### ISSUE TITLE
How can I set a remote image or base64 local image as Navigator button?

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#1027]
Is it possible to set a remote image and/or a base64 local image as a navigator button?  I would also like to style it (set width, height, borderRadius)

I am also trying to put an icon (vector-icon) next to a textual button but I couldn't find a way.

**Comment by jp928** [comment]
@perrosnk 
please follow this https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator.
IMPO, local image with different size would be a better practise than remote image or base64 because you have flexibility to provide different image for different screen resolution, such as image.png, image@2x.png, image@3x.png. Alternatively, you could also have image@1.5x.android.png etc. for android devices.
