### ISSUE TITLE
  This project is a bug more project, it is recommended that anyone don't try

### ISSUE THREAD

**Issue by zuoge85** [wix/react-native-navigation#1044]
this is a project with a lot of bugs，it's not recommanded.

**Comment by Ehesp** [comment]
How about give some feedback or more information? The project is still a work in progress but works absolutely fine. Yes there are bugs but it's still usable.

**Comment by andrewkvavlewhite** [comment]
Yeah, no offense, I'm sure it's going to be great once it's stable but people might want to consider just using the javascript navigator until it's all figured out. I was able to figure out iOS and even get bridge communication working really well, but then I tried android and my entire project basically just fell apart. Have to trash like a week's worth of work.

Maybe it's just the nightly build instability. But I even tried taking their example code, which works fine out of the box all by itself, but it doesn't seem to play nice with other modules because as soon as I add anything to it it pretty much breaks.

**Comment by Ehesp** [comment]
@andrewkvavlewhite The JavaScript navigators are easier to pick up, especially the "new" [`react-navigation`](https://github.com/react-community/react-navigation), however they are too riddled with bugs, performance issues and the inability to do anything complex navigation wise with them.

> but it doesn't seem to play nice with other modules because as soon as I add anything to it it pretty much breaks.

Probably worth mentioning which modules, but due to the way it overrides the React context it will cause issues down the line.

> The example must have some mojo added to it that I can't see because the only way I can get a working instance is by cloning theirs. And that is a frustrating prospect.

Can you share your project? I've followed the docs on a couple of different projects to integrate this with Android and had no issues.

**Comment by andrewkvavlewhite** [comment]
@Ehesp Thanks for the reply. I cannot share the project unfortunately. But I'm wondering if my problem is versioning between dependencies. I don't know if I should start a new thread for this, but it woud be much appreciated if a few things could be answered for me about the Rnn project:

- Is RN 0.43 with Rnn experimental.300 recommended as of now? Should React 16.0.0-alpha.6 not be used? I was hoping someone could share the _safest_ versions of dependencies that are known to cause the least compatibility issues. I just need simple tab capabilities for now that preferably can work with [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) and be reasonably styled.

- Is detox preferred? In the example they don't use the other devDependencies that come stock with RN, and I notice a lot of bugs I run into is versioning issues dealing with debug tools. Is it safe to just scrap them like it seems Rnn did in their example?

- My biggest concern is being dependent on the example code. I want the ability to be able to rebuild my app from scratch at any time. I'm curious about things like detox, because if there are any recommended changes to the RN stock setup that improve robustness by decreasing unnecessary complexity or adding insight to incompatibilities, I'm eager to incorporate them. Are there any suggestions on that front?

Again, I think it's going to be great in a couple months and I'm excited to use it in the future. But I need some assurance of stability for simple tab and styling features in the short term. Sorry for taking advantage of the thread to questions like these, but I'm in a time crunch right now. Thank for your help.
