### ISSUE TITLE
Ability to pass props on dismissModal()

### ISSUE THREAD

**Issue by alexleventer** [wix/react-native-navigation#107]
What's the best way to pass props from a modal on dismiss?

**Comment by guyca** [comment]
For our apps at Wix we use redux, so before dismissing a modal we dispatch an action with the return result.
We'll probably add callback or something similar in the upcoming weeks.

**Comment by pannz** [comment]
And ability to passProps on pop?
Hi, our app design is that there is row item for location info and click it will push to next screen to pick a location, then confirmed,  pop to former screen, but now it's not possible to pass props so that I cound't  pass the picked value to former screen by passProps !
or any solution can also solve this issue ?

**Comment by guyca** [comment]
@pannz when you handle the click on each row, dispatch an action to update state with whatever you need to pass in passProps and handle the state change in the previous screen. That's the best solution I can give you until we implement passing results to previous screen.

**Comment by pannz** [comment]
@guyca thanks !
I just tried use a pass callback func in passProps and found that passProps just accept simple serializable object 😢, and now I'm going to try the dispatch an action as you mention. thanks

**Comment by guyca** [comment]
v2.0 supports passing functions in passProps

**Comment by ghoshabhi** [comment]
@guyca : Any updates as to when v2.0 is releasing ?

**Comment by karlmosenbacher** [comment]
@guyca is it possible to add props to dismissModal yet? Or is it only in V2 ?
