### ISSUE TITLE
Android Contextual Menu if presented modally

### ISSUE THREAD

**Issue by dillonykyang** [wix/react-native-navigation#1095]
### Issue Description

Android showContextualMenu propagates to other navigators if components are presented modally.

### Steps to Reproduce / Code Snippets / Screenshots

Component A with navigators, A.showModal to another Component B.
Component B showsContextualMenu, dismiss the contextual menu by pressing the back button.
Dismiss the Component B modal.
Observe Component A has contextualMenu still overlaying the navigation bar

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.42.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by osadchuk** [comment]
@guyca It looks like we found the problem, in `NavigationActivity.showContextualMenu()`:

```
    public void showContextualMenu(String screenInstanceId, ContextualMenuParams params, Callback onButtonClicked) {
        layout.showContextualMenu(screenInstanceId, params, onButtonClicked);
        modalController.showContextualMenu(screenInstanceId, params, onButtonClicked);
    }
```

That function shows the contextual menu on `layout` (which I think is the presenting Component A in Dillon's description) and the `modalController` (component B). We've been able to resolve the problem by adding a check so that `showContextualMenu()` is called only on `modalController` if it's showing, along with a corresponding `if` clause in `NavigationActivity.dismissContextualMenu()`.  Unless there's a use case I'm not familiar with, I think that if a modalController is showing, the context menu should only show there (or, at minimum, that is our current use case).

If you think the above solution is correct, let me know and I can create a PR.

Thanks!
