### ISSUE TITLE
Can not run Native View from React Native when use React Native Navigation.

### ISSUE THREAD

**Issue by nmjay** [wix/react-native-navigation#1110]
I use react navigation version 1.1.3 and I can not call a Native View from Native project.

All View in Native all does not exist when React Navigation loaded.

I check in code. rootViewController replace.

**Comment by mbizplus** [comment]
Read it at here https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m

**Comment by nguyenminh797** [comment]
@mbizplus I already read. It working but I can not call a Native Controller View. Because I have Native module before. Now I want to load it in New RN project. But it can not show when I use React Native Navigation. It working when I tried with default React Native project (without React Native Navigation)
