### ISSUE TITLE
Scroll inside second tab not working

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#1112]
Hi guy,

I am using startTabBasedApp, at first tab scrollview working but second tab not working. the height alway equal to height of screen.

---
### Environment
* React Native Navigation version: "^1.1.13"
* React Native version: "^0.43.4"
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by guyca** [comment]
Hey @agumack 
Can you please check if downgrading to RN 0.43.0 fixes the issue?

**Comment by agumack** [comment]
Hey @guyca Have same problem with RN 0.43.0

**Comment by brycepavey** [comment]
same issue, RN 0.43.3 react-native-navigation 1.1.17

**Comment by brycepavey** [comment]
I've downgraded to 0.43.0 and also still have same issue. 
I have a scroll-disabled flatlist component inside a scrollview, passing flex:1 through all components has no effect, but if I remove flex from my scrollview and pass only height it works. 

The strange thing is the value of height has no effect. If I set height:0 it works, the scrollview fills space between the components above it down to the tab bar. From what I can tell it seems that any height value less than the actual available screen space to fill allows the view to correctly fill, and same applies for a non-nested scrollview/flatlist. Seems to be a temporary work around for now until the underlying issue is resolved

**Comment by mbizplus** [comment]
great @brycepavey 
tried <ScrollView style={{height: 0}} /> and it work (y)

**Comment by ashemah** [comment]
Thanks @brycepavey! I have been struggling with this for a while. Setting the height of my flatlist (on the second tab) to 0 magically fixed.

Another thing to note: If I call startTabBasedApp and immediately switch to the second tab which had the issue it is sized correctly even without the 0 height hack.

Below is what is in my first screen to immediately switch tabs depending on the selected tab index:
  componentWillMount() {
    this.props.navigator.switchToTab({
      tabIndex: this.props.selectedTabIndex
    });
  }
