### ISSUE TITLE
dismissModal and immediately showModal weird behaviour

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#122]
handle the showModal in some completionHandler after the dismissModal completed

**Comment by Hitabis** [comment]
Same on other actions.
`navigator.push({...})` after `navigator.hideModal()` is not working.

**Comment by simonmitchell** [comment]
We're experiencing the same here, I think that dismissModal needs to return a promise in which you can then perform the secondary showModal. I'm going to take a stab at this now.

**Comment by reubenab** [comment]
Any updates on this? @simonmitchell

**Comment by simonmitchell** [comment]
Yes sorry, we got this working @reubenab but never had a chance to PR it because I haven't been on React Native projects at work for a while now. I have a feeling possibly this was implemented elsewhere by the guys at wix separately from my changes, but not 100% sure on that! If not, it's a fairly simple change to make if you need to make it! Take a look at our fork: https://github.com/3sidedcube/react-native-navigation

**Comment by VSchlattinger** [comment]
If anyone is struggling with this problem and finds this issue (like me), here is how to solve it:

The code is actually fixed, and `dismissModal()` returns a Promise. Unfortunately, the documentation makes no mention of this and thus I was led to believe that dismissModal is a void function.

Working code:

```
navigator.dismissModal({animationType: 'slide-down'}).then(() => {
    navigator.showModal({/* params for new modal */});
});
```

I think this issue can be closed now, however, some changes to the documentation would be nice to avoid this confusion for others.

Side Note for people using TypeScript (like me):

Even the `@types/react-native-navigation` package declares this function as void (I assume that is because of the misleading documentation), so typescript will give you an error if you try the code above. If you don't mind losing type checking for that statement, you can just do the following:

```
(navigator.dismissModal({animationType: 'slide-down'}) as any).then(() => {
    navigator.showModal({/* params for new modal */});
});
```
