### ISSUE TITLE
[iOS] App hung at Splash screen

### ISSUE THREAD

**Issue by thphuc** [wix/react-native-navigation#1246]
### Issue Description
Run example, the app gets stuck at Splash screen with the log: 
2017-05-13 23:36:58.619 [info][tid:main][RCTBatchedBridge.m:75] Initializing <RCTBatchedBridge: 0x7f89d6d39a40> (parent: <RCTBridge: 0x7f89d6e26b20>, executor: RCTJSCExecutor)
2017-05-13 23:36:58.680 [warn][tid:com.facebook.react.JavaScript][RCTModuleData.mm:220] RCTBridge required dispatch_sync to load RCTDevSettings. This may lead to deadlocks
2017-05-13 23:36:58.713 [info][tid:NSOperationQueue 0x7f89d6d1fa30 :: NSOperation 0x7f89d8b0e450 (QOS: LEGACY)][RCTPerformanceLogger.m:80] Unbalanced calls start/end for tag 0

### Steps to Reproduce / Code Snippets / Screenshots
Run example on Xcode 8.3.2, simulator iPhone 6 iOS 9

### Environment
* React Native Navigation version: 1.1.72
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Xcode 8.3.2, simulator iPhone 6 iOS 9, Debug

**Comment by f03lipe** [comment]
@thphuc were you able to fix this?

**Comment by f03lipe** [comment]
See #1191.

**Comment by thphuc** [comment]
Thanks @f03lipe 
But it looks a different issue.

My code 

`// Register screens
registerScreens();

const createTabs = () => {
    const tabs = [
        {
            label: Strings.search,
            screen: SCREEN_NAMES.SEARCH_SCREEN,
            icon: require('../../res/images/ic_search.png'),
            selectedIcon: require('../../res/images/ic_search.png'),
            navigatorStyle: {
                navBarHidden: true
            },
        },
        {
            label: Strings.list,
            screen: SCREEN_NAMES.LIST_SCREEN,
            icon: require('../../res/images/ic_list.png'),
            selectedIcon: require('../../res/images/ic_list.png'),
            navigatorStyle: {
                navBarHidden: true
            },
        },
        {
            label: Strings.add,
            screen: SCREEN_NAMES.ADD_SCREEN,
            icon: require('../../res/images/ic_add.png'),
            selectedIcon: require('../../res/images/ic_add.png'),
            navigatorStyle: {
                navBarHidden: true
            },
        },
        {
            label: Strings.profile,
            screen: SCREEN_NAMES.PROFILE_SCREEN,
            icon: require('../../res/images/ic_profile.png'),
            selectedIcon: require('../../res/images/ic_profile.png'),
            navigatorStyle: {
                navBarHidden: true
            },
        }
    ];

    return tabs;
};

Navigation.startTabBasedApp({
    tabs: createTabs(),
    appStyle: {
        tabBarBackgroundColor: Colors.white,
        tabBarButtonColor: Colors.gray,
        tabBarSelectedButtonColor: Colors.primaryColor,
        tabFontFamily: Fonts.GothamBookRegular,
        forceTitlesDisplay: true,
    }
});`

Do you have any idea?

**Comment by Hizoul** [comment]
I too have the same Problem. Android works perfectly! But iOS just never leaves the Splash Screen.
And since index.ios and index.android import the same main file.

I have adjusted AppDelegate.m and tried (without the ifdefs) using each of the jscodelocations. Also tried using my laptop IP instead of localhost for URL (which works for WebSockets so should work here too) but it didn't. I am also receiving the proptypes warning (https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes)

My Log:
```
2017-06-11 09:06:29.112 [error][tid:com.facebook.React.JavaScript] undefined is not an object (evaluating 'params.screen.navigationParams.screenInstanceID')
2017-06-11 09:06:29.113 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'params.screen.navigationParams.screenInstanceID')
2017-06-11 09:06:31.142722+0200 climbzreactnative[61209:1946157] [] nw_connection_get_connected_socket_block_invoke 9 Connection has no connected handler

```
Using RN 0.45, react-native-navigation 1.1.91, plat

Environment

React Native Navigation version: 1.1.91
React Native version: 0.45.0
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Xcode 8.3.2, simulator iPhone 6 iOS 10.3, Debug

**Comment by Hizoul** [comment]
I have found (by trying to make a minimal example) that using passProps is the root of evil here. If i do passProps: {} screen stays forever white / stays on splashscreen on first start. Also doing passProps: {navigation: Navigator, store: reduxStore} did not work, but I'll work around that.

@thphuc are you using passProps, or is your problem unrelated? like i said I did get it to work now also in a minimal example, so I believe we both might be using some wrong params in the API :)

**Comment by kyle-ssg** [comment]
Hmm I also started getting this 15 mins ago, and a quick google search brought me here. 
```RCTBridge required dispatch_sync to load RCTDevSettings. This may lead to deadlocks``` did seem like it could be the culprit but after digging through my dependencies I think it's unrelated, in my case the error was thrown by ```react-native-fetch-blob``` - removing this had no effect.

I doubt in my case passProps or anything around that is the cause of the issue, I don't think it's even reaching the point where index.ios.js is executed.

I have a feeling (for me at least) the problem is around this line
```2017-06-11 11:56:02.454 [info][tid:main][RCTCxxBridge.mm:184] Initializing <RCTCxxBridge: 0x7f8b17f99d20> (parent: <RCTBridge: 0x7f8b17e9e2a0>, executor: (null))```

I think this should look more like
**executor: RCTJSCExecutor**

**Comment by Eptis** [comment]
I seem to be having the exact same issue and don't use react-native-navigation so this might be more related to react-native itself

**Comment by joonhocho** [comment]
https://github.com/wix/react-native-navigation/issues/1397 related at all? even though https://github.com/wix/react-native-navigation/issues/1397 is for v2.

**Comment by angusmccloud** [comment]
Did this ever get resolved? Doing a long-needed update of RN Core and all my Modules, and running into this issue.  Android works fine, iOS gets hung on the splash screen seemingly indefinitely.

**Comment by juanlet** [comment]
same here....stucked on splash screen

**Comment by garrottkai** [comment]
Getting rid of passProps does seem to work around the issue

**Comment by tarun29061990** [comment]
Its happening with my application on android. In IOS its working fine. Any luck on solving this??
