### ISSUE TITLE
All components Mounts at the same time - TabBasedApp .

### ISSUE THREAD

**Issue by PARAGJYOTI** [wix/react-native-navigation#1250]
### Issue Description

While starting an app with tabBasedApp , all the tabs  mount at the same time the app  is started . Though we can use onNavigator willAppear event in  replacement of ComponentDidMount , still its a terrible idea if we have several number of tabs . I have 5 bottomTabs ,  3 of them having 3 topTabs each . So I almost have 17 tabs which all are being mounted at the same time . Its causing a terrible frame drop in the javascript animation . Once I decrease number of tabs animation speeds frame drop decreases . 
  
   I am wondering if mounting all component at once is a good Idea . However I have seen in other libraries like 'react-navigation'  using the same concept . Please let me know your suggestions 

---
### Environment
* React Native Navigation version: 1.1.70 
* React Native version:  0.43.1
* Platform(s) (iOS, Android, or both?): Android

**Comment by Amurmurmur** [comment]
I think you can use lazyload option to load only active tab scene.

Please check the API documentation to know how to use it.

**Comment by PARAGJYOTI** [comment]
Really ? But I have't found any lazyload option . Can you send me the link . ?

**Comment by Amurmurmur** [comment]
@PARAGJYOTI My bad, confused it with react-navigation. Very sorry :/

**Comment by PARAGJYOTI** [comment]
Yaa I understood you were talking about 'react-navigation' but however I used 'react-navigation' too but it's navigator animations was slow as it was based on JS . so i moved to react-native-navigation . Its a pretty good lib , I found everything I needed .

**Comment by edude03** [comment]
I'm facing this issue as well. I haven't tried to solve it yet, but presumably, you could check if the current screen is visible and return `null` if not

**Comment by Amurmurmur** [comment]
@PARAGJYOTI Did you make it work with react-native-code-push? For me it renders blank. However if I remove
```
app = codePush({ checkFrequency: codePush.CheckFrequency.MANUAL })(app);
```
It renders fine, aka I cant use code-push with this lib.
As for the animation speed, with react-navigation you can use custom animation and pretty much just replace it with the exact same animation that it comes out of the box, with a flat `useNativeDriver: true` and it should be very fast and smooth on both iOS/Android, thats what I currently use with react-native-router-flux.
But since experimental navigation is depreciated we have to move to either react-navigation or react-native-navigation.

**Comment by PARAGJYOTI** [comment]
I never used codepush,so I cannt tell you how to do that . But About navigation , I used only TabNavigation for a swipable tab , but wasn't happy with that . Yaa , you can set useNativeDriver to true , but it has limited properties like transform or opacity , which is enough for navigator by the way . But if you have to choose 'react-native-navigation' and 'react-nvigation' I would just say 'react-native-navigation' . The first one looks like native but second one is native itself .

**Comment by guyca** [comment]
Having all bottom tab screens mounted at the same time is a great idea. If done correctly it means your app is responsive from the start. (The alternative is to load the screen when user enters that tab? or lazy loading? both have major drawbacks which can't be addressed since we can't exactly predict the users interaction at this point)
If you utilize the lifecycle events you've mentioned, you can reduce strain on Js thread.
