### ISSUE TITLE
Swipe forward?

### ISSUE THREAD

**Issue by bentomas** [wix/react-native-navigation#127]
I have a ListView, and I'd like to make it so that when you swipe a list view item from right to left, it drags in a specific screen for that item.  Is this possible?  Maybe by some how manipulating the stack when a swipe happens?

**Comment by guyca** [comment]
Hey @bentomas 
You can try capturing the drag\swipe gesture on the desired view with a `PanResponder` and when appropriate - push a new screen (set `animated: false` when pushing). In the screen you've just pushed, Animate the entire screen content with `Animated` as you see fit.

I haven't tried this, but it might work. We probably won't support such interactions in the library since the swipe gesture is handled in JS and UI manipulation is done natively, and we are limited by the amount of data we can pass on the bridge.
