### ISSUE TITLE
Question: Is there a way to get the current screen title?

### ISSUE THREAD

**Issue by thiagoghisi** [wix/react-native-navigation#1286]
It would be super helpful to track Google Analytics Screen View events.

I was thinking, ideally, it would be available under: `this.props.navigator.title` or `this.props.navigator.getTitle()`. Any thoughts around that? 

More than happy to create a PR if that would be accepted.

**Comment by annelorraineuy** [comment]
This would be really helpful for me too! or even the screen name.

**Comment by guyca** [comment]
You can get the [currently visible](https://wix.github.io/react-native-navigation/#/top-level-api?id=getcurrentlyvisiblescreenid) `screenInstanceId` which is a unique identifier.
You can create some screen registry to be able to map `screenInstanceId` to screens

**Comment by fullhdpixel** [comment]
> You can create some screen registry to be able to map screenInstanceId to screens

Sorry, Im not capable to figure out how to do this. Can you help me with some guidance?

**Comment by windydang26** [comment]
hi @guyca ! thank for awesome lib.
current i'm using getCurrentlyVisibleScreenId to get current screeen in stack navigation. however, i receiverd screen id difference for each case (when i press in difference tab, order of screens).
Ex. app load in tab 1, i click screen 1 and screenId = '1'; but when i press in tab 2, after click screen 2 i still receiver screenId  = '1'. how can i get uniqueId for each screen?

**Comment by Sidharth1999** [comment]
@guyca `screenInstanceId` is a unique identifier, yes, but it's not consistent at all. For example, when tabs are reloaded on the app, the value of `screenInstanceId` changes for the exact **same** screen. Therefore, it's not possible to map `screenInstanceId`'s to screens because two different screens can end up having the same `screenInsanceId`

So, I'm very disappointed that this is the only way to 'uniquely' identify a screen. It's very poor design on Wix's behalf - literally all we need it is a method to return the value of the ID we registered the screen with, **that's all** All problems solved then. 

Currently, not a workable solution for an app with multiple tabs and a sidedrawer to navigate to different screens.
