### ISSUE TITLE
Flow integration

### ISSUE THREAD

**Issue by Baptiste-Garcin** [wix/react-native-navigation#1375]
Hi,

Rather than an issue, it's more an interrogation...

Are you planning to add an easy flow integration ?

Today, it's really hard to type react native navigation objects such as props.navigation.state.params. 

Are you planning to create a [typeDefinition](https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js) like the guys behind react navigation have done ?

Thanks

**Comment by davidhellsing** [comment]
Please!

**Comment by fabryx92** [comment]
I join this request!

**Comment by ghoshabhi** [comment]
Do we have this implemented or anyone else who has done it ?

**Comment by EdwardDrapkin** [comment]
I've got a functional library definition but it's mostly untested, as we just started using this project.  
I'm not 100% sure the file is correct as it's based on the documentation, instead of the code, which I haven't gotten to yet.  I was going to wait to open a `flow-typed` PR until I was certain that it was correct and could type a few examples.  However, if you guys are willing to help me test the library definition, I can give it to you now...

But first, you need to know that it's

 written in such a way that you need to pass around which routes you're using.

So you'll need code like this:


**registrations.js**
```js
// needs to be a map of screen key -> React.Component
export const registrations = {
    root: HomePage,
    'auth.Login': Login
};

export const ScreenRegistrations = typeof registrations;
```

And then in your index file where you mount your app..

```
import type { NavigationStatics } from 'react-native-navigation';
import type { ScreenRegistrations } from 'screens/registrations';

export const MyNavigator: NavigationStatics<ScreenRegistrations> = Navigation;

Object.keys(registrations).forEach(key => {
    MyNavigator.registerComponent(key, () => registrations[key]);
});
```

And whenever you receive a `navigator` prop, declare it with the same Generic parameter:

```
import type { NavigatorProp } from 'react-native-navigation';
import type { ScreenRegistrations } from 'screens/registrations';

type Props = {
   navigator: NavigatorProp<ScreenRegistrations>
}
```

Passing `ScreenRegistrations` around allows Flow to type hint routes so you can't dispatch to unregistered routes and some other trivial checks (that it's a react component getting mounted).

So those are the only caveats, and if you just ignore the generic stuff everything will (theoretically) continue to work.  Let me know if it raises errors you shouldn't get.

And here's the libdef itself: https://gist.github.com/EdwardDrapkin/a844581d1c8602acf1396a720748af1c

One final warning: very much a WIP! Please let me know if it's missing/incorrect in areas!

**Comment by george-steel** [comment]
I've created a wrapper which provides flow integration as well as a few helpers (common Options and deep linking. It is available here:
https://github.com/SatsumaLabs/react-native-typed-navigation
