### ISSUE TITLE
Customise default UIView background colour

### ISSUE THREAD

**Issue by joefocusrite** [wix/react-native-navigation#138]
When using React Native, you can change the background colour of the default UIView in `application: didFinishLaunchingWithOptions:`. Using react-native-navigation, however, this doesn't have an effect because of the way UIViewControllers are vended. 

A corollary of this is that I have a flash of white as the animation for the next scene is pushed onto the stack but before the JS has loaded a new view. I can work around this by adding `self.view.backgroundColor = myBackgroundColour;` in `RCCViewController`'s `commonInit: navigatorStyle: props:` method, but it would be nice to be able to customise this outside of the library. Is this possible?

react-native @ 0.28.0
react-native-navigation @ 1.0.24

**Comment by rmdort** [comment]
I am also experiencing a whilte flash before the JS is loaded. It will be good to have Splash image and a background color option.

**Comment by guyca** [comment]
@artald We've has a similar issue in the past which was fixed in `controllers`, I think you reviewed the PR to fix it.

**Comment by rmdort** [comment]
Yes. the black screen with `controllers` was fixed. But I was wondering if we have a workaround for `white screen` appearing when Javascript is being loaded and executed.

https://github.com/facebook/react-native/issues/1402

How it was fixed in react-native was by loading a Launch screen

````
NSArray *nibObjects = [[NSBundle mainBundle] loadNibNamed:@"LaunchScreen" owner:self options:nil];
UIImageView *loadingView = [nibObjects objectAtIndex:0];
loadingView.frame = self.window.bounds;
rootView.loadingView = loadingView;
````

RCTRootview has `loadingView` property, But react-native-controllers doesnt. Is there a better way of doing this? Everytime i open the app for the first time, I see the splash screen, then  white background and then the app.

**Comment by SudoPlz** [comment]
Any news on that?
