### ISSUE TITLE
Start the app dynamically based on Redux State

### ISSUE THREAD

**Issue by jarvisluong** [wix/react-native-navigation#1459]
I want to make an app that use Redux state to save the authentication of the user, if not logged in, show the single screen app with the log in screen, and if they are logged in, show the tab app.

Is there any way around to achive this in this library?

**Comment by TimoGlastra** [comment]
That is how i implemented it, though with localstorage. I try to check if there is data stored on the phone. If there is data, it will start an TabBasedApp otherwise it will start an SingleScreenApp where the user can input his data. After the user has saved their data, it will reinitialize the app and start an TabBasedApp

**Comment by smooJitter** [comment]
@jarvisluong here's a nice demonstration.  

https://github.com/apparena/app-arena-native-app/blob/master/src/app.js

**Comment by jarvisluong** [comment]
@smooJitter I really like the way the App class is design, mocking a React Component 👍

**Comment by Ehesp** [comment]
Yep that example is exactly how you do it. Remember redux isn't React specific, so you can just get state or dispatch actions in the initial class. Inside your app, just update that same state with react-redux and it'll all fit together.
