### ISSUE TITLE
Use redux for screen navigation?

### ISSUE THREAD

**Issue by NathHorrigan** [wix/react-native-navigation#1486]
Does anyone have a working implementation of redux for screen navigation? for example:

```
Action:
{
  type: 'NAVIGATE'
  payload: {
    screen: 'example.PushedScreen',
    title: 'Pushed Screen'
  }
}

Somewhere in redux:
navigator.push({
  screen: 'example.PushedScreen',
  title: 'Pushed Screen'
});
```

**Comment by jaspal747** [comment]
You can refer to the old-redux-example and see how you can subscribe to the relevant store actions in redux.

https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js

**Comment by NathHorrigan** [comment]
Is there a way to access the navigator object other than when it is provided by props?

**Comment by jaspal747** [comment]
One way you could do it is pass the navigator as a param while dispatching the action. Then in your saga or other function, after you process the action, you can use the  navigator to resetTo the screen you want... Please refer Mattharrison's comment here: https://github.com/wix/react-native-navigation/issues/826

**Comment by tmaly1980** [comment]
@jaspal747 

> Then in the saga or any other file, I can use MainNavigator and call push, pop, resetTo or any other methods.

What about showModal? What do you mean earlier about not using it? In my case I have a login screen I want to always show as a modal, but need a way from a saga to trigger opening it.

**Comment by rauliyohmc** [comment]
Another alternative is to use `componentWillReceiveProps` inside your component. Say, you have some sagas/thunks that are handling some authentication logic and you would like to push to the main screen (or reset the stack) once you have an access token. Since you'll likely stash that access token in your redux store, once the action that sets it is dispatched, your _connected_ `LoginScreen` component that listen to that state piece will receive new props and you can react to it in the next way:

```javascript
componentWillReceiveProps(nextProps: Props) {
  if (this.props.accessToken !== nextProps.accessToken) {
    this.props.navigator.resetTo({
      screen: 'example.mainScreen',
      title: 'Main Screen',
    });
  }
}
```

**Comment by jaspal747** [comment]
@tmaly1980 
When I save an instance of the navigator in the MainNavigator class, that instance does have have control over the Modals (so I cannot show/hide modals using redux). 
I had read somewhere that RNN uses multiple navigators under the hood and synchronizes them.. so from what limited knowledge I have about it, I figured that modal navigator is a different obj than the screen navigator, and hence storing the instance of screen navigator won't help me use Modals.
I might be wrong here, but this logic seems to be working for me...

Hope this helps

**Comment by felipemartim** [comment]
@jaspal747 I used a very similar approach, until I noticed that if I'm using Tabs, each tab has its own navigator instance. That means that if I'm on a different tab than the one I used to set the navigator object, I won't be able to pop the current screen, for example. 

I'm still trying to figure out the best way to solve this, but I think I'll just have to go for the action callback approach.

**Comment by alimek** [comment]
Hi @jaspal747 

So you decided to not use `showModal()` at all ? Because I am using the same approach as you, but now got a use case that modal should be helpfull, but after modal is shown, my all actions after `showModal()` stoped working :(

if you have any solution,  please let us know :)

**Comment by jaspal747** [comment]
Hi @alimek,

I would suggest you look at using 
React Native's Modal https://facebook.github.io/react-native/docs/modal.html
or another modal plugin like 
https://github.com/react-native-community/react-native-modal

In my application, I used the React Native's modal instead of using the React Native Navigation's modal.

Cheers!

**Comment by alimek** [comment]
Thanks @jaspal747 for comment.

This is how I handle modal as well 👍
