### ISSUE TITLE
[Feature request] iOS 11 Style Navbar Titles 

### ISSUE THREAD

**Issue by hammadj** [wix/react-native-navigation#1643]
### Issue Description

Almost every iOS 11 app has this new style for navigation titles:

![ios11 nav title](https://user-images.githubusercontent.com/7143583/28991088-f617b5e4-7940-11e7-92ca-ca14ba6b4d5d.gif)

It would be great to support this natively with react-native-navigation since it seems to be the new UI standard for iOS. It shouldn't be too difficult to accomplish either because I believe iOS has a simple API to enable it: https://developer.apple.com/documentation/uikit/uinavigationbar/2908999-preferslargetitles

**Comment by chrise86** [comment]
There are 2 parts to this, the large titles and the ability to set a `searchController` on the `navigationItem` - both would be a very welcome addition 👍

**Comment by B3rry** [comment]
+1

**Comment by phuongwd** [comment]
+1

**Comment by PavSidhu** [comment]
the API you suggested can't be used because React-Navigation is purely Javascript. This would need to be recreated from scratch.

**Comment by jarvisluong** [comment]
@PavSidhu did you just go to the wrong repo? this is react-native-navigation, not react-navigation

**Comment by PavSidhu** [comment]
@jarvisluong Yeah, I just realised my mistake and removed my comment.

**Comment by joaqtor** [comment]
+1

**Comment by eliperkins** [comment]
Configuring `prefersLargeTitles`, `largeTitleTextAttributes` and `largeTitleDisplayMode` should be pretty straight forward, since they're all similar properties to what we expose already.

Configuring `searchController` will not be as straight forward, since we don't have an API for search controllers anywhere in React Native.

Also, as a reminder to all those commenting "+1", please use the reactions instead of comments, so as not to spam this thread with unhelpful comments. Pull requests to implement this functionality would be more than welcome!

**Comment by gnihphp** [comment]
+1

**Comment by jarvisluong** [comment]
Any update from this feature?

**Comment by Sauri89** [comment]
+1

**Comment by Sauri89** [comment]
+1

**Comment by Burnsy** [comment]
@gran33 Hello, Is there any chance you could give us some insight why the support was removed and if and when it could be re added? Thank you!

**Comment by anonrig** [comment]
Any eta on this?

**Comment by xmarianox** [comment]
Any updates on this issue?

**Comment by oferRounds** [comment]
+

**Comment by chrise86** [comment]
There was a pull request that got merged, then reverted (as shown above). The reason for this I _think_ was due to the scrollview/header jumping as it went from large to small.

I tried this myself and it is indeed an issue; one that does not feel acceptable to use at this point. As this is a simple 1-liner config I'm not sure where to look to "fix", it almost seems like an Apple bug.

As pointed out in the discussion around the pull request, a similar issue appears in the [Parcel](https://parcelapp.net/) app, if anyone wants to take a look. No idea whether Parcel is RN or not though...

**Comment by chrise86** [comment]
There was a pull request that got merged, then reverted (as shown above). The reason for this I _think_ was due to the scrollview/header jumping as it went from large to small.

I tried this myself and it is indeed an issue; one that does not feel acceptable to use at this point. As this is a simple 1-liner config I'm not sure where to look to "fix", it almost seems like an Apple bug.

As pointed out in the discussion around the pull request, a similar issue appears in the [Parcel](https://parcelapp.net/) app, if anyone wants to take a look. No idea whether Parcel is RN or not though...

Possibly linked to issues discussed here https://stackoverflow.com/questions/46703469/shrink-large-title-when-scrolling-not-uitableviewcontroller-ios-11

**Comment by brunolemos** [comment]
I think #2090 wasn't merged because it doesn't support Xcode8, only Xcode9+

https://github.com/wix/react-native-navigation/pull/2090#issuecomment-346097255
https://github.com/wix/react-native-navigation/pull/2090#issuecomment-346989447

**Comment by chrise86** [comment]
@brucelawson you're correct, sorry. That aside, the scroll / janky issue is still very much an issue 😕

**Comment by brunolemos** [comment]
It should be easy to fix this xcode 8 support and get it merged, I think they even wrote the solution there, just nobody made the updated pr

**Comment by brunolemos** [comment]
Well, turns out this feature is already on v2! I just tested this and it works:

```js
export default class MainScreen extends PureComponent {
  static get navigationOptions() {
    return {
      topBar: {
        largeTitle: true,
        title: 'brunolemos'
      }
    };
}
```

<img width="368" alt="image" src="https://user-images.githubusercontent.com/619186/34019419-f62655f8-e115-11e7-80c9-e4c1295b3faa.png">

**Comment by anonrig** [comment]
Hello @brunolemos unfortunately, v2 still has some major missing features, and therefore it's not production ready.

**Comment by hammadj** [comment]
Made a PR for this here: https://github.com/wix/react-native-navigation/pull/2593

**Comment by chnouman** [comment]
for android in java or kotlin?
