### ISSUE TITLE
React-Native-Navigation and React-Navigation from React-Native Compatibility

### ISSUE THREAD

**Issue by nucleons** [wix/react-native-navigation#1699]
Hi Guys

Currently I am using React Navigation from React_native in my app. I am planning to integrate wix react-native-navigation. Are the two compatible with each other. Like the stack maintainance and passing of data between two components?

**Comment by pqkluan** [comment]
*React-Navigation* is a Javascript based navigation, that means all the navigate happen inside of single Activity (on Android and iOS counterpart). 

The good part about Javascript based navigation is they will work on most platforms. But they usually suffer from performance issues due to stacks everything in the same activity.

*React-Native-Navigation* on another hand is an actual native navigation. Every screen has their own native container that handles by native system. Better optimize better performance at the cost of deep integrate for each platform.

For that reason, *you could put a whole react-navigation system inside one react-native-navigation screen* if you want. But by doing something like that you'll make your app unnecessary complex.
