### ISSUE TITLE
navBarHeight

### ISSUE THREAD

**Issue by tkulpa** [wix/react-native-navigation#1767]
I want to get navBarHeight from style, i need this to set google map position with additional components below navbar, any ideas?
---
### Environment
* React Native Navigation version: 1.1
* React Native version: 0.46.1
* Platform(s) (iOS, Android, or both?): Android

**Comment by guyca** [comment]
Hey @tkulpa 
navBar height is consistent across devices - https://stackoverflow.com/questions/30570904/whats-the-height-of-the-android-toolbar

**Comment by danilobuerger** [comment]
@guyca Wouldn't it be possible to provide a method that returns the height of the currently displayed nav bar? I know these values are constant, but it would be nice to have it in this lib so that not every app has to reinvent the wheel and keep track of these constants. 

For example, on iOS I could do something like `self.navigationController.navigationBar.frame.size.height` from a UIViewController to get this programmatically.
