### ISSUE TITLE
global ScreenVisibilityListener can't get component instance

### ISSUE THREAD

**Issue by Tomatoo** [wix/react-native-navigation#1846]
i want to record view visit in global ScreenVisibilityListener, so i want to get pageName, component instance(get specific props，for example article id). but i can't get component instance, how can i do this?

**Comment by farzadshafiee** [comment]
This is also a problem for me. In the context of analytics, the props that has been pushed with the screen also matters (e.g. which product page is being reviewed) since the screen name is the same. I want to refrain from polluting the actual component lifecycle hooks and centralize and abstract away the whole analytics module since there might be more than one analytics service in use. It seems natural to have the passed Props (`passProps`) available in the **RNNScreenVisibilityListener** component. I was curious to know if there's any specific reason that it's not already there.

**Comment by farzadshafiee** [comment]
It is still an issue.
