### ISSUE TITLE
Using MobX instead of Redux

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#187]
Is anyone using Mobx instead of Redux? If yes, would it be possible to share some boilerplate?

**Comment by mastermoo** [comment]
+1

**Comment by knot123** [comment]
+1

**Comment by adamski** [comment]
Just started looking at MobX and I'd be interested in using it with RNN too.. 
+1

**Comment by adamski** [comment]
According to https://github.com/aksonov/react-native-mobx it is "framework" free so in theory should be able to use it with RNN as-is. I will try this soon...

**Comment by perrosnk** [comment]
If you could share a boilerplate if you manage to do it, it would be very helpful for the whole community I think!

**Comment by mastermoo** [comment]
@perrosnk @adamski @knot123 there u go... [navigation-mobx-example](https://github.com/mastermoo/navigation-mobx-example).
It's based on this [redux-example](https://github.com/wix/react-native-navigation/tree/master/example-redux).

**Comment by mastermoo** [comment]
@guyca it would make sense, to add the mobX example to this repo, as well. What do u think?

**Comment by guyca** [comment]
@mastermoo Thanks for taking the initiative and making an example project. MobX sounds interesting and we're excited to hear you got navigation working with it. Are you using MobX with Navigation in production? 

If it's ok with you, I'll link your project and this thread in the readme file. Adding another example project isn't feasable at this time, since we can't commit to another framework. We have a lot planned for the library and adding officially supporting another framework will add a lot of overhead.

**Comment by mastermoo** [comment]
Yes it's good with me.MobX is really a joy to use compared to redux. Yes, currently, I'm building a fairly complex app using Navigation and MobX. 😊Good to hear, that there is a lot planned for this library! I would really like to contribute to this repo, but I don't know any Objective C :/

		_____________________________

**Comment by stief510** [comment]
+1

**Comment by vonovak** [comment]
+1

**Comment by maxs15** [comment]
+1

**Comment by DanielZlotin** [comment]
Great work @mastermoo ! 
One of the changes I have planned is to separate redux/mobx/other state containers from the core of this framework. 

Optimally we would have the core Navigation, and on top of it (either another npm module completely or just a different module inside the framework) some wrappers that inject the state container logic into the screens. 

For example you import `react-native-navigation/redux` or `react-native-navigation/mobx` instead of `react-native-navigation`. 

This is just an idea right now as we have far more pressing concerns. In any case, this shouldn't be hard, and far more extensible. Can be assigned to milestone 2.1.0 I think.

**Comment by grin** [comment]
@DanielZlotin though, do we even need to make RNN aware of any framework (redux/mobx) at all? 
IMHO that shouldn't be necessary (even with separate npm modules). 
Instead of `_registerComponentRedux` and `_registerComponentNoRedux` functions we could have just one function similar to this:

```js
function _registerComponent(screenID, generator, CustomWrapper) {
  const generatorWrapper = function() {
    const InternalComponent = generator();
    return class extends Screen {
      // ...
      render() {
        if (CustomWrapper) {
          return (
            <CustomWrapper>
              <InternalComponent navigator={this.navigator} {...this.state.internalProps} />
            </CustomWrapper>
          );          
        } else {
          return (
            <InternalComponent navigator={this.navigator} {...this.state.internalProps} />
          );          
        }
      }
    };
  };
  registerScreen(screenID, generatorWrapper);
  return generatorWrapper;
}
```
which just takes a user-provide wrapper component. 
So for example, to enable Redux in your app all you'd need to do would be:

```js
function CustomReduxWrapper(props) {
  return (
    <Provider store={store}>
      {props.children}
    </Provider>
  );
}
```

and then register a screen with this:
```js
Navigation.registerComponent('app.ExampleScreen', () => Example, CustomReduxWrapper);
```

The benefit of this approach is that it removes knowledge of Redux (Provider + store) from RNN and also enables support for other frameworks.

As for MobX support, my understanding is that it's already possible by just decorating components with `@observer`, so no need of any work on RNN side other than maybe adding some more docs/examples.

**Comment by DanielZlotin** [comment]
Completly agree, and that was my plan. However I do think a helper wrapper
function can be useful for some.

**Comment by danikenan** [comment]
+1

**Comment by holmesal** [comment]
+1

**Comment by pietgk** [comment]
+1

**Comment by megahertz** [comment]
I've created the mobx-react Provider which can be used with RNN.
https://gist.github.com/megahertz/3aad3adafa0f7d212b81f5e371863637

**Comment by bawn** [comment]
+1

**Comment by kyle-ssg** [comment]
I share @grin 's opinion on this -  I think any form of coupling with things outside of react would hinder the project a great deal

**Comment by keyadesai** [comment]
+1

**Comment by justinhaaheim** [comment]
+1

**Comment by didil** [comment]
+1

**Comment by kanzitelli** [comment]
Hey guys, 

I have created a small boilerplate RNN + MobX with Provider as @megahertz described [before](https://github.com/wix/react-native-navigation/issues/187#issuecomment-265946012)

https://github.com/kanzitelli/react-native-navigation-mobx-boilerplate

And if anyone is going to try it, please let me know how it goes 👍

**Comment by anhtuank7c** [comment]
@kanzitelli 
Thank you so much.
You saved my day.

**Comment by avishayil** [comment]
Hey @kanzitelli , I noticed that `componentWillReceiveProps` does not work on observer components, like `FirstTab`.
Any idea why?

**Comment by yezongyang** [comment]
use componentWillReact

**Comment by drewmca** [comment]
+1

**Comment by andreaskarantzas** [comment]
+1

**Comment by ethanyanjiali** [comment]
+1

**Comment by colincwilliams** [comment]
+1

**Comment by romandubrov** [comment]
+1

**Comment by LouisJS** [comment]
+1

**Comment by kyle-ssg** [comment]
You guys should close this issue, state management has nothing to do with this project surely.

**Comment by JorgeCeja** [comment]
+1
