### ISSUE TITLE
Tabbar always is over contentview

### ISSUE THREAD

**Issue by danceyoung** [wix/react-native-navigation#195]
I have set navigatorStyle={drawUnderTabbar:true},but the bottom Tabar still over contentview

RN Version: 0.31
react-native-navigation version: 1.0.30
platform:android

**Comment by guyca** [comment]
Fixed in version v2.0

**Comment by danceyoung** [comment]
but current version is 1.0.30 in NPMJS

**Comment by guyca** [comment]
@danceyoung That's correct. v2.0 is still under development, you can check it out if you change the version in `package.json` to `next` instead of `^1.0.0` or whatever you're using.
Theres a short [migration guide here](https://github.com/wix/react-native-navigation/blob/v2.0/README.md#migrating-to-version-20)

**Comment by SimchaShats** [comment]
Have the same thing on ios 9, experimental-2.0.167

**Comment by yorkie** [comment]
+1 on same issue
