### ISSUE TITLE
Passing functions as props is not possible in `navBarCustomViewInitialProps`

### ISSUE THREAD

**Issue by nicreichert** [wix/react-native-navigation#1961]
### Issue Description

When customising my Navbar, I need to have access to either the `navigator` object or to be able to pass callbacks to my components, so I can add behaviours to its buttons. However, since the `navBarCustomViewInitialProps` object is serialised in JSON, all the functions are gone, once I receive the object as `props` inside my component.

### Code Snippets

This is what I'm trying to do:

```js
class Navbar extends PureComponent {
    componentWillMount() {
      this.props.navigator.setStyle({
        navBarCustomView: NAVBAR.screen,
        navBarCustomViewInitialProps: {
          onShowDrawer: this.handleShowDrawer,
        },
      });
    }

    handleShowDrawer = () => this.props.navigator.toggleDrawer({
      side: 'left',
      animated: true,
    });

    render() {
      return <Components />;
    }
  }
```

However, inside my component, the `props` object won't even show a `onShowDrawer` property.

I might be wrong, but I perceive this not as being a bug, but a limitation. Are there plans to implement a way to pass functions as `props` to custo view in navbars? 

Thanks.

### Environment
* React Native Navigation version: 1.1.228
* React Native version: 0.48.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info: Simulator - iOS 11

**Comment by cambaughn** [comment]
Agreed, this is pretty limiting. I'm trying to do something similar, with a search bar as a custom view, and passing functions for searching from the parent.

**Comment by fforres** [comment]
Have you folks found an alternative/workaround? @nicreichert or @cambaughn

**Comment by cambaughn** [comment]
@fforres I'm using Redux, so I just ended up storing my search results in my Redux store to make it accessible without passing props (which I should have done from the beginning anyway), and then building the functionality directly in my custom component. 

Because you can only pass initial props to the custom navbar component, it makes sense to implement the functionality you need in Redux. If you're not using Redux, you might be able to do something similar with React context, but I didn't try that, and I'm not sure if that will work, depending on how the Navbar custom component is rendered.

**Comment by cambaughn** [comment]
@nicreichert I was going to say that you should have access to the navigator as a prop on your custom view, since it's registered as a component, but I just checked mine, and apparently we don't? Is it only tabs that get the navigator, not all registered components?
