### ISSUE TITLE
Need RTL Support for Tab Navigation

### ISSUE THREAD

**Issue by coder4affine** [wix/react-native-navigation#1977]
### Issue Description

As per my believe there is no support for RTL for tab navigation. 

### Steps to Reproduce / Code Snippets / Screenshots

I am using I18N for switch the language b/w arabic and english. but I did not find any way for RTL support for navbar and tab navigation.

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.48
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by jadidian** [comment]
Any updates on this? I really like `react-native-navigation` because of its smooth transitions / animations but I had to use `react-navigation` with all its glitchy transitions in my latest project only because it supports RTL; I think this is an important feature for lots of people speaking Hebrew, Arabic, Persian, Azeri, Urdu etc. and deserves more attention from the development team.

**Comment by blackhair** [comment]
Need to RTL `tabNavigator` items, please fix it

**Comment by RamanDEEP225** [comment]
is there any way to support RTL by using react-native-navigation npm in IOS, I did this in android but not in IOS, is it possible?
