### ISSUE TITLE
Will it support "titleView" in the future version ？

### ISSUE THREAD

**Issue by leotu** [wix/react-native-navigation#198]
It is only support string or image, I hope it could be more flexibility  in navigator bar title area, 
i.e. SearchBar

**Comment by guyca** [comment]
@leotu We will probably provide support for SearchBar in ToolBar (At least on Android) since this feature is requested a lot by the community. But I can't guarantee on time frame.

We're also considering supporting custom react views in the tool bar. I hope to experiment with this once the Android version stabilizes more.
