### ISSUE TITLE
Use react-intl with react-native-navigation

### ISSUE THREAD

**Issue by stefanedberg** [wix/react-native-navigation#2044]
### Issue Description

Is it possible to use react-intl (and other third-party libraries that uses higher-order components) with react-native-navigation?

### Steps to Reproduce / Code Snippets / Screenshots

Wrapping your root React component with <IntlProvider>:

```
ReactDOM.render(
    <IntlProvider
        locale={usersLocale}
        messages={translationsForUsersLocale}
    >
        <App/>
    </IntlProvider>,
    document.getElementById('container')
);
```

**Comment by rawrmaan** [comment]
Since there is no root component in RNN, you'll have to wrap each Screen with your HOC. I was also considering using this library for localization but I realized that it was too bulky for my needs and ended up writing my own localization library in <100LOC that just handles locales and string interpolation. Works like a charm. I can open source it if there's demand.

**Comment by tbazko** [comment]
In our app we solved it this way. So we made a wrapper around `ReactIntlProvider` as we need some custom logic:
```
    import { IntlProvider as ReactIntlProvider } from 'react-intl';
    import PropTypes from 'prop-types';
    import React, { PureComponent } from 'react';
    
    class IntlProvider extends PureComponent {
      static propTypes = {
        children: PropTypes.node.isRequired,
        locale: PropTypes.string.isRequired,
      };
    
      /* some custom logic */
    
      render() {
        return (
          <ReactIntlProvider
            locale={locale}
            messages={messages}
          >
            {this.props.children}
          </ReactIntlProvider>
        );
      }
    }
```

Then in `providers.js` wrapping  `ReduxProvider` around  `IntlProvider`.  You can actually skip creating `IntlProvider` and just wrap `ReduxProvider` around `ReactIntlProvider`:
```
    import { Provider as ReduxProvider } from 'react-redux';
    import React from 'react';
    import PropTypes from 'prop-types';
    import IntlProvider from './intl-provider';
    
    const Providers = ({ store, children }) => (
      <ReduxProvider store={store}>
        <IntlProvider>
          {children}
        </IntlProvider>
      </ReduxProvider>
      );
    
    Providers.propTypes = {
      children: PropTypes.node.isRequired,
      store: PropTypes.object.isRequired,
    };
    
    export default Providers;
```
Then, instead of passing Redux Provider to `registerScreens` method pass `Providers` which I mentioned above:
```
    import { Navigation } from 'react-native-navigation';
    import { configureStore } from 'store';
    import { registerScreens } from 'screens';
    import Providers from './providers';
    
    const { store } = configureStore();
    registerScreens(store, Providers);
    
    class App {
      constructor() {
        Navigation.startSingleScreenApp({
          screen: {
            screen: 'Root',
          },
        });
      }
    }
    
   export default App;
```

**Comment by stefanedberg** [comment]
Thank you very much @tbazko

**Comment by Titozzz** [comment]
Hello, I like your approach, however I need to access the translation before startSingleScreenApp to get the screen title right. Any idea on how I could do that ?

**Comment by Titozzz** [comment]
I did, but since then I've migrated to react-not-native-navigation, so I don't have my code around anymore

**Comment by ialmoqren** [comment]
Does anyone figured out how can I access the translations before `Navigation.setRoot` to get the screen title right, even if it's a workaround, thank you guys
