### ISSUE TITLE
SplashActivity Shows for Extended Period of Time

### ISSUE THREAD

**Issue by jarredwitt** [wix/react-native-navigation#2050]
### Issue Description

We have our SplashActivity set up as follows:

```
public class MainActivity extends SplashActivity {
  @Override
  public int getSplashLayout() {
      return R.layout.launch_screen;
  }
}
```

When we start our application the splash screen hangs for 6-8 seconds before we can call`startSingleScreenApp`. I've been trying to dig into the Android side and can't find where the hold up is. It seems like `startReactContextOnceInBackgroundAndExecuteJS()` gets called pretty quickly, but after that it takes around 6-8 seconds for `onDestroy` to be called on the SplashActivity. Any ideas on what could be causing the delay before the SplashActivity gets destroyed? Just as a side note, this only happens on Android, `startSingleScreenApp` on iOS gets called in under 2 seconds. 

---
### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung Galaxy S6 Android 7.0

**Comment by sunny635533** [comment]
good idea! hope consider it,please.

**Comment by thechefchen** [comment]
Wow, I have the same issue today. Glad that I found another instance. At the same time, did you have any luck addressing the issue?

**Comment by guyca** [comment]
SplashActivity doesn't hang... as you've stated your self - `startReactContextOnceInBackgroundAndExecuteJS` is called right off. Your bundle has gotten big and takes a long time to parse.
We've experienced this at Wix, and realized it's due to modules being all imported at once. Try deferring module loading by requiring them only when you need to.

Another major culprit are screens.
Try registering your screens like this:
```js
Navigation.registerComponent('example.MyScreen', () => require('./screens/MyScreen');
```

This means your screen, and all of its imports will be required only when the screen is actually needed, and not when the app is launched and bundle is parsed.

**Comment by miguelespinoza** [comment]
@guyca, when you refer to:
> Try deferring module loading by requiring them only when you need to.
Is this specific to all modules (JS and native)? or only native modules?  Do you have an example of how Wix handles this issue?

**Comment by thechefchen** [comment]
Hi @guyca 

I did more digging today.

For our case, the scenario is opposite. When the app is backgrounded for an extended time and being re-opened, the splash screen would show for a very short amount of time, then `openTabBasedApp` would be called but it's another splash screen!

To fix this, I have to either force kill the app to re-open or background again then foreground.

I notice for the successful opening case, the splash screen would show longer than the unsuccessful ones. I think that's the time to load the JS modules.

I'm not an Android expert but I think these two commits [Finish SplashActivity if it's opened over NavigationActivity](https://github.com/wix/react-native-navigation/commit/0c389b5dac42d49208eb4279e43d9308943e2723) and [Finish SplahActivity if react context exists](https://github.com/wix/react-native-navigation/commit/5c266e4436de130b22621072d7257f89600e80f4) might be related since they both call `finish` early.

I suspect could it be the case that when the app is backgrounded and killed, some JS instances are not killed properly. Then when it needs to reload the JS context, then the splash activity is beining `finished` too early?

**Comment by miguelespinoza** [comment]
@thechefchen you may be seeing the same issue I was. 
Check: https://github.com/wix/react-native-navigation/issues/2682
