### ISSUE TITLE
Is there any way to hide Running application log?

### ISSUE THREAD

**Issue by miriyas** [wix/react-native-navigation#2100]
### Issue Description

Below images, RNN logs are too verbose to debug.
Is there any options for toggle it off I didnt know?
Thanks.

![image](https://user-images.githubusercontent.com/1982486/32205271-b0e6be76-be31-11e7-8d9c-a8ec61e9cc0e.png)

### Environment
* React Native Navigation version: 1.1.246
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

**Comment by rgoldiez** [comment]
I'm also interested in this.

**Comment by guyca** [comment]
This is actually coming from [react native](https://github.com/facebook/react-native/blob/e10f7788c4ebf29d96594f9753264bdf6146f0cf/Libraries/ReactNative/AppRegistry.js#L172). Maybe `infoLog` can be swizzled or perhaps there's a control boolean somewhere.

**Comment by miriyas** [comment]
https://github.com/react-community/react-navigation/issues/360
maybe this one is related.

**Comment by yomybaby** [comment]
Any way to remove? :) 🙏

**Comment by jveldboom** [comment]
From within the console, I've been using this regex to filter out the logs. Not the most ideal way since it has to be added each time you launch the debugger, but it does work.

`/^(?!.*(infoLog.js|RCTLOG.js))/`

Looks like this:
![image](https://user-images.githubusercontent.com/303202/38434955-37407fe2-399e-11e8-8412-d7e2324c14b9.png)

**Comment by guyca** [comment]
I'm closing as this isn't an actual RNN bug or issue
