### ISSUE TITLE
add supports with expo

### ISSUE THREAD

**Issue by huangl7759** [wix/react-native-navigation#2104]
i want to use react-native-navigation in expo ,but it seems not supported until now,i was expecting
when these twos can be integrated! thanks for that

**Comment by guyca** [comment]
I'm not familiar with Expo. Does it support native modules?
Anyways, wether possible or not - I don't think this will be happen any time soon as this isn't in our scope.

**Comment by mjsisley** [comment]
Expo works w/ JS only. react-native-navigation uses native modules, it won't work w/ Expo. 

Your best move for navigation with Expo is using react-navigation. You could build w/ react-navigation with Expo, eject at the end, and refactor to using react-native-navigation. Or you could build w/o Expo in order to use this library (and other libraries that require native modules).
