### ISSUE TITLE
v1 to v2 Migration Path?

### ISSUE THREAD

**Issue by larryranches** [wix/react-native-navigation#2137]
There are about 250k downloads a month for the react-native-navigation v1 as this shows the popularity of being a top RN navigation solution. Knowing that v2 is currently in development right now.

I think this is an important question to ask. Will there be a migration path from going to v1 to v2 when v2 is ready?

**Comment by hugows** [comment]
Also, someone starting today should use v1 or v2?

**Comment by smooJitter** [comment]
I called this about 4 months ago V1 is so sweat already and well maintained.  The work on V2 has gone well on for well over a year now. My app registers more than 90 screens and I expect that to double. While I using HoC, I’m still curious as to how V2 can add value.  I hope, more than anything else, it addresses the concerns with swipdecks and carousels.

**Comment by Kielan** [comment]
Migration path is very important, as the version 2  framework comes from a new solution for app registering. Because this is a dependency for react native which is a forever changing code based javascript layer on top of core mobile it is critical that there be a guide and wiki for this top routing solution. Here are some links to get started.

https://medium.com/react-native-training/react-native-navigation-v2-by-wix-getting-started-7d647e944132
https://github.com/birkir/hekla/blob/master/package.json
