### ISSUE TITLE
Clearing a redux state before rendering a page

### ISSUE THREAD

**Issue by jonching** [wix/react-native-navigation#2150]
### Issue Description

It seems basically impossible to perfectly clear a redux state before rendering a page. For example, I have a component that has details and photos for a local business (like yelp). Every time I want to render this page, it has the details from the previous data that was on this component. This is because calling a redux dispatch on 'willDisappear' doesn't seem to finish updating the state. Calling a redux dispatch to clear the data on 'willAppear' or even in the constructor doesn't seem to work either because the navigation seems to always render the page with the state it has before running any actions. 

The result is that it makes it very hard to have smooth pages. There will almost always be a flicker showing the previous data if you are sending api calls to fetch new data.

**Comment by pqkluan** [comment]
I don't think this problem belongs to the navigation but the way your management your app state.

I suggest you remove the old data before you start navigating or using loading status either base on new data fetching status or hard code delay whenever render the new screen.

**Comment by iksent** [comment]
I have some similar issue:

There are Redux with its store (and data in it) and screens in TabBasedApp.

Then I want to reset stack to single screen app, so I call "Navigation.startSingleScreenApp", and in "then" of it I make dispatch to reset store data. And I get a lot of errors, because screens in TabBasedApp are in render too for some strange reason.

So how can I remove screens from previous rendering, when calling startSingleScreenApp?
