### ISSUE TITLE
v2 Setting parameters

### ISSUE THREAD

**Issue by iwangx** [wix/react-native-navigation#2154]
### Issue Description

```
Navigation.events().onAppLaunched(() => {
    Navigation.setRoot({
        container: {
            name:"name"
        }
    });
});
```
I don't know where the other parameters should be written.Please give an example to demonstrate the use of parameters.
---
### Environment
* React Native Navigation version: 2.0.1937
* React Native version: 0.50.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by johngoren** [comment]
Although I like the powerful new options that v2 seems to bring, I wonder if there's a possibility of improving the top-level API so that it is as graceful and easy to read as the one in v1. Right now the setRoot example suggests an impressive combination of tabs and stacks. 

I found the format more confusing and less intuitive than v1, where the ease of reading and the clarity of the concepts was a major selling point for me compared to some of the other RN packages (some of which rely on abstractions that seem unnecessarily abstract.) I'm looking forward to using v2 but hope that the setRoot is a work in progress towards something as great as v1's.

**Comment by DanielZlotin** [comment]
I agree, and you are correct it's still a work in progress. The api right now best represents what actually happens in the native side in both platforms and allows us to make as little assumptions as possible.
This is important for extensibility and flexibility.
We had several discussions about what we can do and one possibility we all liked is to create templates for common patterns.
Another option we always thought about is wrapping this API with JSX, but that will require more work.

**Comment by DanielZlotin** [comment]
@iwangx the best example is the playground project, under `/playground`

**Comment by thienpow** [comment]
@iwangx passProps after name attribute
