### ISSUE TITLE
Trouble using with react-native-youtube

### ISSUE THREAD

**Issue by ifsnow** [wix/react-native-navigation#2160]
I'm in a trouble to use `react-native-navigation` with `react-native-youtube`.

https://github.com/inProgress-team/react-native-youtube/issues/161#issuecomment-338648074

As you can see from the link above, Youtube official sdk does not allow overlay layout(com.reactnativenavigation.views.SnackbarAndFabContainer) during playback.

I don’t need this features(fab&snackbar) on this project, but `SingleScreenLayout` always creates this container. I want to be able to turn this feature off and on manually. Could you think about this feature?

I hope to hear good news.

**Comment by guyca** [comment]
Hey @ifsnow
Could you please upload a project where this issue is reproducible? I'd like to take a stab at it.

**Comment by ifsnow** [comment]
@guyca Here is a sample project about this issue. I hope this helps.

https://github.com/ifsnow/react-native-navigation-issue-2160

**Comment by guyca** [comment]
Thanks, I'll get to it asap.

**Comment by GoaGit** [comment]
@guyca we run into the same issue with our app. Could you please indicate if you expect this issue to be resolved soon? I am asking because we will be running a large campaign in the second half of January. In-app Youtube videos are a major part of that. Since we need to run these campaigns, we need to decide on short notice how to deal with this issue.

We are happy to test an update to check if the issue is being resolved.

**Comment by nimamyscreen** [comment]
any update for this issue??

**Comment by praveenapoojary** [comment]
This issue still exists. Any update on this?
