### ISSUE TITLE
Android animationType on startSingleScreenApp not working

### ISSUE THREAD

**Issue by anhuin69** [wix/react-native-navigation#236]
The animation caused by the FLAG_ACTIVITY_CLEAR_TASK in the startApp call cannot be removed or edited. The option 'animationType' isn't handled on Android I guess.

Is there a particular reason to do a clear task here?
Do you think it would be possible to remove the animation with a call like overridePendingTransition?

**Comment by guyca** [comment]
Hey @anhuin69 `FLAG_ACTIVITY_CLEAR_TASK` is there due to unfortunate design decisions I made in v1 of the Android branch. We wanted to clear the back stack whenever `startSingleScreenApp` and `startTabBasedApp` are called. The easiest and quickest solution I could think of at the time was to use activity flags. 

Overriding the activity start animation isn't supported yet, but should be available in the final release of v2.

/cc @drorbiran

**Comment by DanielZlotin** [comment]
No way around the `FLAG_ACTIVITY_CLEAR_TASK` flag at the moment. We *can* just replace everything in the activity without actually restarting it.. but not in the current milestone. In any case, overridePendingTransition should work, and if not, we'll think of something.

**Comment by anhuin69** [comment]
Hey guys, thanks for the answers and for your work!
As it is definitely not critical for now I'll keep following your work on the v2.

This lib is a life saver on iOS but I face some challenges using it on Android. As you said I think all those challenges are related to the design of the first Android version. I would be glad to help once you have a public v2 branch.

**Comment by guyca** [comment]
`2.0.0-experimental.75` adds support for `animationType: none` on Android. Other animation types are not supported yet.
