### ISSUE TITLE
React Native 0.51

### ISSUE THREAD

**Issue by michaelmerrill** [wix/react-native-navigation#2431]
### Issue Description

This library does not work with any RN version greater than 0.49. Please update the Readme to reflect this or update the library to work with the latest RN version. I realize that v2 is under development, however the community is currently invested in v1 of this project and needs it to work until v2 is ready for production (or at least in beta).

---
### Environment
* React Native Navigation version: v1.1.323
* React Native version:  > 0.49
* Platform(s) (iOS, Android, or both?): Android and iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All devices

**Comment by guyca** [comment]
Hey @michaelmerrill 
Feel free the PR the readme 👍 
At any case, next week (Sunday or Monday) we will bump minimum supported version to 0.51

**Comment by chaitanya0bhagvan** [comment]
@michaelmerrill if you mention the issues you are facing the community will be able to help. A blanket statement serves no purpose.

**Comment by nebsi04** [comment]
@michaelmerrill I just got react-native-navigation v1.1.323 working with react-native v0.51.0. This combination is working on my end for both Android and iOS (so far).

I started with react-native v0.48.4 per @pqkluan 's comment here #2201 . Then I followed the instructions [here](https://wix.github.io/react-native-navigation/#/). I set up the basic usage instructions, ran it and it worked. I did discover that tabs: { icon: require('./example/example.png) } is needed or you'll see a white blank screen.

Then, my plan was to run react-native-git-upgrade to upgrade to react-native v0.49.0 and test that upgrade. But I forgot to specify v0.49.0 and I accidentally upgraded to react-native v0.51.0. So, I tried it and it is working so far with just the [usage](https://wix.github.io/react-native-navigation/#/usage) example from the docs.

I had a pretty tough time getting the Android install to work because I was either not doing it right or making small mistakes. What helped me is I downloaded [example](https://github.com/wix/react-native-navigation/tree/master/example) app even though it is a little old. I built/ran that example to ensure it worked, then when I followed the instructions I did some comparison between the instructions and the android files. 

I'm pretty excited for v2! I am way behind so I have to at least start prototyping all of my screens. This is the most high performance navigation solution I have found for react-native yet (spent a long time with react-navigation). Thanks to the team for making this available.
