### ISSUE TITLE
Need document for v2.0

### ISSUE THREAD

**Issue by fengliu222** [wix/react-native-navigation#251]
In 2.0, some new features should have document to description.
For example, how many params allow pass to `appStyle` ?

**Comment by guyca** [comment]
@fengliu222 The reason we didn't update the docs yet is because new features we've added are not available on iOS. Also, the api is not final and updating the docs is very time consuming.
We're working on a change log file which should help a bit, and obviously the docs will be updated in due time.

Regarding `appStyle`, this api might change soon and is not available on iOS. it accept any property that can be set in `navigatorStyle` and few more. You can look at the source code [here](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.android.js#L113)
