### ISSUE TITLE
Are you supporting react native version 0.52.0?

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#2520]
Are you supporting react native version 0.52.0?

it seems not,

current version is: 1.1.338
Android

**Comment by aspidvip** [comment]
me to no work react native version 0.52.0

**Comment by alien3d** [comment]
maybe they still trying test after react-native create a new update..  https://github.com/wix/react-native-navigation/issues/2512

**Comment by johakr** [comment]
see https://github.com/wix/react-native-navigation/pull/2494

**Comment by guyca** [comment]
Hey @Jaafar-abusair 
No, we're still not supporting 0.52.

**Comment by MiLeung** [comment]
The readme says "Latest stable version is 1.1.x and is published to npm under tag latest. It supports react-native 0.43 through 0.51", but the [iOS installation page](https://wix.github.io/react-native-navigation/#/installation-ios) says "Make sure you are using react-native version >= 0.51. We also recommend using npm version >= 3", and @guyca is saying 0.52 is not supported.

So that means the only RN version you should use is 0.51?!

**Comment by alien3d** [comment]
@MiLeung  . I used  0.48  after react native  introduce literal string cannot be support in 0.49.. After 0.50, i think  react native introduce the single index.js then 0.52 introduce new method again for error message error and i would said wait a little bit,because not fault of this repo at all .  I have tested on version 0.51. But for stable for me is 0.48.

**Comment by SudoPlz** [comment]
Ok so at first there was this PR:
https://github.com/wix/react-native-navigation/pull/2545

but then another great fella created this one which is backwards compatible too.
https://github.com/wix/react-native-navigation/pull/2580

@guyca just came back from vacation and he'll be merging that tomorrow, so you can close that issue and track 2580 instead.
