### ISSUE TITLE
Android bottom tab press doesn't do 'back' behavior (iOS does)

### ISSUE THREAD

**Issue by jslz** [wix/react-native-navigation#2592]
### Issue Description

Discrepancy between iOS and Android behavior with bottom tab taps. I want the iOS behavior on Android.

### Steps to Reproduce / Code Snippets / Screenshots

1. assume a Multi tab app, starts up on 1st bottom tab.
1. Press on 3rd bottom tab.
1. In that tab, press on app's button that push()es a screen.
1. Now press on the 3rd bottom tab again.
iOS: screen pops and 3rd bottom tab's contents are seen.
Android: nothing happens.

---
### Environment
* React Native Navigation version: 1.1.331
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All android devices, all build types.

**Comment by pqkluan** [comment]
The is no out-of-the-box solution for this. You have to mimic the iOS behavior by using [bottomTabReselected](https://wix.github.io/react-native-navigation/#/screen-api?id=listening-to-tab-selected-events) event at the root screen of each tab.

You could also create a pull-request for this feature. If you do so, please re-open this issue and link to the pr.

**Comment by Galti** [comment]
Are you going to provide this feature in v.2?

**Comment by donovanhiland** [comment]
Is this still the case in v2 @pqkluan?

**Comment by ryzhak** [comment]
I can confirm that in RNN 3.1.2 behavior is the same.

Any solution for ios to prevent screen pop on tab press?

**Comment by AnthonyAkentiev** [comment]
@pqkluan why this issues was closed?

**Comment by pqkluan** [comment]
Hi @AnthonyAkentiev,
This issue was closed in 2018 because there are too many open issues (500+ IIRC).

I’m understanding this is a positive feature request, but because of the lacking of man power & resource it was closed to help the team focus on more important core features and bug fixes.

As I commented before closing the ticket, the OP could re-open the issue if he could work on a PR to implement this feature.
