### ISSUE TITLE
Gradient is not working with the wix/navigation component

### ISSUE THREAD

**Issue by tranhuuthinhit** [wix/react-native-navigation#2599]
### Issue Description

I'm using wix/react-native-navigation, it working ok. But when I integrate react-native-linear-gradient, I got the error Invariant Violation: Native component for "BVLinearGradient" does not exist.

---
### Environment
* React Native Navigation version: 1.1.352
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Simulator

**Comment by perrosnk** [comment]
This probably doesn't have to do win RNN.
Have you tried adding libBVLinearGradient.a to Build Phases -> Link Binary With Libraries?
See also this: https://github.com/react-native-community/react-native-linear-gradient/issues/157

**Comment by tranhuuthinhit** [comment]
I got a problem on Android. I think RNN changed the MainApplication class extends from "Application implements ReactApplication" to "NavigationApplication". 

We can see the RNN document https://wix.github.io/react-native-navigation/#/installation-android

**Comment by Stephanevincenza** [comment]
Same issue with RN 0.51 and 0.52,RNN 1.1.365,RN-linear-gradient 2.4.0 : LinearGradient works fine with iOS, and fails with android.
"Invariant violation : Native component for 'BVLinearGradient' does not exist"

**Comment by Stephanevincenza** [comment]
SOLVED !

The issue was really simple : when you modified your Mainapplication.java, you probably removed (as it's mentionned on RNN docs ) all the imports needed to work. That's what I made.

You should add all libraries and linked them in Mainapplication.java.

I had the same error, and it works now.
Here's my right Mainapplication.java :
///////////////////////////////////////////
package ############### (hidden project name)
import com.facebook.react.ReactPackage;
import java.util.Arrays;
import java.util.List;
import com.reactnativenavigation.NavigationApplication;
import com.BV.LinearGradient.LinearGradientPackage;
import com.AlexanderZaytsev.RNI18n.RNI18nPackage;
import com.horcrux.svg.SvgPackage;

public class MainApplication extends NavigationApplication {

  @Override
  public boolean isDebug() {
    // Make sure you are using BuildConfig from your own application
    return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
    // Add additional packages you require here
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
            // eg. new VectorIconsPackage()
            new LinearGradientPackage(),
            new RNI18nPackage(),
            new SvgPackage()
    );
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }
  @Override
  public String getJSMainModuleName() {
    return "index";
  }
}

IT WORKS NOW !!!

**Comment by pqkluan** [comment]
This issue is a native-linking problem, and the problem resolved. 
I'll close the issue, feel free to re-open if needed.
