### ISSUE TITLE
How to fix lagging move screen

### ISSUE THREAD

**Issue by dhamdani666** [wix/react-native-navigation#2607]
Hi , 

i used react native navigation but after move screen why very slow ?
is there a way to maximize to move screen faster?

this is the result :

![re](https://user-images.githubusercontent.com/13973698/35497051-196e0f84-04fb-11e8-98a5-d2494abeefa7.gif)

* React Native Navigation version: 1.1.351
* React Native version: 0.50.0
* Platform(s) (iOS, Android, or both?): Xiaomi Redmi 4

* Device info (Simulator/Device? OS version? Debug/Release?): Device , OS Version : 6.0.1 Marshmallow , Debug

**Comment by pqkluan** [comment]
The lag could be caused by the device specs, background task, how you implement the JS code. It's tough to resolve your problem here. 

StackOverflow would be a more suitable place for this issue. You could re-open this if you think the problem belongs to RNN and have the example code to re-produce.
