### ISSUE TITLE
White Screen Problem during Compilation with RN 0.53

### ISSUE THREAD

**Issue by alexsmartens** [wix/react-native-navigation#2674]
**Issue Description**

Compiling current react-native-navigation with RN 0.53 causes white screen. Furthermore, at this stage ('white screen') device debug menu does not work. 
The problem appears when react-native dependency version is set up to "0.53.0", like in the [example](https://github.com/wix/react-native-navigation/blob/60e62e1a53c2e29bc8547d5938fcf1888e72b1ff/example/package.json#L15).

**Steps to Reproduce / Code Snippets / Screenshots**

If you compile current [RN 0.53 Example](https://github.com/wix/react-native-navigation/tree/master/example), you will have the same problem until you change RN dependency version in [package.jason](https://github.com/wix/react-native-navigation/blob/60e62e1a53c2e29bc8547d5938fcf1888e72b1ff/example/package.json#L15) to "0.51.0" for example

---
### Environment
* React Native Navigation version: 0.53.0
* React Native version: 1.1.371
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Moto G (2nd Generation), Android version: 6.0=

**Comment by alexsmartens** [comment]
# I think this issue might be connected to  #2580

**Comment by guyca** [comment]
Closing as won't fix.

**Comment by padupuy** [comment]
Hello @guyca, I encountered the same problem as  @alexsmartens .
Could you explain why the bug won't be fix ?

**Comment by guyca** [comment]
The example app uses RN 0.53 and works. Other then suggesting this issue happens with RN 0.53, no further information is provided.
As there's no way for me to debug this further, I don't see a point keeping this issue open.
Regardless, we're working focusing on v2 and are trying to spend as less time as possible on v1.

**Comment by Ehyeh-Asher-Ehyeh** [comment]
@guyca I am having this same problem, but I can provide some more information: 

- first, this is only a problem on Android
- second, it is only a problem with redbox/dev menu, so only for dev builds
- third, it is only noticeable if you deploy to a device, rather than an emulator

The reason you only see it on device is, as far as I can tell, because SplashActivity doesn't call any methods to provide the ReactInstanceManager with the current activity, so we can't open the dev menu to set the address of the packager. The emulator will just use the default setting to send requests for the packager to the machine it is running on, so we pass by SplashActivity and into NavigationActivity, which _does_ call NavigationReactGateway::onResumeActivity, which calls through to ReactInstanceManager::onHostResume, which sets the current activity.

We need the activity set to display redbox and dev menu since this https://github.com/facebook/react-native/commit/d19afc7 change, which was included in RN 0.52.0. It specifically mentions
> This change can break things for framework users who provide custom implementation of DevSupportManager interface on Android

which is relevant for the JsDevReloadListenerReplacer in this library, unless I'm mistaken.

**Comment by Ehyeh-Asher-Ehyeh** [comment]
Unfortunately not: we were already phasing out our use of react-native-navigation in favor of an internally-developed navigation library, so I simply hastened that process somewhat once I established why the upgrade-branch was having problems on android. Since you can subclass SplashActivity to customize the splash appearance, I suppose you could override its onResume to put in a call to NavigationReactGateway? I haven't checked, so this is just a suggestion.

**Comment by axlider** [comment]
@Ehyeh-Asher-Ehyeh: Thanks for sharing your experience! Meanwhile i ran in to some more issues on both platforms. So I will propably also search for alternatives.
