### ISSUE TITLE
Sidemenu   click

### ISSUE THREAD

**Issue by lilitGrigoryan** [wix/react-native-navigation#2835]
Hi i have a sidemenu with buttons , but when i click on button in sidemenu , instens of my button on press  sidemenu is closing. this bug only on android.

---
### Environment
* React Native Navigation version: v2
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by LeJPR** [comment]
ran into the same issue. Believe this is because LayoutFactory.java is iterating through the sidemenu view types, and is adding the leftview before adding in the contentview, and creating issues with z index. quickly hacked layoutfactory to always add sideMenuLayout.setCenterController first before left or right and it fixed the issue. Will see if i can get some time to do a PR later in week..
