### ISSUE TITLE
Leveraging Alternative Native Drawer Behaviors

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#3]
First, I'm a newbie to react-native and I know very little about native IOS and Android.  I've bee searching for an approach to handle navigation and routing for reach-native apps. I tried react-native-router-flux and I was satisfied. So far, I like my experience with react-native-navigation. For the most part, it's easy to reason about.  I started with react-native-controller but a few days ago, my demo project broke giving me react-native, react, and react-native-controller package conflicts.  Nevertheless, its easy to find my way around this package. 

I have a few questions,

1. Are all the features available to react-native-controller available to this package. 
2. What do you think it would take to  leverage native drawer behaviors such as, 

-     jondanao/TheSidebarController:  https://github.com/jondanao/TheSidebarController
-     romaonthego/RESideMenu: https://github.com/romaonthego/RESideMenu/

I ask because, similar to this package, these implementations seem ( correct me if I'm wrong) based on native view controllers.

**Comment by talkol** [comment]
Interesting to check why react-native-controllers broke for you, because this package is also based on it. If I had to guess, you need to switch to react-native >= 0.19.0 and update dependencies with `npm update`. If this still doesn't work, I urge you to open an issue under react-native-controllers with details about the errors you're getting.

Re. your questions:

1. Ideally yes, we're working hard to expose everything the react-native-controllers offers. If we've missed something, open an issue about it and we'll make sure it's exposed.

2. The best place to add these would be under react-native-controllers. It shouldn't be difficult because react-native-controllers is designed exactly for this purpose. I think the first one you've shown (jondanao/TheSidebarController) is excellent and the entire community would benefit from it. I'll ask someone to add it to react-native-controllers and then we'll expose it here as well. @gran33 - would you like to take it?

**Comment by smooJitter** [comment]
Hi @talkol, I noticed react-native control now allows for a range of drawer options. I'm playing around with the latest react-native-navigation, if I upgrad to the new controller, will these options be exposed or do I need to make other adjustments?

**Comment by talkol** [comment]
not yet supported there, we're still in the middle of a merge :)

**Comment by smooJitter** [comment]
Just wondering, I read something about rewriting the how the navigation controller stack is managed.  I also read something about building on top of NevigationExperimental. Are you talking about one these when you write "merge"?

**Comment by drorbiran** [comment]
Drawer is available in v2.0
