### ISSUE TITLE
Android crash when call Navigation.startSingleScreenApp the second time

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#300]
What version of `react-native` you are using
0.31.0
What version of `react-native-navigation` you are using
2.0.0-experimental.105

Hi my app crash when call Navigation.startSingleScreenApp the second time :(

`java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.phonewindow$decorview not attached to window manager`

**Comment by guyca** [comment]
@agumack Can you reproduce the crash in the example project? What does "call Navigation.startSingleScreenApp the second time" mean? When you refresh the app? press home button, then open it again from app drawer?

**Comment by agumack** [comment]
yep @guyca 

When i refresh the app. 
First time LoginScreen loaded. After user login ok => I call Navigation.startSingleScreenApp to join app. 

React-native-navigation old version < experimental.95, this feature work fine. 
I don't know why, too.

**Comment by DanielMaly** [comment]
I have been seeing a similar problem. It was occurring when I was hiding a loading indicator after login (implemented using Modal from react-native). I think the problem was that the view, which was being dismissed as part of a root change was at the same time trying to re-render because I had hidden the loading indicator. When I gave up on trying to hide it - the view was disappearing anyway - the problem went away.

**Comment by guyca** [comment]
@agumack This flow is working fine in the example project and in our production apps.
I think you should investigate what @DanielMaly mentioned. Can you check if before you're calling startApp you're also updating store which in turn re-renders a screen that just got detached from window?

Also, You've mentioned this doesn't reproduce on version below 0.95. Can you try and identify the exact version where this issue started? Because I doubt the commit that was added in .96 causes this.
Thanks

**Comment by agumack** [comment]
@DanielMaly @guyca yep ActivityIndicator 
thanks so much!
