### ISSUE TITLE
No red screen if app fails on initialization

### ISSUE THREAD

**Issue by shlomokraus** [wix/react-native-navigation#3068]
### Issue Description

When application is failing before final render, no red screen is displayed and all I get is a white screen. I can't access any of the debugger features such as reload or access the dev settings (nothing happens when shaking the phone).

---
### Environment
* React Native Navigation version: 1.443
* React Native version: 0.54
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug on device and simulator

**Comment by chinookng** [comment]
@shlomokraus you probably have an error on initialization and my guess will be the icons for the navigation. To see the redbox you will have to downgrade your react-native version to version 0.51(the minimum version supported by react-native-navigation)
- Open package.json and change the react-native version to 0.51.0
- In your project root run the following commands
 * 'watchman watch-del-all'
* remove node_modules ( in your project root type 'rm -rf node_modules)
* npm install
* npm start -- --reset-cache    

Run your project, you should see the Redbox, fix any error and upgrade your react native back to the version it was before.

I hope this helps.

**Comment by shlomokraus** [comment]
@chinookng Thanks, I tried it and the red screen does shown on 0.51. The problem is not the icons. It is because I am using Haul which doesn't support delta bundles and on first load it is required to enter dev settings and disable them. Since there is no red screen I can't access the dev menu nor reload.

But the problem is much wider than that. Even I fix this issue, will it happen every time there is an error on initialization? How come downgrading react-native helped and is there anything I can do to fix this behavior on newer versions?

**Comment by krystofcelba** [comment]
#2801

**Comment by manoj-k-mishra** [comment]
I was facing this issue for past two days- finally found the error in android studio logcat.
--------------------------------------------
@ 6607-6640/com.appname E/ReactNativeJS: Error while starting app: Error: No icon defined for tab abc.
@ 6607-6607/com.appname E/unknown:ReactNative: Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: console.error: "Error while starting app: Error: No icon defined for tab abc
--------------------------------------------
As soon as I defined the icons, everything started working:

 constructor() {    this._initApp()  }
  _initApp() {
    Navigation.startTabBasedApp({
      tabs: [
        {    label: 'Feeds',   screen: 'instagramclone.FeedsScreen',     title: 'Instagram',
             icon: require('./images/icon1.png'),
        },
        {     label: 'Explore',    screen: 'instagramclone.ExploreScreen',     title: 'Explore',
              icon: require('./images/icon1.png'),
        },
      ]
    })
  }
