### ISSUE TITLE
Lightbox does not rerender but modal does

### ISSUE THREAD

**Issue by stokesbga** [wix/react-native-navigation#3090]
### Issue Description

Whether passProps or redux connect, shouldComponentUpdate and re-render does not fire on new props. However, showModal instead of showLightBox works as expected.

### Steps to Reproduce / Code Snippets / Screenshots

1. showLightBox -> passProps from state
2. change state
3. Nothing happens

---
### Environment
* React Native Navigation version: 1.1.422
* React Native version: 0.53
* Platform(s) (iOS, Android, or both?): Only tested on iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 8

**Comment by guyca** [comment]
Hey @stokesbga 
Lightbox isn't supported anymore and was dropped in v2 in favor of simplified API called Overlay. As v2 is still late alpha and you might not be ready to switch to v2, perhaps you should use Modal instead of lightbox.
Regardless, I'm closing as this won't be addressed. Sorry for the inconvenience.

**Comment by stokesbga** [comment]
No inconvenience at all! Thanks for what you guys do, its incredible work.

**Comment by RamiroIsBack** [comment]
all right! I was experiencing some weird behavior with the light boxes and couldn't get them to receive props properly either thanks for the heads up. Switching to modals until new version is ready, thanks guys
