### ISSUE TITLE
Use only icons without label at TabBar

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#311]
I want to use only Icons and not the labels at the TabBar, and possibly reduce the height of the TabBar.
It seems that this is a more modern to design a TabBar, because Facebook and Airbnb are already designing like this.
For react-native-controllers it has been discussed here, and some solutions are already developed:
https://github.com/wix/react-native-controllers/pull/60
https://github.com/wix/react-native-controllers/pull/62
https://github.com/wix/react-native-controllers/pull/75

**Comment by guyca** [comment]
Sounds like a good feature

**Comment by taltultc** [comment]
+1

**Comment by DavoCg** [comment]
+1

**Comment by IharKrasnik** [comment]
+1

**Comment by maddes** [comment]
You can remove the labels easily, just don't include them on the params.

But reducing height is currently imposible as it uses AHBottomNavigation behind the scenes and it has the height hardcoded as 56dp (because it follows material spec):

Hardcoded dimension:
https://github.com/aurelhubert/ahbottomnavigation/blob/137f8f5d85c8a648189eaade9368c37dd56baa38/ahbottomnavigation/src/main/res/values/dimens.xml#L7

Material Spec:
https://material.io/guidelines/components/bottom-navigation.html

**Comment by guyca** [comment]
This is already supported.
