### ISSUE TITLE
[V2] iOS works, android does not. undefined is not an object

### ISSUE THREAD

**Issue by heroic** [wix/react-native-navigation#3139]
### Issue Description
I setup a new project with v2. The app works fine on iOS, but throws an error on Android.

```
undefined is not an object (evaluating 'this.nativeCommandsModule.setRoot')
setRoot
    index.delta?platform=android&dev=true&minify=false:1637:49
setRoot
    index.delta?platform=android&dev=true&minify=false:69161:63
setRoot
    index.delta?platform=android&dev=true&minify=false:1540:45
<unknown>
    index.delta?platform=android&dev=true&minify=false:1454:46
emit
    index.delta?platform=android&dev=true&minify=false:3748:42
__callFunction
    index.delta?platform=android&dev=true&minify=false:2654:49
<unknown>
    index.delta?platform=android&dev=true&minify=false:2424:31
__guardSafe
    index.delta?platform=android&dev=true&minify=false:2616:13
callFunctionReturnFlushedQueue
    index.delta?platform=android&dev=true&minify=false:2423:21
```
### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 2.0.2274
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by francisbrito** [comment]
Hello @heroic,

I think this is happening because `react-native-navigation` is not being included in your `MainApplication`'s `getPackages` result. This could be because the method is being overriden. If you need to add additional native packages, consider overriding `createAdditionalReactPackages` instead as it will not override the required package.
