### ISSUE TITLE
error: cannot find symbol class ReactApplication

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#314]
### Issue Description

I've just updated to the latest `2.0.0-experimental.113` (from `97`)

I'm getting errors similar to below. Seems very much related to #299 and [android/build.gradle](https://github.com/wix/react-native-navigation/issues/285#issuecomment-245182822) but I've tried different combinations and still getting these build errors. 

Is it possible that an older version of RN has been cached somewhere and is using that instead? I've cleaned and rebuilt, deleted all files in the `build` folder... 

### Steps to Reproduce / Code Snippets / Screenshots

```
/path-to-project/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
Error:(7, 26) error: cannot find symbol class ReactApplication
Error:(8, 26) error: cannot find symbol class ReactNativeHost
Error:(17, 76) error: cannot find symbol class ReactApplication
Error:(57, 12) error: cannot find symbol class ReactNativeHost
Error:(56, 5) error: method does not override or implement a method from a supertype
```

<img width="443" alt="screen shot 2016-09-16 at 14 13 43" src="https://cloud.githubusercontent.com/assets/14980/18588365/0b6d9254-7c1e-11e6-869a-03239de29162.png">

---
### Environment
- [ ] React Native Navigation version: [2.0.0-experimental.113]
- [ ] React Native version: [0.31.0]
- [ ] Platform(s) (iOS, Android, or both?): [Android]
- [ ] Device info (Simulator/Device? OS version? Debug/Release?): [Simulator, 6, Debug]

**Comment by guyca** [comment]
@adamski Did you try to `clean` + `invalidate cache and restart` ?

**Comment by adamski** [comment]
No, I didnt, just tried that and seem to be in the same place.

**Comment by guyca** [comment]
It's definitely and a gradle issue. Try changing the maven closure in `build.gradle` to
```groovy
maven {
            url "$rootDir/../node_modules/react-native/android"
        }
```

**Comment by adamski** [comment]
That seems to have fixed it, thanks for the suggestion. Very strange (and frustrating...!) - this was working fine before with `$projectDir`.

**Comment by nucleons** [comment]
@guyca Really thanks, I was trying to find a solution for past 2 days.

**Comment by amcsi** [comment]
@guyca Thanks! That URL entry was already there for me, but I was able to deduce that the problem was that I needed to make sure `npm install` was properly run :)
To be safe, I deleted `node_modules` first, then did `npm install`, then deleted the `.gradle` folder, and now everything works!

**Comment by gagangoku** [comment]
I ejected from expo, my build.gradle is as follows:
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
`

Tried npm install (after removing node_modules/) and deleting .gradle folder as well. Still getting this issue

**Comment by DhirajKate** [comment]
@gan

> I ejected from expo, my build.gradle is as follows:
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     repositories {
>         jcenter()
>         google()
>     }
>     dependencies {
>         classpath "com.android.tools.build:gradle:3.1.4"
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         jcenter()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }
>     }
> }
> ```
> Tried npm install (after removing node_modules/) and deleting .gradle folder as well. Still getting this issue

Yes having same issue, I ejected Expo and tried react-native run-android command, but still showing the issue.

**Comment by Zeroxys** [comment]
I have the same issue, how can solve it ?

**Comment by vahidreza** [comment]
@Friendly-Robot thanks for the valuable info. I changed the version of react-native in `packages.json `file and then did a `yarn install `and after that `npm run android` did the job perfectly without any error.

**Comment by gagangoku** [comment]
Haven't tried @Friendly-Robot 's suggestion, I ended up creating a React native app without Expo and directly running on Simulator !

**Comment by vahidreza** [comment]
@gagangoku  I guess your suggestion could be the most suitable way for me to do things but I got some errors regarding some plugins later in one project some time ago using pure `react-native init` process, but on all my other expo ejected apps I did not have that specific issue( although I had other issues :) ) so I chose this way and may be choosing other ways in the future because everything in the react-native area is changing very fast. 

Below is my complete findings on how to properly eject expo app with no issues (at least for me) and I have tested this procedure 3 times by using current versions:

issues 1) if while doing `create-react-native-app` and choosing a template it tried to download it and then it failed and then you get zip extraction errors go to `~/.expo` in finder (im using a mac)  and delete this folder and try again

issue 2)error: cannot find symbol class ReactApplication 
after doing `create-react-native-app [appname]`
you will run `npm run eject` in the folder of the `app: [appname]` and you have to choose empty project or else you have to manually remove all expo references from the tab based project later or you will get common react native errors...

then you have to upgrade the `gradle` version in `android/app/build.gradle` file to the proper version (mine should be 3.1.3)
you have to have the following setting in `android/build.gradle` file
    allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
           url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

then open android studio and let it sync gradle and download everything.
then based on @Friendly-Robot  change the react version in `packages.json` to the proper version (mine should be 0.55.2)
then do `yarn install`

then add an index.js file into the root of your project with below code
    import App from './App';
    import { AppRegistry } from 'react-native';
    AppRegistry.registerComponent('AppName', () => App);

then `npm run android` and it will be successfully installed.

**Comment by omerg** [comment]
@Friendly-Robot resetting react-native dependency and running `yarn install` version worked for me. Thank you!
