### ISSUE TITLE
cannot find symbol class ReactInstanceDevCommandsHandler

### ISSUE THREAD

**Issue by harshadcpatel** [wix/react-native-navigation#3211]
### Issue Description
Error:cannot find symbol class ReactInstanceDevCommandsHandler
Error: method does not override or implement a method from a supertype

![screen shot 2018-05-15 at 6 41 43 pm](https://user-images.githubusercontent.com/30864404/40058877-2546ba86-5870-11e8-9db8-aa5bb13c47bd.png)

(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

yarn add react-native-navigation@1.1.336
Run the project 

---
### Environment
* React Native Navigation version: 1.1.336
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device and Simulator, 8.0, Debug and release both

**Comment by onuroo** [comment]
I met same error. RN version 0.51.0, react native navigation version 1.1.328.

How can we solve this problem ??

**Comment by harshadcpatel** [comment]
@onuroo  can you please tell me which version of react native are you use?
I am using 0.51

**Comment by Igum92** [comment]
Same issue here on RN 0.48.4. Updating react-native-navigation to 1.1.458 results in https://github.com/wix/react-native-navigation/issues/3207

**Comment by nurkuspan** [comment]
@onuroo not sure if this will be helpful as I didn't use react-native-navigation, but did experience the React Native version mismatch. 
The react-native-navigation version of 1.1.458 is compatible with 0.51, according to the documentation (>=0.48, https://www.npmjs.com/package/react-native-navigation/v/1.1.458).

For the React Native version mismatch, you can force react native version in your project/android/app/build.gradle file by changing 
 ` compile "com.facebook.react:react-native:+"`
to
`compile ("com.facebook.react:react-native:0.51.0") { force = true }` or any version you are using instead of `0.51.0`. 

Here is the link of the issue: https://github.com/facebook/react-native/issues/19259
