### ISSUE TITLE
Build failed when using buildToolVersion 27 and android support 27

### ISSUE THREAD

**Issue by yudhaputrama** [wix/react-native-navigation#3262]
### Issue Description
I make a React native project android with dependency com.android.support:appcompat-v7:27.+ but in react native navigation using  com.android.support:design:25 and build tool 26

Then i build my project throw error

It work when i change version in node_modules manually

### Error Message
```
:app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-v4' has different version for the compile (26.1.0) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution
```
---
### Environment
* React Native Navigation version: 1.1.457
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Real Device, Debug
* Build Tool Version : 27.0.3

**Comment by guyca** [comment]
This is not an issue with RNN, but rather a gradle dependency issue. Please open an issue in SO

**Comment by zubko** [comment]
I think the issue is that in RNN v2 the version is hardcoded:
<img width="641" alt="screen shot 2018-11-21 at 9 21 21 pm" src="https://user-images.githubusercontent.com/16039/48861091-cb549300-edd3-11e8-8619-d2b56b775aa6.png">

while in the docs there is `build.gradle` file with `supportLibVersion` param:
<img width="436" alt="screen shot 2018-11-21 at 9 21 03 pm" src="https://user-images.githubusercontent.com/16039/48861173-08208a00-edd4-11e8-84db-8e4bba5ddba2.png">

so I'd expect RNN to use that param.
I'm no way an Android expert, but looks like it's possible for a dependency to use the param set from the 'root project'. For example from `react-native-maps`:
<img width="999" alt="screen shot 2018-11-21 at 9 44 23 pm" src="https://user-images.githubusercontent.com/16039/48862273-e5dc3b80-edd6-11e8-9e0e-4f5728a2ee3a.png">

I can submit a PR if you agree.
