### ISSUE TITLE
consolidate orientation and screenBackgroundColor to layout option

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#3268]
```js
layout: {
  orientation: 'landscape',
  screenBackgroundColor: 'red'
}
```

**Comment by stefanc96** [comment]
If I want to open the app in the landscape mode and the phone it's locked to portrait the screen flips from landscape to portrait for 2 seconds at the transition between splash screen and the screen that i want to show .My guess it is that because the OrientationDefault from Orientation class is set to unspecified

**Comment by AyushAppin** [comment]
> [Android only] If I want to open the app in the landscape mode and the phone it's locked to portrait the screen flips from landscape to portrait for 2 seconds at the transition between splash screen and the screen that i want to show .My guess it is that because the OrientationDefault from Orientation class is set to unspecified

I am facing the same issue any fix for that?
