### ISSUE TITLE
[iOS] RCTWebSocket issue

### ISSUE THREAD

**Issue by tylerclark** [wix/react-native-navigation#335]
### Issue Description

Having trouble getting the iOS version working

### Steps to Reproduce / Code Snippets / Screenshots

1. Ran `rninit init test4 --source react-native@0.32.1` to get RN 0.32.1
2. Ran `npm install react-native-navigation@next --save`
3. Ran iOS instructions to add `ReactNativeNavigation.xcodeproj` to project and then modified `AppDelegate.m` according to document
4. Tried to Run the project but the build failed with the following:

```
RCTWebSocket
/Users/username/test4/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: Ignoring return value of function declared with warn_unused_result attribute
/Users/username/test4/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1334:5: Ignoring return value of function declared with warn_unused_result attribute
```

---
### Environment
* React Native Navigation version: 2.0.0-experimental.126
* React Native version: 0.32.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Build failed

**Comment by artald** [comment]
There's an issue with RN and Xcode8. It is fixed in RN33, but it might take some time until we upgrade.

**To solve it:**
Open Xcode, go to `RCTWebSocket.xcodeproj` (under Libraries in Xcode project navigator) -> Build Settings -> search for `-Werror` (it’s specified under "other warning flags") and remove it from the flags list.
Note that you will need to do this each time after a clean npm install.
