### ISSUE TITLE
[V2] Navigation.push is crashing my application

### ISSUE THREAD

**Issue by TylerNRobertson** [wix/react-native-navigation#3408]
### Issue Description
My project uses React Native Navigation V2 and whenever I setRoot with a stack and then try to push to it, the application crashes with an error of 'NSInvalidArgumentException'.

Exact Error: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

### Steps to Reproduce / Code Snippets / Screenshots
This is how i set my root.
<img width="453" alt="screen shot 2018-06-21 at 10 30 42 am" src="https://user-images.githubusercontent.com/23481122/41722220-36e08c5a-753e-11e8-9aa4-3ea2c15362fc.png">

This is how I am calling push.
<img width="490" alt="screen shot 2018-06-21 at 10 30 57 am" src="https://user-images.githubusercontent.com/23481122/41723328-30244016-7541-11e8-91dd-43fa3555136a.png">

This is how im registering my component:
<img width="903" alt="screen shot 2018-06-21 at 11 08 50 am" src="https://user-images.githubusercontent.com/23481122/41724236-81b6b326-7543-11e8-937c-dfb83a180d43.png">

This is my redux wrapper due to the new way of implementing redux in V2:
<img width="1079" alt="screen shot 2018-06-21 at 11 08 28 am" src="https://user-images.githubusercontent.com/23481122/41724209-7350d096-7543-11e8-912f-60709afed862.png">

---
### Environment
* React Native Navigation version: 2.0.2367
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Iphone 8 Simulator, IOS 11.3, Debug Version

**Comment by TylerNRobertson** [comment]
Managed to solve this issue by Making sure i have Navigation.events().registerAppLaunchedListener(() => { }) Listener fire before set Root.

**Comment by mcampsall** [comment]
@TylerNRobertson, can you share your code for the solution? I think i might have the same issue...

**Comment by TylerNRobertson** [comment]
@mcampsall I would recommend not looking at this issue. It is about an out of date/older version of RNN V2. I definitely have spent lots of time with this library though and probably could help out if I saw your code thats causing issues?
RNN Version?
RN Version?

**Comment by hadeel36** [comment]
@TylerNRobertson 
I got the same problem with RNN and I try to re-install several versions (2.2.0 /2.2.1 / 2.2.2 / 2.2.3 /2.2.4 / 2.2.5 ) but this not working too, in addition to node_modules error in tsconfig.ts  "can't find type definition file for 'jest'"
![screen shot 2018-12-18 at 16 48 30](https://user-images.githubusercontent.com/18619013/50181097-25ce0a00-0314-11e9-90e3-7c6287a7e50b.png)

Also when I try to Navigation.push I the simulator is freeze and this error is printed out " Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:"
![screen shot 2018-12-18 at 22 33 22](https://user-images.githubusercontent.com/18619013/50181406-f8ce2700-0314-11e9-82fc-b8fd83c7745b.png)

###This is my code
@index.js
![screen shot 2018-12-18 at 22 29 49](https://user-images.githubusercontent.com/18619013/50181219-76456780-0314-11e9-9526-43f0dac780a8.png)
@calling navigation 
![screen shot 2018-12-18 at 22 30 56](https://user-images.githubusercontent.com/18619013/50181282-9c6b0780-0314-11e9-91d3-fa76c8ba2dd8.png)
@the next page
![screen shot 2018-12-18 at 22 31 39](https://user-images.githubusercontent.com/18619013/50181326-b60c4f00-0314-11e9-9d0d-857b60865f33.png)

###I check the code hundred time and read the docs and search it GitHub issues but nothing work

Thank you in advance :)

**Comment by hadeel36** [comment]
I just found that the componentId is undefined so I pass it an a string
And it work
![screen shot 2018-12-19 at 10 41 01](https://user-images.githubusercontent.com/18619013/50209136-b12eb600-037b-11e9-9e5f-2c17990df092.png)

**Comment by MakhouT** [comment]
@hadeel36 That worked for me. The props are indeed not being passed which results in componentId being undefined.
