### ISSUE TITLE
v2-docs: Bump support dependencies to 26.1.0 to support RN 0.56

### ISSUE THREAD

**Issue by ujwal-setlur** [wix/react-native-navigation#3414]
### Issue Description

A recent checkin went in to add support for RN 0.56. This broke RN < 0.56 on android, but it can be fixed with documentation.
### Steps to Reproduce / Code Snippets / Screenshots

install latest v2 with npm
use react-native < 0.56, say 0.55.4

Build android. It fails.

Solution:

- use ```compileSdkVersion 26``` in android/app/build.gradle
- use ```implementation "com.android.support:appcompat-v7:26.1.0"``` in android/app/build.gradle
- use  ```buildToolsVersion "26.0.1"``` or above in android/app/build.gradle

---
### Environment
* React Native Navigation version: 0.55.4
* React Native version: FILL 2.0.2373
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by ujwal-setlur** [comment]
Might be related to #3412

**Comment by ilovett** [comment]
I was also not able to get v2 running on android following the v2 install instructions... I would get the error:

```
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:appcompat-v7' has different version for the compile (25.4.0) and runtime (26.1.0) classpath. You should manually set the same version via DependencyResolution
```

Following the above instructions at least let me compile further, but then I ran into this issue:
```
project/native/android/app/src/main/java/com/flexilarmapp/MainApplication.java:47: error: method does not override or implement a method from a supertype
  @Override
  ^
1 error
```

Turns out that if I removed the following override

```
  @Override
  public String getJSMainModuleName() {
    return "index";
  }
```

The application would launch but then I would receive errors that the app is looking for `index.android.js` which I had not created...

I'm fairly new to this but it's my understanding that the change to `index.js` for both ios and android was fairly recent?
