### ISSUE TITLE
Root component for implementing listeners?

### ISSUE THREAD

**Issue by avishayil** [wix/react-native-navigation#343]
Hi there,
I started experimenting with this library and everything is great - except I was wondering where should I put listeners where I can listen to from the whole app (Like in a root component / container).
For example, I want to know whether a firebase child node had been updated.
So yes, I could put the listeners on one of the screens registered for my tabbasedapp, but then I'll register the same listeners over and over when i'll navigate back to those screens, and i'll lose them when i'll navigate outside those screens.
What would be the best practice for that?

**Comment by guyca** [comment]
Hey @avishayil 
Tab screens don't get unmounted/destroyed when you navigate to other tabs. Infact, they don't get unmounted even when you push a screen into a tab or show a modal. So if you register a receiver in a screens constructor, it will be called once since it's created only once.
Screens get unmounted when they are popped, or when a modal is dismissed.

That being said, your project probably contains a class that's instantiated from both `index.android.js` and `index.ios.js`:
```js
import App from './src/app';
const app = new App();
```

In your `App`'s constructor, or even statically, you can register and instantiate listeners and dispatch actions accordingly.

**Comment by avishayil** [comment]
Thanks!

**Comment by Colmea** [comment]
Question: how do you call setOnNavigatorEvent in this app class without a this.props.navigator (since we're not in a React component) ?
Is there a static function to set a listener ?

**Comment by guyca** [comment]
You don't.  `onNavigatorEvent` should be implemented in your screens. If you want to handle these events in a centralized place, you can dispatch actions from your screens.

**Comment by Colmea** [comment]
@guyca Ok, then I don't understand your previous example which doesn't seem to work since App() is not a React component.

Regarding events in screens: the problem is that when an screen is not yet loaded (I mean "has not been displayed once"), the onNavigatorEvent is not triggered (because the Screen React class is not loaded yet).

So what's the solution if I can't handle onNavigatorEvent in a root component (there's no way with react-native-navigation to add a React root component as a screen), and screens has to be displayed once to set listeners ?

**Comment by sahil5695** [comment]
So is it ok to not call removeEventListener?
