### ISSUE TITLE
Sidemenu Deeplink not working

### ISSUE THREAD

**Issue by ant-camp** [wix/react-native-navigation#345]
I have a sidebar and im clicking on the side menu link to go to the HomeView screen and the sidemenu closes but it doesn't redirect to the next screen. Anyone ran into this issue?

    <TouchableOpacity style={styles.drawerButtonStyle}
                          onPress={this.onReplaceTabHome }>
    <View style={styles.menuLinks}>
    <Icon
        style={{width:20, height:20, marginRight:3, marginTop:1, backgroundColor:"transparent" }}
        name='fontawesome|home'
        size={17}
        color={"white"}
    >
    </Icon>

          <View style={styles.btnTxtSpacing}></View>
            <Text style={[styles.drawerButtonStyleText]}>
                Home
            </Text>
      </View>
        </TouchableOpacity>

  onReplaceTabHome() {
    this.props.navigator.toggleDrawer({
      to: 'closed',
      side: 'left',
      animated: true
    });

    this.props.navigator.handleDeepLink({
      link: "App.HomeView"
    });
  },

---
### Environment
* React Native Navigation version: "^1.0.30"
* React Native version:"^0.25.1"
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/ IPhone 6 - 10

**Comment by guyca** [comment]
Hey @ant-camp 
It's possible deeplinks are broken on `v1.030`. We stopped supporting `v1.0.30` and are now working on v2.
The [docs](https://github.com/wix/react-native-navigation/wiki/Installation---Android) contain upgrade and migration instructions if you want to migrate to v2.

I'm closing the issue, since v1.0.30 is not maintained. I encourage you to use the `next` version, feel free to post here if you encounter any issues migrating your project.
