### ISSUE TITLE
Navigation.startTabBasedApp, tabs -> selectedIcon not works 

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#354]
### Issue Description

Im using Navigation.startTabBasedApp,  I have three tabs, with icon and selected icon

 icon: require('../img/two.png'),
 selectedIcon: require('../img/two_selected.png'),

The selected Icon never applied, It's always the "icon", only the color changed because I have set tabBarSelectedButtonColor.

Another Issue I have, the tabBarSelectedButtonColor not working on release build, When I do select tab another tab color get changed, and some time the text color changed for a tab and the icon color for another tab at the same time

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 2 Exp
* React Native version: 0.25
* Platform(s) (iOS, Android, or both?): Testing on Android
* Device info (Simulator/Device? OS version? Debug/Release?): LG G3 OS 5.0

**Comment by guyca** [comment]
Hey @Jaafar-abusair 
`selectedIcon` is an iOS only property, sorry about the confusion. When a BottomTab is selected on Android, according to the [design guidelines](https://material.google.com/components/bottom-navigation.html#bottom-navigation-behavior), only the color changes.

On Android you can customise the BottomTabs theme in `appStyle`:
```js
Navigation.startSingleScreenApp({
  screen: {
    screen: '...',
    title: '...'
  },
  tabsStyle: {
    tabBarButtonColor: '#757575',
    tabBarSelectedButtonColor: '#00adf5'
  },
  appStyle: {
    tabBarButtonColor: '#757575', // BottomTabs unselected button color
    tabBarSelectedButtonColor: '#00adf5', // BottomTabs selected button color
  }
});
```

`appStyle` allows you to declare app wide styles in a single place but it's still not implemented on iOS, that's why we also use `tabStyle`.

**Comment by Jaafar-abusair** [comment]
Should I user Navigation.startSingleScreenApp with tabs inside the screen object or Navigation.startTabBasedApp?

**Comment by guyca** [comment]
You should use `startTabBasedApp` for consistency between iOS and Android. This will start a new app with `BottomTabs`.

in v2.0 we're going to support [TopTabs](https://material-design.storage.googleapis.com/publish/material_v_9/0B6Okdz75tqQsOUdyb0FjQTJTdlk/components_tabs_usage_mobile3.png) which you will be able to add to each screen (`BottomTab`). For now it's only available on Android but will be implemented on iOS in the upcoming weeks.

You can add `TopTabs` to a screen like this:

```js
    topTabs: [
      {
        screenId: 'example.FirstTabScreen',
        title: 'Tab1'
      },
      {
        screenId: 'example.PushedScreen',
        title: 'Tab2'
      },
      {
        screenId: 'example.ListScreen',
        title: 'Tab3'
      }
    ]
```

This isn't mentioned in the documentation since the api will change when we implement it on iOS.
