### ISSUE TITLE
[V2] TopBar tabs

### ISSUE THREAD

**Issue by jarrx** [wix/react-native-navigation#3544]
Is segmented controls implemented for topBar in iOS?
I think I've read that that was planned but I cannot find any docs about it.

**Comment by birkir** [comment]
```jsx
class TopBarSegment extends React.Component {
  render() {
    return (
      <SegmentedControlIOS value={['Tab 1', 'Tab 2']} />
    );
  }
}

Navigation.registerComponent('TopBarSegment', () => TopBarSegment);
```

```js
{
  topBar: {
    component: {
      name: 'TopBarSegment',
    },
  },
}
```

**Comment by jarrx** [comment]
How could I get the segmented control component to get aligned below the regular top bar title and buttons?
I want something like 
![hacking-uinavigationbar_image_1](https://user-images.githubusercontent.com/31743687/42832140-97a09de8-89f0-11e8-9f56-3233cd6088e7.png)

**Comment by birkir** [comment]
You can't change the height of an Navigation Bar

You can try to disable navbar border and include the Segmented Control in your Main view component with the same background color as the navbar, and then add the border to that component (rather than having it inside the navbar).

FIY, this navigation pattern is not recommended by Apple.

**Comment by jarrx** [comment]
Ah okey. Thank you for the help.
