### ISSUE TITLE
[v2] Elevation ignored on showModal

### ISSUE THREAD

**Issue by nenti** [wix/react-native-navigation#3582]
### Issue Description
On initial component of showModal elevation option is ignured

### Steps to Reproduce / Code Snippets / Screenshots

```js
static get options() {
    return {
      topBar: {
        elevation: 0,
        drawBehind: false,
      },
    }
  }
```

```js
Navigation.setDefaultOptions({
    topBar: {
      visible: false,
      drawBehind: true,
      elevation: 0,  <--- this is ignored aswell
    },
})
```

Component topbar will have default elevation and drop shaddow

---
### Environment
* React Native Navigation version: 2.0.2399
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung S7

**Comment by mths0x5f** [comment]
I'm having a issue with TopBar elevation being ignored too. Perhaps cause is the same.

I have defined my root as 4 bottomTabs with a stack each. The TopBar get stylized as defined and expected in `Navigation.setDefaultOptions()` or `static get options()` for every stack screen, but not the *TopBar elevation* in the first tab.

Strangely enough, the TopBar in the first tab get my custom elevation if I change to another tab and go back.

**Comment by mths0x5f** [comment]
This issue is getting me crazy!!! Only 2 things I discovered is that the customized elevation value appears briefly before being set to default (actually you can see with attention to the GIF above) and that if I delay `Navigation.mergeOptions()` execution for few hundred miliseconds within `componentDidMount`, the customized elevation is applied without user intervention.

**Comment by mths0x5f** [comment]
I have discovered the cause of the issue observed by me, reading the SDK code for AppBarLayout. 

When no theme is provided, AppBarLayout styles itself programmatically. What happens is that because these tasks are done asynchronously based on events, its call for "setElevation" equivalent can run after RNN calls!

@nenti, Can you confirm that your issue is like mine? Can you try the "solution"?

**Comment by guyca** [comment]
Hey @nenti 
I've merged the PR submitted by, @mths0x5f - can you please confirm it resolved the issue?

**Comment by nenti** [comment]
Elevation is fixed in latest #v2 branch. Thx @mths0x5f and @guyca
