### ISSUE TITLE
[v2] Overlay is showing above system dialogs like alerts

### ISSUE THREAD

**Issue by pie6k** [wix/react-native-navigation#3614]
### Issue Description

![image](https://user-images.githubusercontent.com/7311462/43097062-342bf742-8ebb-11e8-9e6d-c840ccf0baef.png)

### Steps to Reproduce / Code Snippets / Screenshots

1. Show any overlay element
2. Show any system dialog like `alert('Foo');`

Expected result:
Overlay is above everything excluding system UI

Actual result:
Overlay is above everything

### Note

Do you think adding some z-index to overlays and modals could be good idea too? In some cases you might want modal to be above overlay.

---
### Environment
* React Native Navigation version: 2.0.2425
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): every iOS device

**Comment by phuongwd** [comment]
@pie6k Do you have any solutions to resolve? Im facing the same issue when open url by Safari View.

**Comment by phuongwd** [comment]
@yogevbd 
This issue happened when open url by SafariView: react-native-safari-view
What do you think if we support set overlay hidden when open modal?

**Comment by bneigher** [comment]
@yogevbd 
Any way we can revisit this one?  The overlay elevation / z-index should not ever appear above a native OS / system prompt IMO.  I bet this is something that would even flag Apple reviewers since I know they can be sticklers on impeding iOS functionality.

A common use case that I've read about on the forums is using an overlay as a floating bottom menu (like the OP) and myself who has a custom bottom tab bar as an overlay.  Any time a keyboard opens, or the iOS debugger menu opens for example - the overlay takes preciseness and blocks the native menus.

<img width="426" alt="Screen Shot 2021-01-27 at 4 51 33 PM" src="https://user-images.githubusercontent.com/4627728/106073986-ea3fc580-60bf-11eb-8018-af4d8eeb966d.png">

Keyboard,
Alert,
Native Select,
React Native Debugger
React Native YellowBox / LogBox

These three System prompts are examples of prompts that can be blocked by a RNN overlay
