### ISSUE TITLE
Slow in Android

### ISSUE THREAD

**Issue by vivekparekh8** [wix/react-native-navigation#364]
### Slow in Moto G2

[On a Touchable Highlight click, One screen (ContentView + TopBar) is pushed on to stack ContentView has five view components including [PickerView](https://www.npmjs.com/package/react-native-picker) ]

### Pushing on to stack is slow in some low end devices

Tried commenting out every view and keeping <Text> but still the slowness persists for this device
Nexus 5x works really good
---
### Environment
* React Native Navigation version: experimental 116
* React Native version: 0.31
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device : Moto G2 Android 5.0.2 Debug, Oneplus one Android 5.1.1

**Comment by explorigin** [comment]
I noticed that things were pretty slow on my Galaxy S3 but then I updated to RN 32 and things are a lot better.  Although 0.32 isn't officially supported yet perhaps you can try that.

**Comment by vivekparekh8** [comment]
@explorigin Thanks for the quick response. I tried that but there is lag which is noticeable.
Also, Oneplus one - reproducing the same.

**Comment by guyca** [comment]
Well, react actually performs pretty bad on low end devices in debug mode. To confirm this you can disable `JS Dev Mode` in Dev Settings screen when running in debug or simply run your release build.

You should check if any views running none native animations or how busy your bridge is with `MessageQueue.spy` or [snoopy](https://github.com/jondot/rn-snoopy).

I'm closing the issue since I doubt this is related to RNN. Please reopen if you can confirm otherwise.

**Comment by vivekparekh8** [comment]
I already have [snoopy](https://github.com/jondot/rn-snoopy) in place for JS-N calls
It shows lots of UIManager.setChildren and UIManager.createView calls

**Comment by guyca** [comment]
Hey @vivekparekh8 Could be something is frequently changing your state and that causes views to rerender?
Don't forget that when you push a screen the previous screen is not unmounted, therefor it will react to state changes.

How's your release build performing?

**Comment by vivekparekh8** [comment]
Release build is comparatively faster.
