### ISSUE TITLE
Push a new screen from side menu?

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#37]
On SideMenu.js (Folder example) I tried change deepLink to push, but it don't working?
I have many categories on SideMenu and want when Press will push a new screen. How do create?
Thank you!

```
onReplaceTab2Press() {
     this.props.navigator.toggleDrawer({
       to: 'closed',
       side: 'left',
       animated: true
     });

    this.props.navigator.push({
      title: "More",
      screen: "example.PushedScreen"
    });
  }
```

**Comment by IlyasM** [comment]
+1

**Comment by divyekhanna** [comment]
+1

**Comment by guyca** [comment]
fixed in v2.0. [Deep links](https://github.com/wix/react-native-navigation#deep-links) are now working properly from side menu

**Comment by MeKarina** [comment]
i'm sorry,, is this issue really solved..??

have example on this..??

```js
onPress(title, md) {
  AsyncStorage.setItem('MD', md, () => {
    this.props.navigator.toggleDrawer({
      to: 'closed',
      side: 'left',
      animated: true
    });
    this.props.navigator.handleDeepLink({
      link: "tab2/example.StyledScreen"
    });
    this.props.navigator.push({
      title: title,
      screen: "example.StyledScreen"
    });
    console.log(md);
  });
}
```

i'm with 2.0.0-experimental.103 now..

thank You...

**Comment by guyca** [comment]
@MeKarina I' not aware of any issues with deep links. They work for us in production and in the example-redux project. Make sure the screen that needs to handle the deep link called 
'this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));'

**Comment by MeKarina** [comment]
ignore my previous comment... just my stupidity... works great..

**Comment by guyca** [comment]
It's ok, no harm done.

**Comment by tapdancemobile** [comment]
Hey, how do I pass a title along with a Deep Link? Do I have to make it part of the link? I tried adding a prop named title but it's not working.


` let item = Constants.MENU_ITEMS[index];
       this.props.navigator.handleDeepLink({
           link: 'root/switch/'+item.view,
           title: item.title
       });`

**Comment by guyca** [comment]
Yes, you need to add it in the deeplink.

**Comment by tapdancemobile** [comment]
Hey, so just to clarify - I need to pass in the title to my controller via the url rather than a prop?
ie. `this.props.navigator.handleDeepLink({ link: 'root/switch/'+item.view+'/'+item.title });`

instead of 
`this.props.navigator.handleDeepLink({ link: 'root/switch/'+item.view, title: item.title });`

**Comment by guyca** [comment]
Yes. You define the deep link scheme and handle it as you see fit.

@DanielZlotin We should rethink this API in one of the next versions. Instead of passing a string and having to parse it we should simply pass a JSON. And while we're at it, maybe handle it in a separate method to get rid of the `event.type switch-case` in `onNavigatorEvent`
