### ISSUE TITLE
ResetTo in the Drawer

### ISSUE THREAD

**Issue by alexcurtis** [wix/react-native-navigation#374]
### Issue Description

If I try to call resetTo using the`props.navigator` in the drawer, nothing seems to happen.
I am using this as a sign out link within the drawer to reset to the login screen.

### Environment
* React Native Navigation version: 2.0.0-experimental.127
* React Native version: 0.31
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Hey @alexcurtis I'm not sure I understood your use case. You're trying to change the `SideMenu` when the user logs out to display a login screen in the SideMenu?

**Comment by alexcurtis** [comment]
@guyca I'd like to reset the main scene (not drawer). At the moment I'm calling `startSingleScreenApp` again on logout - but the transition is not as nice as calling `resetTo`.

**Comment by guyca** [comment]
In our app, we call `startSingleScreenApp` in this use case but `resetTo` will also work.

In order to change screens from the SideMenu, you'd need to use [deepLinks](https://github.com/wix/react-native-navigation/wiki/Deep-links). Because you want to change your main screen, you need to call `resetTo` with you main screen's `navigator`. Similar to how screen is [pushed to a specific tab](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/SideMenu.js#L30) in the example project

**Comment by alexcurtis** [comment]
@guyca great. Thanks for the help. I'll close this issue now.
