### ISSUE TITLE
Switch to tab and refresh it?

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#396]
### Issue Description

Hey, I have problem with refresh event tab. How can i switch to a tab and refresh it when this tab active.

Thanks so much!
---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Hey @agumack I suggest your wait until screen lifecycle methods are implemented. Then, you'd be  receive `onDisplay` callback in your screens and do what ever you want there.

That being said, I don't think it's good practice to refresh data each time BottomTab is active. You can't predict your user's behaviour, they can navigate back and fourth between tabs and when on your mobile device some times you have low network conditions. That's why the recommended patters is pull to refresh. Let the user request data refresh.

**Comment by Jaafar-abusair** [comment]
I agree with @guyca , I have pull to refresh on the list which is better, but in one case when user add item then I send him back to the list I do refreshing the data using redux dispatcher, and the page will automatically refresh

**Comment by agumack** [comment]
Thanks @guyca , @Jaafar-abusair 
i don't using redux :( 
i am found a solution for callback event and receive to refesh list, too
