### ISSUE TITLE
[v2] SideMenu takes a full width

### ISSUE THREAD

**Issue by baldarian** [wix/react-native-navigation#3977]
### Issue Description

The SideMenu content takes the full width of the screen. Because of this issue I can't center items horizontally. 

https://ibb.co/fKGOZz

---
### Environment
* React Native Navigation version: 0.56
* React Native version: 2.0.2515
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / iOS / Debug

**Comment by rgoldiez** [comment]
@baldarian - Can you post some code?  I'm not seeing this issue.

**Comment by Hesowcharov** [comment]
I have same issue too but on ios. As temp fix you might set width for side menu component as 280 because it is default value for drawer width https://github.com/wix/react-native-navigation/blob/9d4eea835ad83170c39c336c108ef2610c078f19/ios/RCCDrawerController/MMDrawerController/MMDrawerController.m#L27
