### ISSUE TITLE
[wix] All these reverts on v2

### ISSUE THREAD

**Issue by birkir** [wix/react-native-navigation#3998]
Hey wix team.

I've noticed that the project is moving way more slowly than usual because most of the PR's that lands on v2 gets reverted.

It's super hard to keep track of what's in, why it didn't, or whats up generally.

I know that the Wix app is dependent on this project, but can't you guys figure out a solution to not block react-native-navigation if there is a problem that arises, with versioning or something else.

I don't want to be the bad guy or anything, I just care about the community around this project, it is the only active native navigation project alife and I would hate for it to go down the sink because of something like this

Thanks!

**Comment by henrikra** [comment]
Yeah I agree because reverting should be pretty rare but feels like it is very common in `v2` branch nowadays 🤔

**Comment by guyca** [comment]
Hey @birkir 
Looking at the commit log, 2 issues were reverted.
1. A PR which introduced a bug with the back button
2. A series of commits which were not supposed to land on the v2 branch in the first place, and have been restored in a separate branch with a [pending PR](https://github.com/wix/react-native-navigation/pull/3979)

Perhaps the reason it seems things have slowed down in the month of september is because both @yogevbd and I are on vacation, as this is the holidays season here in Israel. We have about 8 work days scattered around the entire month.

After the holidays (early Octobre) we're going to merge v2 to master and change our release strategy to a more conventional one.
Each commit to master will publish a snapshot to npm, once every 2-3 weeks we'll release a stable version. Alongside this change we'll also integrate an automatic changelog system.

Hope I answered your concerns, In the future you can reach out to me directly on [Discord](https://discord.gg/DhkZjq2) 👍

**Comment by birkir** [comment]
@guyca this answer my question well

My intention was not to ruin anyone's vacation, hope you and your family and friends had a great vacation.

I hope you and your team didn't take this the wrong way. I think this is mostly about more transparency towards contributors.

I didn't know about Discord. I'll use that platform for sure!

Thanks
