### ISSUE TITLE
[v2] bindComponent expects a component with a componentId in props, Jest Test

### ISSUE THREAD

**Issue by angelos3lex** [wix/react-native-navigation#4024]
### Issue Description

[Can't create unit tests with jest in components that are registered in Navigation]

### Steps to Reproduce / Code Snippets / Screenshots

I have a view called MyView, which is registered in Navigation screens. Inside this view, i vae a function called functionName which i want to test like shown below:
```
it("check MyView functionName", () => {
    let MyViewInstance = renderer
      .create(<MyView />)
      .getInstance();
    expect(MyViewInstance.functionName(2)).toEqual(4);
  });
```

When i run yarn test, is face the following error:
_bindComponent expects a component with a componentId in props_

in:  _Navigation.events().bindComponent(this);_

I somehow need to pass props in MyView like so: (<MyView  {...props}/>.
I tried using 
```
jest.mock('path/to/MyView', () => {
  const mockComponent = require('react-native/jest/mockComponent');
  return mockComponent('path/to/MyView');
});
```
before it(...), but i face the error: 
```
ReferenceError: props is not defined
```
So, is there any way to test a registered view using jest test?
### Environment
* React Native Navigation version: v2
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by acollazomayer** [comment]
@angelos3lex did you manage to solve this?

**Comment by JimTeva** [comment]
@acollazomayer I did have a similar issue
The problem was that the component X where I was trying to set a navigation listener was not called by navigation so it didn't have a componentId.
To solve this, I needed to include the parent componentId as a prop to the component X.
<ComponentX componentId={this.props.componentId} /> (as long as the parent component has a componentId set by navigation)
