### ISSUE TITLE
[V2]Unable to remove a screen from a Stack

### ISSUE THREAD

**Issue by ArunKulasegaran** [wix/react-native-navigation#4029]
###Problem Statement

In screen navigation like A -> B -> C -> D, I need to remove the screen C from the stack so that during pop gesture it will directly go to B from D since C can be ignored during backward flow.

Please do the needful changes or let me know if this can be done with existing code.

**Comment by guyca** [comment]
https://wix.github.io/react-native-navigation/v2/#/docs/screen-api?id=poptocomponentid-mergeoptions

**Comment by ArunKulasegaran** [comment]
Hi guyca,
Pop to component ID wont work if we want to use swipe gesture in iOS.
I want to remove the screen from the stack to make it work for pop gesture also.

**Comment by dcalhoun** [comment]
@guyca I agree with @ArunKulasegaran that your provided reference to [`popTo`](https://wix.github.io/react-native-navigation/#/docs/screen-api?id=poptocomponentid-mergeoptions) is not capable of accomplishing this task. We need a way to remove a screen from the stack prior to a user attempting to navigate backwards with a gesture (e.g. swiping from the left edge of the screen on iOS).

**Is there a way to proactively remove a screen from the stack?** If not, can we reopen this issue as a valid feature request please?

**Comment by guyca** [comment]
Hey @dcalhoun, RNN doesn't support this use case and as of now, we have no plans on supporting such api. We used to support this behaviour on Android, but since it's [not available on iOS](https://developer.apple.com/documentation/uikit/uinavigationcontroller) we removed it from Android as well.

This is not part of **any** stack api. I think the solution here might be to use a modal when you need to branch out and dismiss (pop) to a specific screen.
