### ISSUE TITLE
Does this project break the once source of truth rule?

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#414]
Perhaps I misunderstood something but I think I read that some state has to be kept under the native part of the code if someone uses this library.

Is this true and to what extent?

Thank you.

**Comment by DanielZlotin** [comment]
That's a great question.

You are correct to observe that when allowing the native side to keep state, and not be a direct function of the JS side state, this breaks one of the major contracts of declarative programming and React in general.

But, that's one of the main caveats of actually having truly native navigation. We decided (by investing in this framework) that not having truly native navigation, ie, the skeletal structure of the app, a deal breaker in terms of user experience.

So we allow some state to be "leaked" and managed by the native OS, even though this sometimes means it breaks the contract. Unfortunately this is unavoidable because the native OS is an imperative environment by definition.

So react-native-navigation's role is to "bridge this gap".
This means we need to be extra clever, and allow for a flexible enough API that will allow you to do things from JS that will play well with current declarative concepts.
We are not at this point yet though, thus, the experimental nature of current version.
By 2.0.0 the JS API will be stable enough.

**Comment by DanielZlotin** [comment]
It is possible, in the future, to create a wrapper around navigation which will allow you to control everything declaratively (maybe even using JSX) and it will interpret the commands and the "deltas" and make the appropriate imperative calls. This is not in the current scope though.
