### ISSUE TITLE
Android Splash screen

### ISSUE THREAD

**Issue by sexykodo** [wix/react-native-navigation#415]
Hi,
i'm trying to find the proper way to set a splash screen for Android using react-native-navigation.

On my Manifest I set a default theme for my Mainactivity

```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
          android:theme="@style/SplashTheme"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
```

In values/styles i config my style

```
 <style name="SplashTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@drawable/splash_bg</item>
    </style>

```

As i launch my app, the splash is shown correctly, BUT I see a white screen between the splash and the activity layout.
Did I miss something?

RN 0.35
RNN 2.0.0-experimental.136
Android

**Comment by MattDavies** [comment]
I've done mine by overriding `getSplashLayout` in SplashActivity, e.g.

```
public class MainActivity extends SplashActivity {
    @Override
    public int getSplashLayout() {
        return R.layout.splash;
    }
}
```

I've also got a fade in/out animation defined which hides the odd flicker.

**Comment by guyca** [comment]
@MattDavies's answer should do the trick. Thanks 👍

**Comment by sexykodo** [comment]
@MattDavies @guyca  ok, that does the trick but i still see a white screen before and after the splash (for a shorter time now)

**Comment by MattDavies** [comment]
Default view colour is white so you need to override that. Pick a colour that matches your app background, add a fade and it becomes unnoticable to the user.

    <style name="AppTheme" parent="Theme.AppCompat.NoActionBar">
            <item name="android:windowBackground">@color/gsblue</item>
    </style>

**Comment by sexykodo** [comment]
@MattDavies works great! how can I add a fade? can you please give me some further info? Thanks so much!

**Comment by MattDavies** [comment]
I'll dig up my code for that tomorrow, ping me if I forget :)

**Comment by Crash--** [comment]
@MattDavies ping :-°

**Comment by MattDavies** [comment]
Hey @sexykodo @Crash-- 

I had a look, turns out I had to do this in a fork to get a splash fade working:

https://github.com/MattDavies/react-native-navigation/commit/2cc4f10eda274368561cb67093ebb747d2f62553

`fade_in.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<alpha xmlns:android="http://schemas.android.com/apk/res/android"
    android:interpolator="@android:anim/accelerate_interpolator"
    android:fromAlpha="0.0" android:toAlpha="1.0"
    android:duration="750" />
```

`fade_out.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<alpha xmlns:android="http://schemas.android.com/apk/res/android"
    android:interpolator="@android:anim/accelerate_interpolator"
    android:fromAlpha="1.0" android:toAlpha="0.0"
    android:fillAfter="true"
    android:duration="750" />
```

Doing what I did actually sets the animation for whenever `NavigationActivity` gets started, i.e. I wanted the transition when I call `Navigation.startXApp` again (looks good for my login/logout process and hides any flickers as discussed above).

I've been thinking about this today and I really have no idea what a solid hook point might be to do this properly. There is some code for disabling animations a bit further down in `NavigationActivity`'s `onCreate()` which I was thinking of adjusting, but I found when I waited until after after `super.onCreate()` before overriding the transition it didn't use my animation for the splash screen.

@guyca or others if you have any brainwaves on how to do this in a nice way I'm happy to put a PR up.

**Comment by guyca** [comment]
@MattDavies 
NavigationActivity supports [disabling](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java#L64) activity animations. I think we can set the desired activity animation there. Instead of only clearing the animation, call `setActivityAnimation` instead etc.
The fade animation should be defined as `animationType: fade` when calling `startApp`

**Comment by MattDavies** [comment]
@guyca I did see that. For some reason when I set the activity animation there, it didn't fade out the splash screen properly. When I set it before the call to super.onCreate() it did.

**Comment by florianbepunkt** [comment]
@MattDavies Can you give an exmple of a simple splashscreen layout? I'm new to android..

In my MainActivity I override `getSplashLayout` like this

```
public class MainActivity extends SplashActivity {
	@Override
    public int getSplashLayout() {
        return R.layout.splash;
    }
}
```

in /android/app/src/main/res/layout/splash.xml I have this

```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:drawable="@android:color/white"/>
    <item>
        <bitmap
            android:gravity="center"
            android:src="@mipmap/ic_launcher"/>
    </item>
</layer-list>

```
My app builds, but when it crashed when opening saying "Unfortunately, MyApp has stopped"

**Comment by MattDavies** [comment]
Layout file looks OK at first glance. What's the crash error/stacktrace?

**Comment by florianbepunkt** [comment]
Can't say… changed my layout to just use an image and that worked

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/background">
</LinearLayout>
```
