### ISSUE TITLE
[v2] [iOS] Cant dismissModal which was opened in previous navigator.

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#4173]
### Issue Description

If I launch modal using **showModal** in first navigator(_for example Login_ ) and then launch other navigator  (_for example main navigator bottom tabs_) modal will be visible and you could not close it. Even with **dismissAllModals**.

This bug is only on iOS

### Steps to Reproduce / Code Snippets / Screenshots

```
const Login = () => {
  Navigation.setRoot({ ....
      });
};

Navigation.showModal()....

const MainNavigator = () => {
  Navigation.setRoot({ ....
      });
};

Navigation.dismissModal( _stored component Id_ ) - ( Component is not a modal )
Navigation.dismissAllModals() - ( Component not found )

```
---
### Environment
* React Native Navigation version: 2.0.2602
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by ItsNoHax** [comment]
Yeah seeing a lot of weird behaviour with iOS recently. I can't dismiss an overlay anymore.

**Comment by yogevbd** [comment]
@rendomnet A modal must be attached to some other screen by design, therefor when you reset your root layout using `setRoot` the screen which the modal was attached to is no longer there. That's why we dismiss all modals when `setRoot` gets called. I think you should use overlays in this case. New window is created for each overlay presented, it's detached from the app `rootViewController`, therefor `setRoot` will not destroy it.

@ItsNoHax Fixed your issue here: https://github.com/wix/react-native-navigation/pull/4204

**Comment by rendomnet** [comment]
@yogevbd But in my example modal is not dismissed when new setRoot is launched **IT IS STILL VISIBLE** and  becomes undisimissable.
