### ISSUE TITLE
[V2]Immersive mode

### ISSUE THREAD

**Issue by stefanc96** [wix/react-native-navigation#4258]
### Issue Description

I am trying to enter immersive mode when app starts but the screen won't redraw over the part where the navigation bar dissapeared

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?):Android
* Device info (Simulator/Device? OS version? Debug/Release?): Google Pixel 2

**Comment by ItsNoHax** [comment]
How are you trying to enter immersive mode?

**Comment by ItsNoHax** [comment]
Are you using drawBehind: true property on the topBar when you enter immersive mode?

**Comment by guyca** [comment]
I'm actually experimenting with this now in [windowInsets](https://github.com/wix/react-native-navigation/tree/windowInsets) branch.

It includes a new options to modify the `navigationBar`
```js
navigationBar: {
  drawBehind: true | false,
  backgroundColor: String
}
```

The downside of this branch is that it in order to handle drawing under the status bar and the navigation bar - I had to handle all insets myself rendering `android:windowSoftInputMode="adjustResize"` useless. This means the system doesn't handle insets for you when the keyboard opens for example and instead RNN handles all insets.
I'm a bit hesitant to introduce this change as I'm not entirely sure what effects it will have.

**Comment by dreamhb** [comment]
```js
        topBar: {
          visible: false,
           height: 0,
           drawBehind: false
         },
         statusBar: {
           drawBehind: true,
           visible: true,
           style: 'dark',
           backgroundColor: 'transparent'
         }
```
it works!

**Comment by jfrolich** [comment]
> I'm actually experimenting with this now in [windowInsets](https://github.com/wix/react-native-navigation/tree/windowInsets) branch.
> 
> It includes a new options to modify the `navigationBar`
> 
> ```js
> navigationBar: {
>   drawBehind: true | false,
>   backgroundColor: String
> }
> ```
> 
> The downside of this branch is that it in order to handle drawing under the status bar and the navigation bar - I had to handle all insets myself rendering `android:windowSoftInputMode="adjustResize"` useless. This means the system doesn't handle insets for you when the keyboard opens for example and instead RNN handles all insets.
> I'm a bit hesitant to introduce this change as I'm not entirely sure what effects it will have.

Any plans to merge this into master (drawing behind the navigation bar?)

**Comment by guyca** [comment]
@jfrolich That branch was an unsuccessful experiment, but I do plan on supporting this feature in Q2 2020

**Comment by jp928** [comment]
@guyca Is same option can achieve immersive mode on v7+?

**Comment by guyca** [comment]
@yogevbd This issue should be added to the roadmap IMO

**Comment by swabbass** [comment]
Fixed in the mentioned PR, have a look for the recorded demo there, and here is one with `setRoot` at opening:

https://user-images.githubusercontent.com/7227793/142226975-b11d043d-0467-475e-8e74-214811cae7b4.mov

You can choose to show StatusBar and set backgroundColor that matches your taste and pass `translucent` and `drawBehind` as `true`.
