### ISSUE TITLE
[v2] passing Navigation.pop in passprops

### ISSUE THREAD

**Issue by ionush** [wix/react-native-navigation#4393]
### Issue Description

I wish to use Navigate.pop by passing it in passProps of Navigate.push. The reason for this is I only want the pop to run when it is passed through the push function. 

Like this:

### Steps to Reproduce / Code Snippets / Screenshots

               onPress={() => {
                  Navigation.push(this.props.componentId, {
                    component: {
                      name: 'App.ComponentName',
                      passProps: {
                        section: 'all',
                        expandedSearch: true,
                        extraCloseProps: () => Navigation.pop(this.props.componentId)
                      }
                    }
                  })
                }}

However, it breaks, and then I get all sorts of issues, namely, Error:popping component failed.

![image](https://user-images.githubusercontent.com/26359601/49505089-f64fe400-f8b5-11e8-8a63-881304ff2c9d.png)

---
### Environment
* React Native Navigation version: 2.0.2632
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): simulator iphone 6

**Comment by vshkl** [comment]
@ionush my guess is that this happens due to you are actually going to execute `pop` with the `componentId` of the screen you've pushed it from and not with the `componentId` of the screen you're actually going to `pop` from.

Like:
screen 1 -> componentId == id1
screen 2 -> componentId == id2

Here you are basically calling `push('id1',  ...)` and passing a `pop('id1')` with passProps. And when it comes to executing that `pop` function (you are actually at the screen with 'id2', not 'id1') it appears to have wrong screen id passed to it.

**Comment by ionush** [comment]
yup. Spot on. Thanks!
