### ISSUE TITLE
[v2] Show LightBox Equivalent 

### ISSUE THREAD

**Issue by RomualdPercereau** [wix/react-native-navigation#4629]
### Issue Description
There is actually no equivalent of showLightBox in v2
The new version introduce 2 features : showModal and showOverlay. 

## ShowModal 
This is supposed to push a new full screen controller, which works like Navigation.push

## ShowOverlay
There is no animation, no background management, interceptTouchOutside doesn't work as expected (https://github.com/wix/react-native-navigation/issues/4622) 

You can bullshit to have something like the previous showLightBox : https://github.com/wix/react-native-navigation/issues/4060. 

## Alternatives
The cleaner way to display a modal on v2 is probably the official way: https://facebook.github.io/react-native/docs/modal

## Any Plans ? 
Any plans to replace this feature with should be on the native side and done by the navigator?

### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Alls

**Comment by guyca** [comment]
Bullshitting as shown in #4060 seems like a great idea!
lightbox isn't implemented in v2 because it's not a native component and can be easily implemented (bullshit as you describe it) using Overlay.
Want to handle touch events outside of the actual lightbox? use `TouchableWithoutFeedback`, don't want to repeat yourself? open source your bullshit.

good luck and happy bullshitting.
