### ISSUE TITLE
[V2] componentDidAppear does not trigger until the animation has finished

### ISSUE THREAD

**Issue by SMJ93** [wix/react-native-navigation#4648]
### Issue Description

First of all, great work with this library guys, I'm really noticing the performance improvements compared to react-navigation 👍 

I am using react context to store the app theme (dark and light). I have got everything updating as you can see in this gif (thanks @guyca! - https://github.com/wix/react-native-navigation/commit/dd41d48c36c18aa8e68346b512dca25feaae112a)

![app](https://user-images.githubusercontent.com/2145641/51804936-d659f280-225e-11e9-8205-ccd12aa52921.gif)

In the gif you'll notice the header and status bar are dark with white content (updating straight away thanks to `Navigation.setDefaultOptions`), but the content is still white for about half a second (this is while the pop transition/animation takes place.

I am currently using `componentDidAppear` to trigger the re-render, but this is invoked after the animation has finished running - causing the half second delay. Is there a way force re-render the previous screen (the one i'm going to pop to) before it starts animating?

Maybe another lifecycle `beforeComponentAnimates`?

Another potential solution i've been looking into is disabling the `pop` animation for just that screen, but I can't get it to work:

```
Navigation.pop(componentId, {
      animations: {
        pop: {
          content: {
            alpha: {
              duration: 0,
              from: 0,
              to: 1
            }
          }
        }
      }
    })
```

### Environment
* React Native Navigation version: 2.7.1
* React Native version: npm:@brunolemos/react-native (so I can use react-hooks)
* Platform(s): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator debug

**Comment by guyca** [comment]
Hey @SMJ93 
Indeed, `componentDidAppear` event is emitted **after** the animation ends. In v1, we emitted two events when attaching components to hierarchy:
1. didAppear - emitted after animation ends
2. willAppear - emitted on animation start

We've done so exactly for this purpose - sometimes we need to act before animation starts. This worked well for the most part, but became completely unreliable when taking the bridge and js thread into account.

If the bridge or js thread are busy `willAppear` becomes meaningless as it will be handled after the component appeared, perhaps even after animation ended.
Since we can't guarantee the events will be emitted in the appropriate time, we had to drop it.
`didAppear` is reliable as it's emitted after animated completes, as the user expects.

Since components are mounted until popped, you can update your theme manager before calling `Navigation.pop` to trigger re-render before actually popping the component (aka before pop animation starts)

**Comment by SMJ93** [comment]
Thanks for the quick response @guyca!

I see, that makes sense regarding `didAppear` and `willAppear`.

I've tried updating the theme manager (global context) before popping, but unfortunately it still doesn't work :/

The context does not cause it to re-render (when popping) I need to sync the context from the `componentDidAppear` lifecycle event.

```
// home
 public componentDidAppear() {
    trackScreen(SCREEN_TRACKING_NAME)
    this.props.syncTheme()
  }

// global theme context
syncTheme = () =>  this.state.theme.themeType = this.state.theme.themeType
```

I'm happy to invite you to my private repo if you want to take a look?

**Comment by SMJ93** [comment]
@guyca Sadly I have not been able to find a solution to this :/

The only hacky way I have found is with `Navigation.setStackRoot(this.props.componentId, {` instead of `push` and `pop` but that removes the back button and the transition is incorrect.

Is there a way to remove the `Pop` animation for this screen only? I can't think of another way to get around this :/
