### ISSUE TITLE
registerCommandListener => pass passedProps

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#4716]
### Issue Description

It would be nice to have the passedProps available in registerCommandListener. For instance when globally sending screen events for analytics purposes.

**Comment by guyca** [comment]
This is indeed a great suggestion, We've noticed this as well. The issue is actually pretty simple to fix, perhaps someone would like to submit a PR.

Basically, passProps are omitted from commands and stored in internally. This is done since props are not guaranteed to be serialisable so they can't be passed over the bridge. Also, props might be pretty large, in which case passing them over the bridge hinders performance.

Once a component is mounted we inject props and clear them from store. We should continue omitting props from objects passed over the bridge, while still including them in command events.

**Comment by jfrolich** [comment]
OK let me see if I can add a pull request for this

**Comment by pribeh** [comment]
@jfrolich any luck with this?

**Comment by jfrolich** [comment]
Nope, wish I had the time, but we need this soon in our app, so I'll will have to look into this soon.

**Comment by jfrolich** [comment]
Just published a pull request for this!

**Comment by pribeh** [comment]
@jfrolich wicked! How would i use copiedLayoutNode then?

**Comment by jfrolich** [comment]
You don't need to use that, that just makes sure that passed props is not always null in the screen parameter of `registerCommandListener`.

**Comment by guyca** [comment]
Thanks to @yogevbd, passProps are now available in command events 👍

**Comment by Frenchford** [comment]
@guyca what about v7.1.0?
passProps are unavailable
