### ISSUE TITLE
[V2] topBar Button icon not show in iOS10 

### ISSUE THREAD

**Issue by trungthanhnt** [wix/react-native-navigation#4759]
### Issue Description
My topBar button icon is not shown on iOS 10.3.3 iPhone 5S. ( However In iPhone 7 12.x.x it works)
Please show me how to fix it. 
Thank you very much

### Steps to Reproduce / Code Snippets / Screenshots

static get options() {
    return {
      topBar: {
      
        title: {
          text: 'ChatScreen',

        },
   
        leftButtons: [
         
          {
            id: 'searchBttn',
            icon: require('../../resources/images/ic_search_blue.png'),
      
            text:'QR Chat',
           
            disableIconTint:true,
          },
          
        ],
        background: {
          color: '#fff'
        },
        noBorder: true,
        elevation: 0,
      }
    };
  }

### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS 10.3.3
* Device info (Simulator/Device? OS version? Debug/Release?): Device iPhone 5S Debug and Release

**Comment by varungupta85** [comment]
I am observing similar problem. This is a problem introduced after version `2.8.0` as the images appear fine in that version but don't show after I updated to `2.12.0`. This is of course not reproducible in an e2e test because they only run on the latest iOS on which the problem is not seen.

@guyca @yogevbd
