### ISSUE TITLE
all error screens point to index.ios - installation instructions

### ISSUE THREAD

**Issue by florianbepunkt** [wix/react-native-navigation#486]
in the installation instructions it reads that we should modify AppDelegate.m according to this example: https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m

Doing so results in all error messages pointing to `index.ios.bundle?platform=ios&dev=true`

Is this intentional?

**Comment by artald** [comment]
If you have an error in JS, it will surely point you to the bundle where all the JS code is bundled, so I don't think any errors of this kind are related to the changes necessary in `AppDelegate` native code. Anyway, it is not intentional and you're not supposed to get error screens.

What exactly does the error message say?
