### ISSUE TITLE
Install automatically with react-native link

### ISSUE THREAD

**Issue by hrahimi270** [wix/react-native-navigation#4943]
### Issue Description

install `react-native-navigation` with `react-native link react-native-navigation`.
Currently, we must config manually for Android and iOS both. It's a little hard and confusing.
It also increases the percentage of errors.
Similar packages can be installed with `react-native link`.
I think it's a good idea considering this.
Regards.

**Comment by retyui** [comment]
Yes, the first setting may seem complicated, I think this is due to the fact that many developers come to the field of mobile development from the web and do not understand much about this new platform.

At the moment, the documentation describes in sufficient detail each step.

and a few words about the automatic settings, there is no universal solution
