### ISSUE TITLE
Open Collective donation

### ISSUE THREAD

**Issue by alexchia** [wix/react-native-navigation#5079]
Hi, I made a donation to support the project on opencollective.
Would the core devs kindly collect at https://opencollective.com/react-native-navigation and spend as you see fit.

Keep up the amazing work, I found this package incredibly useful.

**Comment by guyca** [comment]
Hey!
Thanks a lot for the kind words ❤️We truly appreciate the gesture!
Since this project is backed by [Wix](https://www.wix.engineering/open-source) and developed as part of our day to day tasks here at Wix's mobile team, I don't feel comfortable accepting donations.

Once again,
Thanks, that means a lot ❤️
