### ISSUE TITLE
[v2] Android app relaunches when opened via deeplink.

### ISSUE THREAD

**Issue by acollazomayer** [wix/react-native-navigation#5105]
### Issue Description
The android app relaunches when its opened via a deep link. Does anyone knows why this might happen

---
### Environment
* React Native Navigation version: 2.18.4
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both Android 9 Both

**Comment by yuheidapperapps** [comment]
This issue should not close, it is still exists in 2.20.0.
When app launch from deep link, onDestroy in NavigatorActivity is called and navigator.destroy() destroy all the stacks and unable to retain previous state. This code still exists in master.

https://github.com/wix/react-native-navigation/pull/4740

I think this was fixed in v1 https://github.com/wix/react-native-navigation/pull/4740 but come up again in v2
