### ISSUE TITLE
setRoot navigation debug overflow memory

### ISSUE THREAD

**Issue by fatihmert** [wix/react-native-navigation#5205]
### Issue Description

I haven't tested the production date yet but, my application also has 4 main functions that include setRoot. Like this project; https://github.com/atoami/react-native-navigation-redux-starter-kit/blob/master/src/navigation/Navigation.js

The application closes instantly because the RAM is swollen. No bugs etc anything. I'm worried, My users do not encounter the same problem when I deploy my application. I think that's because more RAM is consumed in debug mode. Do you still recommend this (functional) use?

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2.18.3
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Venus GO _(I'm also speaking general for all devices, I've tried a lot of my friends' phones too)_

**Comment by piuholo** [comment]
I'm facing the same problem on some older Android phones, although the app will also close when using a release build.

**Comment by guyca** [comment]
Hey there,
This issue is probably not related to RNN. Are you displaying very large images?
If you believe this is related to RNN, please try and reproduce on the problematic devices with our playground app and provide more information.
I'm closing for now as I don't believe it's related to RNN, but will gladly reopen if needed.
