### ISSUE TITLE
why not support react-native link for android

### ISSUE THREAD

**Issue by charlesluo2014** [wix/react-native-navigation#521]
### Issue Description

when integrate this framework,it will appear a problem,when add a new native dependency ,react-native link command dose not take effect

### Steps to Reproduce / Code Snippets / Screenshots

react-native link

---
### Environment
* React Native Navigation version: all
* React Native version: all
* Platform(s) (iOS, Android, or both?):all
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by perrosnk** [comment]
Have you followed these instructions?
https://github.com/wix/react-native-navigation/wiki/Installation---iOS#installation---ios

**Comment by charlesluo2014** [comment]
@perrosnk thanks,but android is not support

**Comment by guyca** [comment]
@charlesluo2014 
This is indeed a painful issue which we have to address. A couple of times I had to integrate third party dependency that provided no explanations on how to integrate them other then "run npm link".
As a workaround I had to `react-native init` a dummy project, add those dependencies there, link and see the changes 👎 

As a developer, I didn't really relate the concept behind `npm link`. Instead of understanding how our frameworks work - we rely on some black magic that works only if our project is configured and structured exactly like Facebook's example project. And even then it some times fail.

**Comment by charlesluo2014** [comment]
@guyca react-native link or npm link help us much ,npm link or react-native link help us manage the dependency and modify the gradle file,and import the module in the Main class of getPackages().I think it is much better to promote RNN framework

**Comment by guyca** [comment]
Agreed. Hope we'll be able to prioritize this for one of the next releases.

**Comment by SudoPlz** [comment]
+1 to that..!

**Comment by Fenwil** [comment]
Guys we made this workaround to have compatibility with `react-native link` for Android platform.

```java
public class MainApplication extends NavigationApplication {
  @Override
  public boolean isDebug() {
      return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
          // eg. new SvgPackage(),
    );
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
      return this.getPackages();
  }
}
```

This has work for us since a time ago.

@guyca I will send you a PR, maybe it will be OK

**Comment by guyca** [comment]
@Fenwil Sure!

**Comment by pbassut** [comment]
+1 to this!

**Comment by leoi11** [comment]
[This](https://github.com/wix/react-native-navigation/pull/1245) seems to be the above discussed PR. Could you confirm, @lndgalante?
Does this mean the documentation is outdated and `react-native link` will now work?

**Comment by leoi11** [comment]
UPDATE: `react-native link` won't work even with the above PR. It added unnecessary lines for me and does not changes what MainApplication extends, and it doesn't update the compileSdkVersion (to 25) either. For anyone trying to install RNN, you should go for the manual steps instead.

**Comment by jmiller14** [comment]
The issue is that once the changes to `MainApplication.java` are made during the installation process, the lines that `react-native link` keys off of when adding new packages are no longer present.  In particular:
* `import` statements are added after `import com.facebook.react.ReactApplication;` (see [here](https://github.com/facebook/react-native/blob/master/local-cli/link/android/patches/makeImportPatch.js))
* new packages are added after `new MainReactPackage(),` (see [here](https://github.com/facebook/react-native/blob/master/local-cli/link/android/patches/makePackagePatch.js))

To get `react-native link` working correctly, just add a couple of comments with those bits in there.  Here's what my `MainApplication.java` ended up looking like:
```java
package com.[YOUR_APP_PACKAGE];

import android.support.annotation.Nullable;

import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;
// the following line is present so that `react-native link` works correctly
// import com.facebook.react.ReactApplication;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {
    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    @Nullable
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return Arrays.<ReactPackage>asList(
            // the following line is present so that `react-native link` works correctly
            // new MainReactPackage()
        );
    }

    @Nullable
    @Override
    public String getJSMainModuleName() {
        return "index";
    }
}
```

**Comment by mths0x5f** [comment]
> The issue is that once the changes to `MainApplication.java` are made during the installation process, the lines that `react-native link` keys off of when adding new packages are no longer present. In particular:
> 
> * `import` statements are added after `import com.facebook.react.ReactApplication;` (see [here](https://github.com/facebook/react-native/blob/master/local-cli/link/android/patches/makeImportPatch.js))
> * new packages are added after `new MainReactPackage(),` (see [here](https://github.com/facebook/react-native/blob/master/local-cli/link/android/patches/makePackagePatch.js))
> 

These bits of information by @jmiller14 should be in the documentation, as `react-native link package` still does not patch automagically the MainApplication.java file without the comments he mentioned about. It's really boring to not use 'react-native link' 100% capability out of box if this is simple as adding a comment to boilerplate.
