### ISSUE TITLE
[V2] componentWillUnmount not running on screen pop.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#5348]
### Issue Description

I'm pushing a screen like normal, with `Navigation.push`, and then pop it w/ `Navigation.pop`.
I noticed after the pop takes place, the animation runs, the screen is no longer visible, bot `componentWillUnmount` **doesn't** run.

As I investigated further I found out that `Navigation.pop` never returns anything, the promises that it's supposed to return NEVER resolves, or rejects.

I decided to dig further into the code and found out that [this](https://github.com/wix/react-native-navigation/blob/d09d0108d1530cf10e24c46efb6c9d9962807ead/lib/ios/RNNNavigationStackManager.m#L40:L44) never runs and that's because [this](https://github.com/wix/react-native-navigation/blob/d09d0108d1530cf10e24c46efb6c9d9962807ead/lib/ios/RNNNavigationStackManager.m#L87:L89) never runs.

Now I tried to reproduce that on the playground app but couldn't. Not sure why that's happening on my end.

GOOD NEWS though, I also found [this SO answer](https://stackoverflow.com/questions/27470130/catransaction-completion-block-never-fires)  and tried surrounding the animation block with a main thread block.

After that the issue was gone!!
[The completion block runs again](https://github.com/wix/react-native-navigation/blob/d09d0108d1530cf10e24c46efb6c9d9962807ead/lib/ios/RNNNavigationStackManager.m#L87:L89) and so does `componentWillUnmount` on every pop.

I still have no idea what's causing it, but here's how the new code looks like:

```
[self performAnimationBlock:^{
        poppedVC = [viewController.navigationController popViewControllerAnimated:animated];
}
```

is now:

```
[self performAnimationBlock:^{
        dispatch_async(dispatch_get_main_queue(), ^{
            poppedVC = [viewController.navigationController popViewControllerAnimated:animated];
        });
}
```
---
### Environment
* React Native Navigation version: 2.26.2
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPad Pro 12.9 Inch 3rd Generation iOS 12.4 Simulator

**Comment by SudoPlz** [comment]
@guyca this is the issue I've been telling you about ^, it doesn't reproduce on the playground app, but I'm pretty sure one of your iOS devs will have a better idea as to why that's happening.

**Comment by SudoPlz** [comment]
should I open a PR? Would you accept my code or is it too early to make assumptions?

**Comment by guyca** [comment]
@SudoPlz 
This is a real strange one. @yogevbd and I went over the code and we can't think of a reason why the completion block won't fire.

* I suggest you check if `performAnimationBlock` is called from the main thread. If somehow it isn't, that might explain what you're observing.
* Perhaps the completion block isn't fired because the ViewController is actually leaking. If you could dig into that and find a leak, that would help us find the "real" fix to this issue.

Please let me know if I can help more

**Comment by SudoPlz** [comment]
@guyca I have no idea how to test if the view controller is leaking :/ any hints?

**Comment by SudoPlz** [comment]
I'm out of ideas, spent the whole day looking for the issue, but couldn't track it down.

What I've learned though is that:

1) Things like any other animation taking place right after a pop happens i.e an `ActivityIndicator` running can [somehow mess things up](https://stackoverflow.com/a/27471702/1658268) <-- example.

2) [The completion block will not call if there is nothing to animate or the transition part already done by some another part of your source code](https://stackoverflow.com/a/37928557/1658268) and the code snippet runs on different thread

I'm wondering why did you implement this via a `UINavigationControllerDelegate` [like so](https://stackoverflow.com/a/48121217/1658268)?

**Comment by SudoPlz** [comment]
For now I've opened a PR to fix this. I don't what harm making sure animations run on main thread may bring.

**Comment by guyca** [comment]
@SudoPlz Sorry for not being responsive, was a bit busy with v3.
Seems like this change broke some unit tests, I don't mind merging this if ci passes 👍

**Comment by SudoPlz** [comment]
@guyca no worries, let me know if you need me to do anything

**Comment by SudoPlz** [comment]
@guyca looks like this is going to be closed :/

**Comment by Crysp** [comment]
i have same issue with navigation... after `pop` animation screen still exists. and sometimes i've got a error `Error: popping component failed` after `dismissOverlay` and trying to `pop` current screen

**Comment by tootsweet** [comment]
We have this problem as well.

**Comment by tootsweet** [comment]
This is not stale.

We have been able to circumvent this problem by avoiding any animations in our screens under iOS (we replaced loaders with animated GIFs), but it's obviously a bad solution.

Someone has to take a look a this and fix it in v3.

**Comment by phuongwd** [comment]
This is not stale.

**Comment by tiennv-0883** [comment]
i have same issue with navigation .after pop animation screen still exists. and sometimes i've got a error Error: popping component failed

**Comment by SudoPlz** [comment]
@guyca can you merge the above PR? It's hard to keep the issue from going stale.

**Comment by guyca** [comment]
@SudoPlz Seems like this is a bigger issue we need to look into. I closed your PR and we'll look into this asap.

**Comment by phuongwd** [comment]
Hi @guyca @yogevbd 

This issue still happening if the animation of Lottie component is runs.

**Comment by guyca** [comment]
@phuongwd Please create a separate issue and include a reproduction

**Comment by Caundy** [comment]
@guyca 
Any chance you'd try to reason about what else could cause this situation from a theoretical standpoint?

Ran into such an issue today when working with a paginated FlatList. The bug is super quirky and I'm not sure how pagination could be linked to Navigation.pop's promise not resolving but here is what I observed:

With only the first - of multiple - page of results loaded, opening and closing a details screen for one of the list elements would cause the promise returned by Navigation.pop **not to resolve** (and not to reject), it simply hangs.

While the promise hangs like this, some further actions **cause it to resolve**, such as: using RefreshControl, scrolling down (which causes another page of results to load) or opening the details screen once more (which pushes the screen into the stack) for the same list element or another one. 

With all the pages of results loaded in, opening and closing a details view for one of the list elements causes the Navigation.pop promise to resolve as expected.

I spotted the issue while using the 7.18.1 version of the library but it reproduces in 7.26.0, too.

Would be grateful for any input on the matter, cheers!
