### ISSUE TITLE
Navigation.events().bindComponent not working after setRoot for the second time

### ISSUE THREAD

**Issue by Komeyl94** [wix/react-native-navigation#5408]
### Issue Description

I've used setRoot when switching users in my app, but the problem is that after switching it seems that the navigation events doesn't bind again, so as a result non of the lifecycle methods (didAppear & didDisappear) works! 
Does anybody know what could be the problem?

---
### Environment
* React Native Navigation version: 2.22.3
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Tested only on Android
* Device info (Simulator/Device? OS version? Debug/Release?): Google Nexus 5X Android 7.1.0 Genymotion Emulator - Debug & Release

**Comment by phuhk** [comment]
Same here, because when you `setRoot`, `componentDidMount` of "new Component instance" call first, then `componentWillUnmount` of "old Component instance" trigger `unmounted` function of `ComponentEventsObserver` class (check code in react-native-navigation/events), which should remove all your listener.

Work around here, try to `setRoot` to some temp root screen, thanks for `setRoot` return Promise, so you can know `setRoot` complete, so you can set it to your real root screen

**Comment by Komeyl94** [comment]
@phuhk thanks a lot, your solution worked

**Comment by agestaun** [comment]
Same issue..
