### ISSUE TITLE
'React/RCTConvert.h' file not found RNNOptions.h

### ISSUE THREAD

**Issue by Reactongraph** [wix/react-native-navigation#5560]
Got this error after tried both manual and CocoaPods linking
got stucked here help please

Also here is screenshot for the issue
<img width="1250" alt="Screenshot 2019-10-09 at 5 59 07 PM" src="https://user-images.githubusercontent.com/37612566/66481594-dfbe7e80-eabe-11e9-8ca1-9abc44407ad5.png">

**Comment by davidmarinangeli** [comment]
Me too

**Comment by davidmarinangeli** [comment]
@Reactongraph have you found a fix in these 20 days?

**Comment by dmexs** [comment]
I believe this issue is related to a breaking change in the react-native code base as of v0.60.0:

https://github.com/react-native-community/releases/blob/master/CHANGELOG.md
https://github.com/facebook/react-native/commit/2321b3f

'React' can't be added as a build target to a scheme anymore because it doesn't exist. However I"m not sure how still achieve a valid reference to RCTConvert.h

Anybody have any thoughts?

RN 0.61.3
RNN 3.3.0

**Comment by dmexs** [comment]
With a clear head this morning I found that the mistake I made was trying to following the manual linking process as well as the Pod linking process.

After I undid the steps I followed in 1 and 2, RNN started building properly.
https://wix.github.io/react-native-navigation/#/docs/Installing
