### ISSUE TITLE
How to customize tabs and navigator color on ios/android

### ISSUE THREAD

**Issue by vedovato** [wix/react-native-navigation#557]
### Issue Description
- 1: Seems like i can't change icons tab bar color on Android. It works well on iOS and i can change tab background color, icon color and stuff. On Android it simply doesn't work and it renders pink as a default. There's a way to customize it?

- 2: There's a way to remove that navigator header inner shadow on Android? Looks like i can only change it's background color and font specs.

---
### Environment
* React Native Navigation version: ^2.0.0-experimental.152
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android issues
* Device info (Simulator/Device? OS version? Debug/Release?): Android API 23 and 24. MacOs 10.12.1

**Comment by guyca** [comment]
Hey @vedovato 
1. The [docs](https://github.com/wix/react-native-navigation/wiki/Styling-the-tab-bar) have a section about styling to BottomTabs.

2. Currently there's no way to remove the shadow. This has been requested previously, we can support it if it's needed. Why would you like to remove the shadow? Because you don't like it or you'd like to add a component to the `TopTab`?

**Comment by vedovato** [comment]
wow, @guyca! I didn't realize this **appStyle** which applies to Android so thank you! About second point, i prefer a solid color without inner-shadow in header. 

Also noticed that running the bootstrap project, thaat inner-shadow doesn't exists :O

**Comment by guyca** [comment]
IIRC TopBar doesn't have shadow in KitKat and bellow. Maybe you checked on an older device?
