### ISSUE TITLE
titleImage Android

### ISSUE THREAD

**Issue by AtixD** [wix/react-native-navigation#564]
How insert logo in title nav bar? (Android) titleImage with Android not working, but iOS working! Please help!

---
### Environment
* React Native Navigation version: 2.0.0-experimental.152
* React Native version: 0.39.1
* Platform(s) (iOS, Android, or both?): ANDROID
* Device info (Simulator/Device? OS version? Debug/Release?): 4.3 - 6.0

**Comment by desmondhume** [comment]
+1

**Comment by danieljvdm** [comment]
+1

**Comment by ericacooksey** [comment]
+1

**Comment by guyca** [comment]
Hey,
Setting an icon in the Toolbar is currently not supported. I'm not sure I understand the purpose of having an icon in the Toolbar that's not a button. It used to be common to have the application's icon in the toolbar but that's long ago.

Since pushed screens on Android should have a back button, and the title is aligned to the left of the screen, I'm not sure where another icon fits here. Between the back button and the title? to the right of the title? at the center of the Toolbar? This seems unnatural in an Android app.

I've rechecked the [material design guideline](https://material.io/guidelines/components/toolbars.html#) on this matter and didn't find references to icon in the toolbar.

Not every feature available in one platform will be available in the other platform. The reason for that is that this library tries to provide a real native experience for the users, so if a feature is doesn't exist in one platform, it's unlikely it will be added.

Hope I was able to answer your questions.

**Comment by ericacooksey** [comment]
@guyca setting a custom view is a feature for the action bar: https://developer.android.com/reference/android/support/v7/app/ActionBar.html#setCustomView(android.view.View) . From the doc: 
> Custom navigation views appear between the application icon and any action buttons and may use any space available there

Would it be possible to wrap this method in order to accept an image?

**Comment by guyca** [comment]
Yes, we will add support for custom react views in the toolbar. Thought it might be implemented only in the final v2 version and not the current experimental version.

**Comment by dhyegofernando** [comment]
👍

**Comment by raunaqss** [comment]
@guyca glad to read that custom view support will be added to v2. Any chance the same has been added to the v1 (current stable version)? I'm sure I saw an option allowing this in current version's docs..

**Comment by guyca** [comment]
@raunaqss 
You can use `navBarCustomView` and `navBarComponentAlignment`. You can see it in action in the example app. It's also mentioned in the [docs](https://wix.github.io/react-native-navigation/#/styling-the-navigator?id=style-object-format), though that style object is a bit intimidating.

**Comment by guyca** [comment]
@DanielZlotin Is this something you guys are planning on supporting in v2? If not we can close the issue.

**Comment by raunaqss** [comment]
@guyca Really appreciate the quick response! Thanks!

**Comment by DanielZlotin** [comment]
Custom top bar will be supported, yes

**Comment by guyca** [comment]
@DanielZlotin What about [TitleBar icon](https://developer.android.com/reference/android/support/v7/app/ActionBar.html#setIcon(int))? v1 currently supports it only on iOS and not on Android.

**Comment by DanielZlotin** [comment]
We can add that, sure

**Comment by raunaqss** [comment]
@guyca Trying to implement `navBarCustomView` to work around the above limitation on Android. However, can't get the custom navbar to show up. Looking at the issues related to this, it seems this feature too is not supported for android. Could you recommend any workaround to get a title image for Android?

**Comment by guyca** [comment]
Hey @raunaqss 
Actually it is supported on Android, see the example app for [reference](https://github.com/wix/react-native-navigation/blob/f14e4bbaf568270db31e7532aeb6c6537d711589/example/src/screens/types/CustomTopBarScreen.js)

**Comment by pqkluan** [comment]
[This feature is already available](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=buttons-object-format)
