### ISSUE TITLE
[V3]: dismissModal animation doesn't work when using hooks

### ISSUE THREAD

**Issue by luskin** [wix/react-native-navigation#5640]
### Issue Description

When calling the same dismissModal function from a button, the dismiss animation works as expected. When calling this same method from an effect, there is no animation, see code below:

### Steps to Reproduce / Code Snippets / Screenshots

```js
const TestScreen = ({ componentId }) => {
  useEffect(() => {
    const listener = Navigation.events().registerNavigationButtonPressedListener(event => {
      if (event.componentId === componentId) {
        switch (event.buttonId) {
          case NAVBAR_BUTTONS.CLOSE.id:
            Navigation.dismissModal(componentId) // THIS DISMISSES THE MODAL WITHOUT ANIMATION
            break
          default:
            break
        }
      }
    })

    return () => listener.remove()
  }, [componentId])

  return (
    <SafeAreaView>
      <PillButton
        title="Hide"
        backgroundColor="#000000"
        titleColor="#FFFFFF"
        shadow
        onPress={() => {
          Navigation.dismissModal(componentId) // THIS DISMISSES THE MODAL WITH ANIMATION
        }}
      />
    </SafeAreaView>
  )
}
TestScreen.displayName = 'TestScreen'

TestScreen.options = props => ({
  topBar: {
    title: {
      text: props.title,
      color: '#ffffff',
    },
    rightButtons: [NAVBAR_BUTTONS.CHAT],
    leftButtons: [NAVBAR_BUTTONS.CLOSE],
  },
})
export default TestScreen
```

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): BOTH
* Device info (Simulator/Device? OS version? Debug/Release?): Debug Simulator Only

**Comment by jpgarcia** [comment]
Hi @luskin I couldn't reproduce this issue neither on **Android** nor **IOS** 😢 

BTW Yesterday we fixed an issue on [react-native-navigation-hooks](https://github.com/underscopeio/react-native-navigation-hooks) that could be related to this one. Here is the one https://github.com/underscopeio/react-native-navigation-hooks/issues/7

I'm wondering that maybe you're facing the same issue, in that case I would try to use `useLayoutEffect` instead of `useEffect`

Also consider using it as you'll end up with a much cleaner code 💅 

```js
import { useNavigationButtonPress } from 'react-native-navigation-hooks'

useNavigationButtonPress(() => {
  Navigation.dismissModal(componentId)
}, componentId, NAVBAR_BUTTONS.CLOSE.id)
```

Hope it helps!
