### ISSUE TITLE
[v3][v4] currentTabIndex can't be set in setRoot

### ISSUE THREAD

**Issue by GioLogist** [wix/react-native-navigation#5679]
Seems like [this issue](https://github.com/wix/react-native-navigation/issues/5012) is back

```
"react-native-navigation": "^3.7.0",
```

```js
   Navigation.setRoot({
      root: {
        bottomTabs: {
          children: tabs,
          currentTabIndex: 1,
        }
      }
    })
```

Has no effect, tabs stay the same.

For added context, setting it in `Navigation.setDefaultOptions` works just fine.

**Comment by wongp** [comment]
Environment
React Native Navigation version: 3.7.0
React Native version: 0.60.5
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device?): Both

I was facing this same issue has well on iOS after upgrading and using `setDefaultOptions` seems to have done the trick! I'm worried about performance issues though since I make the call to `setDefaultOptions` often during our navigation.

@GioLogist Have you seen any problems using `setDefaultOptions`? Or do you feel that it is interchangeable with `mergeOptions`?

**Comment by GioLogist** [comment]
I haven't noticed any issues just yet. That being said, I mostly run it when the app first launches or when changes are made to auth (IE: `startGuestApp`, `startMemberApp` pattern).

**Comment by GioLogist** [comment]
Not stale

**Comment by GioLogist** [comment]
@guyca sorry to keep tagging you. not sure who else is best to tag, to mark not stale.

**Comment by ItsNoHax** [comment]
@GioLogist In your example you forgot to put the currentTabIndex inside the options object, can you check if that helps?

**Comment by guyca** [comment]
@GioLogist Thanks for pinging us 🙇 Before we look into this, could you please follow up on @ItsNoHax comment?

**Comment by GioLogist** [comment]
@guyca @ItsNoHax Sorry for the delay. This is not stale, just tested. Adding it via an options object also makes no difference,

**Comment by yogevbd** [comment]
Tested and it doesn't seem to be broken.
This is how you should use it:
```
Navigation.setRoot({
  root: {
    bottomTabs: {
      children: tabs,
      options: {
        bottomTabs: {
          currentTabIndex: 1
        }
      }
    }
  }
})
```
