### ISSUE TITLE
drawUnderNavBar not working when used together with navBarTransparent on iOS

### ISSUE THREAD

**Issue by jaggerwang** [wix/react-native-navigation#568]
### Issue Description

 As the title said, but on Android, it's ok.
And drawUnderNavBar can used together with navBarTranslucent, both on iOS and Android.
---
### Environment
* React Native Navigation version: 2.0 newest
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by neogermi** [comment]
👍

**Comment by neogermi** [comment]
We have this as well with RN 0.43

**Comment by holden-caulfield** [comment]
Seen this as well. I've tested it on the iOS simulator only... so hopefully is working ok on a real device?

Anyways, I've found an (ugly) hack that seems to fix it. While still keeping the navigator fully styled on your component trough the `static` declaration, also pass `navBarTranslucent: true` to the navigator while pushing the screen, like this:

    this.props.navigator.push({screen: 'your.screen.name',
         navigatorStyle: {
             navBarTranslucent: true
         }})

Yes, you need to pass `navBarTranslucent` even though you want it to be transparent. And yes, is hacky and a bummer because you need to include it on every push you do to that screen. But at least that made it work for me.

Hopefully this gets fixed

**Comment by holden-caulfield** [comment]
Confirmed it also happens on a real iOS device so by now that hack is the only solution I've found

**Comment by aminroosta** [comment]
```js
   static navigatorStyle = {
      drawUnderNavBar: true,
      navBarTransparent: true,
      navBarTranslucent: true
   };
```

It works if you set both `nabBarTransparent` & `navBarTranslucent`.

**Comment by kmdupr33** [comment]
This does not work on iOS 11 :(

**Comment by anthonator** [comment]
@aminroosta's suggestion works for me on iOS 11.2. However, I get a translucent flash before it goes transparent when using the simulator. Haven't tried an actual device yet. Not sure if this is a workable solution.

Using `react-native-navigation` 1.1.300
