### ISSUE TITLE
'ReactNativeNavigation/ReactNativeNavigation.h' file not found when archiving with specific configuration

### ISSUE THREAD

**Issue by MorayM** [wix/react-native-navigation#5916]
### Issue Description

[Edited 2020-02-11 with more info]

I'm getting the famous `AppDelegate.m: 'ReactNativeNavigation/ReactNativeNavigation.h' file not found` error message, but only when building an archive with configuration `Beta`. `Release` and `Debug` both work fine, which is more confusing as `Beta` was originally cloned from `Release` and differ only in name and signing certs.

Yes, I've followed the [installation steps](https://wix.github.io/react-native-navigation/#/docs/Installing) to set up the header search path for each configuration!

### Steps to Reproduce / Code Snippets / Screenshots

I'm currently putting together a barebones example of this behaviour, but in the meantime:

This behaviour is seen when using Product -> Archive in XCode with the Configuration for the `MyApp` scheme set to `Beta`, and when building with Fastlane `gym`. The `xcodebuild` command `gym` generates is below.

``` sh
# Generated by Fastlane
xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -configuration Beta -destination 'generic/platform=iOS' -archivePath <path to xcarchive file> archive
```

AppDelegate.m:

``` objective-c
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <ReactNativeNavigation/ReactNativeNavigation.h>
#import "RNSplashScreen.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];

  [RNSplashScreen show];

  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

---
### Environment
* React Native Navigation version: 2.26.2
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): IPA

**Comment by simonlowedev** [comment]
For anyone else facing this same problem when using a beta enviroment. 

The problem was the environment configurations on the libraries. On initial set up or when reinstalling the node_modules the libraries would be missing the beta configuration – as this isnt one of the defaults – hence why release and debug builds worked find. To solve this you just need to go through each of the libraries in xcode and add a Beta configuration. See screenshot.

<img width="500" alt="Screenshot 2020-02-19 at 12 09 20" src="https://user-images.githubusercontent.com/23050284/75031939-46a56880-549f-11ea-9349-29375152fd88.png">

I would be interested to know if there is a better way of doing this.

**Comment by kobe-finance** [comment]
@simonlowedev can you explain more
