### ISSUE TITLE
 How to combine multiple important native packages in one project with react-native-navigation?

### ISSUE THREAD

**Issue by muhammadwafa** [wix/react-native-navigation#5923]
As you can see there are `methods` within `MainActivity.java` class is added as I installed `react-native-gesture-handler` and `react-native-orientation-locker` and may other packages too in the future.

```java
public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "hello";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
        return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }

  @Override
  public void onConfigurationChanged(Configuration newConfig) {
      super.onConfigurationChanged(newConfig);
      Intent intent = new Intent("onConfigurationChanged");
      intent.putExtra("newConfig", newConfig);
      this.sendBroadcast(intent);
  }

}
```

But in your doc we have to change `ReactActivity` to `NavigationActivity` and also we have to remove the `methods` was inside `MainActivity extends ReactActivity`.  So here What Can I with other packages ??? 

_Originally posted by @muhammadwafa in https://github.com/wix/react-native-navigation/issues/5904#issuecomment-584777833_

**Comment by drewhamlett** [comment]
https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#with-wix-react-native-navigation-https-githubcom-wix-react-native-navigation

**Comment by muhammadwafa** [comment]
Thank you I used  that link but still there is problem with auto linking and orientation locker package.

**Comment by ItsNoHax** [comment]
@muhammadwafa Orientation locking can be achieved in react-native-navigation and as @drewhamlett mentioned you will need to wrap your screens with the provided HoC from react-native-gesture-handler. Going to close this issue though as this is not the first time this has been asked.

**Comment by daveyjones** [comment]
I need to use react-native-orientation-locker so that my app can listen to orientation changes and respond accordingly. As far as I can tell, RNN does not provide this functionality. I'd love to know how to integrate it given that we can't override `onConfigurationChanged`.

**Comment by daveyjones** [comment]
@muhammadwafa Did you ever figure out a way to use react-native-orientation-locker?

**Comment by daveyjones** [comment]
Nevermind, I figured it out:
```
public class MainActivity extends NavigationActivity {
    @Override
    public void onConfigurationChanged(@NonNull Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        Intent intent = new Intent("onConfigurationChanged");
        intent.putExtra("newConfig", newConfig);
        this.sendBroadcast(intent);
    }
}
```

**Comment by drpiou** [comment]
I think this should not be closed. The title mention "How to combine multiple native packages" mentioning "ReactActivity" and "NavigationActivity" which seems to be an issue today.

Because I have changed "ReactActivity" to "NavigationActivity", I cannot implement "createReactActivityDelegate" which is needed by the expo modules installation (not mentioning Expo, this is the case with many other packages).

Where/how should I add the needed method "createReactActivityDelegate" in my "MainActivity" (please provide a full example) to satisfy my package setup?

Thanks in advance.

**Comment by smn-snkl** [comment]
@drpiou did you manage to solve this? We're having the same problem trying to configure an Expo package with our app using RNN and the only major issue is that the NavigationActivity doesn't implement / expose the createReactActivityDelegate ...

**Comment by drpiou** [comment]
Hello @smn-snkl, I changed everything in our app to get rid of RNN at all (and I do not plan to use it again in my future projects). I selected react-navigation (which also have some issues, but can be worked around at least). So I started a whole new project using the expo cli command with a native template, this in exchange limit me to RN 64 but make the expo libraries working pretty great in the end. I then removed my src folder to my new project. For sure I had to refactor everything, but because I tend to always wrap any library, I had to change my navigation wrapper and made the whole app working again without changing all my files. Clearly this is not what you except to read, but I guess I had no other solution. Best :)
