### ISSUE TITLE
Pushing new screen where id is present somewhere else within bottom tabs

### ISSUE THREAD

**Issue by drewhamlett** [wix/react-native-navigation#5962]
### Issue Description

I have screens in my app that can exist on multiple tabs.  So you can get to the "ListViewScreen" and "DetailScreen" from the HomeTab and the ProfileTab.  If I go to the "ListViewScreen" in the HomeTab, then switch to the ProfileTab and do a push to the "DetailScreen" it goes to the "DetailScreen" on the HomeTab and not the ProfileTab.  I'm guessing because these id's already exist in the stack.  I don't know how to really solve this other than registering screens that can appear in both tabs by prefixing the tab name with the screen name.   

Am I missing something simple here?  Thanks!

---
### Environment
* React Native Navigation version: 5.1.1
* React Native version: 0.60.26
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Debug / Release

**Comment by guyca** [comment]
Hey @drewhamlett, Sorry for not responding sooner. As you've mentioned, this happens since you have multiple screens with the same id. I suggest you let RNN handle id's in this case, and use predefined id's only when needed.

Usually predefined id's are handy for stack or other parent layouts (not component layout) which exists only once - this allows the developer to easily manipulate these layouts.
