### ISSUE TITLE
[v6][Types] Icon type does not accept object

### ISSUE THREAD

**Issue by safaiyeh** [wix/react-native-navigation#6099]
### Issue Description
Icon can accept an object with different attributes

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
icon: {
  uri: '...',
  scale: 5
}
```

TypeScript Error
```
Type '{ uri: string; scale: number; }' is not assignable to type 'string | number | undefined'.
  Type '{ uri: string; scale: number; }' is not assignable to type 'number'.
```

---
### Environment
* React Native Navigation version: ^6.4.0
* React Native version: 0.62.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by guyca** [comment]
Hey @safaiyeh 👋 
Seems like you're referring to [ImageURISource](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L3507) while RNN uses [ImageRequireSource](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L3570) which is the result of requiring an image.

Should we be using ImageURISource?

**Comment by safaiyeh** [comment]
I believe so. The properties I defined take effect, should be reflected in the type.

**Comment by guyca** [comment]
Oh actually you're probably referring to [ImageResolvedAssetSource](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L3672) which is the result of `Image.resolveAssetSource(value)` where value is of type `ImageRequireSource`.

@safaiyeh Want to submit a PR? It's probably a small change to [processImage](https://github.com/wix/react-native-navigation/blob/master/lib/src/commands/OptionsProcessor.ts#L63)

**Comment by safaiyeh** [comment]
Sure! I can check it out tonight.

**Comment by koiralakiran1** [comment]
Hi @guyca,
This was reported on v6 and the latest is already in v7.1 and since this has been open for quite a while now, do you think this is still a valid issue?

I'd like to submit a PR if you think this is still valid.

I'm thinking I'll need change
https://github.com/wix/react-native-navigation/blob/1b35b79ecbe2cf61b3047ddd68696d55e97eed4e/lib/src/interfaces/Options.ts#L757

to
```js
export type ImageResource = ImageRequireSource | ImageURISource | string | ImageSystemSource;
```
where `ImageURISource` is a named import from `'react-native'`
because `Asset.resolveAssetSource` here
https://github.com/wix/react-native-navigation/blob/1b35b79ecbe2cf61b3047ddd68696d55e97eed4e/lib/src/adapters/AssetResolver.ts#L5
accepts [ImageSourcePropType](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/faf806ad1949cc2a5ed3fc5b606a5078aeaa273d/types/react-native/index.d.ts#L3859)

Maybe I should also change the type of `value` on `AssetResolver.ts` to `ImageSourcePropType`?

Let me know what you think.

**Comment by yogevbd** [comment]
@koiralakiran1 Sounds good! Could you submit a PR?

**Comment by koiralakiran1** [comment]
@yogevbd Sure. I'll make the changes and submit a PR.
