### ISSUE TITLE
Fast refresh crash

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#6176]
### Issue Description

When fast-refresh needs to do a full-reload and there is a modal open, the app crashes. Is this a bug in fast-refresh with more than one react-root, or is this something that is addressable in `react-native-navigation`?

### Steps to Reproduce / Code Snippets / Screenshots

Open modal, trigger fast refresh on a file that exports more than a component.

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Any

**Comment by jfrolich** [comment]
Not stale

**Comment by grandedk** [comment]
Any news on this subject?

We're also experiencing this on the following environment:

- React Native Navigation version: 6.12.2
- React Native version: 0.63.3

**Comment by jfrolich** [comment]
Yeah would be great to explore a fix for this!

**Comment by aa-ar** [comment]
Experiencing the same issue with:

- Fast refresh on an open modal.
- Receiving a CodePush update while a modal is open.
- Foregrounding an app with an open modal.

Our environment:

- React Native v0.62.2
- React Native Navigation v7.0.0

**Comment by stevehowells404** [comment]
I am seeing this issue a lot with our live app, which pops up a modal in response to opening a push notification. The errors I see in Bugsnag are -
> Error
> "home.log" has not been registered. This can happen if:
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

and the last entry in the breadcrumb trail is 'notification_opened' which triggers a 'Navigation.showModal' in the code as seen here - 
```
      analytics.trackEvent('notification_opened', meta);
      Navigation.showModal({
        stack: {
          children: [
            {
              component: {
                id: 'logModal',
                name: 'home.log',
                passProps: {
                  defaultActiveIndex:
                    userInfo.type === 'dailyLogReminder' ? 0 : 2,
                  componentId: 'logModal',
                },
              },
            },
          ],
        },
      });
```

Hope this helps in finding a solution. In the meantime I have to find a workaround as we are losing users through this.

**Comment by dan-trewin** [comment]
Figured I'd post a couple more details I noticed about this bug for the benefit of the community.

1. This bug only happens to me with the "iOS swipe close-able modals". Modals with `modalPresentationStyle: 'fullScreen'` set seem to refresh just fine for me.
2. This bug also happens when forcing a refresh in a simulator with an open modal. ie. Navigate to a modal, Cmd + d, click reload, simulator freezes.
3. Using node_modules like <https://github.com/avishayil/react-native-restart> to restart the app also causes the simulator freeze.
4. This bug seems exclusive to the iOS simulator. When running on physical device, I have not run into it.

Workaround for 3:
`react-native-restart` provides a simple way to get a completely fresh instance of your app. The app I work on uses `react-native-restart` to restart the app when a user takes certain actions (like logging out).  This way we can ensure the app state is clean. That being said, it is annoying that in our dev environment (the iOS simulator) taking some of these actions will cause a freeze (when a modal is open). The workaround I've come up with is this helper function:

```js
import { Navigation } from 'react-native-navigation'
import RNRestart from 'react-native-restart'

export const restartApp = async () => {
	await Navigation.dismissAllModals()
	RNRestart.Restart()
}
```

Always calling `Navigation.dismissAllModals()` prior to the restart method, prevents the simulator freeze from occurring.

Hope these additional details help!
