### ISSUE TITLE
Attempt to invoke interface method 'void com.reactnativenavigation.layouts.Layout.destroy()' on a null object reference

### ISSUE THREAD

**Issue by AyushAppin** [wix/react-native-navigation#6293]
### Issue Description

[ENTER DESCRIPTION HERE]
App is getting crashed when navigating between the screens. 
### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 1.1.493
* React Native version:  0.59.10
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by jinshin1013** [comment]
@AyushAppin Hi there, I can see that you are on a very old version. I know upgrading to the latest version will take some effort however it is extremely hard for the developers to debug and fix the issue that are on V1 😓  Please try upgrading to the latest version to see if the problem is fixed. If not feel free to create an issue with a minimal reproduction. Sorry for the inconvenience 😥 Cheers.
