### ISSUE TITLE
Laggy animation 

### ISSUE THREAD

**Issue by antony-meunier** [wix/react-native-navigation#6332]
### Issue Description

Hello, I recently change my old 6S with an iPhone 11 pro, and I have some laggy issue since with my app.

I don't really know if navigation is the source if the issue, but maybe someone has the same problem... 
(It works perfectly on my 6s, and some other android phones)

Here is two short video, with both iPhone
[demo.zip](https://github.com/wix/react-native-navigation/files/4820827/demo.zip)

Thanks for your help !
---
### Environment
* React Native Navigation version: 2.3.1
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): 11 pro

**Comment by guyca** [comment]
Hey @antony-meunier 
I see you're using an old version... a lot has changed since so I suggest you upgrade and see if you notice any improvement.

Also, you might want to move any logic that's executed in constructor or CDM to `componentDidAppear` which is invoked when the animation completes.
I'm closing the issue since there's really not much we can do unless you point us to a particular area in the code.
