### ISSUE TITLE
[V6] Getting import build errors on iOS

### ISSUE THREAD

**Issue by oferRounds** [wix/react-native-navigation#6367]
### Issue Description
Upgrading from v1 to v6(!)

Linked the project manually – getting some errors:

- In some files, for example `RNNViewLocation.h`, I get **"Unknown type name 'CGRect'; did you mean 'Rect'?".** If I replace the `#import <Foundation/Foundation.h>` with `#import <UIKit/UIKit.h>`, then the error is gone
- on `RNNReactView.m`, I get: **"'React/RCTRootContentView.h' file not found"**. I wasn’t able to resolve this one

Any idea? Thanks for this awesome library!

---
### Environment
* React Native Navigation version: 6.8.0
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by jinshin1013** [comment]
Hi @oferRounds 🙌 , thanks for reporting the issue! It'd be super helpful if you could provide a minimal reproduction on Github for us to have a better look at the problem.

**Comment by oferRounds** [comment]
@jinshin1013 thanks! Is the library suppose to work with react-native 0.59?
I think this is the same issue as mentioned here, in `react-native-gesture-handler`: https://github.com/software-mansion/react-native-gesture-handler/issues/816

**Comment by oferRounds** [comment]
I tried now also on a new project with 0.59.10 and Xcode 11.5 (latest), getting same type of errors: the import from react fails:

![image](https://user-images.githubusercontent.com/1477963/86909668-1cd4a180-c121-11ea-9ee5-06353ad3349c.png)

**Comment by oferRounds** [comment]
@yogevbd hi! Could you have a look
Possibly?

**Comment by yogevbd** [comment]
@oferRounds this is very strange.. Can you join our discord channel and send me a message there?

**Comment by oferRounds** [comment]
Will do, thanks!

**Comment by willyp63** [comment]
Hey @yogevbd @oferRounds 

Running into this exact issue trying to run on an iOS simulator (RN: 0.63.4, React: 16.13.1, & RNN: 7.8.0)

This came about after trying to upgrade RN to the latest version. After the upgrade we were getting a version mismatch error that seemed to be caused by RNN:
<img width="563" alt="Screen Shot 2021-01-06 at 9 40 43 AM" src="https://user-images.githubusercontent.com/15879255/103795531-58362700-5003-11eb-8177-4f8eb7714743.png">

To resolve the issue we tried upgrading RNN to the latest version as well, which then resulted in the build error originally posted in this thread.

Do either of you recall what the solution was here?
