### ISSUE TITLE
Double BottomTabs bar

### ISSUE THREAD

**Issue by webforuse** [wix/react-native-navigation#6375]
### Issue Description

1. Splash Screen
2. BottomTabs - component with 3 screens

Case:
1. setRoot(SplashScreen)
2. push(BottomsTabs)
3. switch thrid screen , press button , setStackRoot(SplashScreen)
4. push(BottomsTabs)

Result : bottom tabs double

How reset ?

---
### Environment
* React Native Navigation version: 6.9.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device Release/Debug

**Comment by jinshin1013** [comment]
Hi @webforuse thanks for reporting the issue! It'd be greatly helpful if you could either provide a minimal reproduction on Github or fork the library and tweak the Playground app to reproduce your issue. Cheers!

**Comment by webforuse** [comment]
Hi, @jinshin1013 

i update repo (this sample)
https://github.com/webforuse/sandbox


![Запись экрана 2020-07-10 в 10 12 09](https://user-images.githubusercontent.com/37406224/87127158-229fc380-c296-11ea-84bb-86e1b6c1aa15.gif)



![Simulator Screen Shot - iPhone SE 13 - 2020-07-10 at 10 09 45](https://user-images.githubusercontent.com/37406224/87126798-7f4eae80-c295-11ea-962a-49ceda7a3ee7.png)

Thank you very much for your feedback.

**Comment by guyca** [comment]
Seems like your problem is caused by misuse of the api.

Instead of replacing the root entirely, you keep replacing the stack root with layouts which contain bottomTabs. Perhaps the [Basic Navigation](https://wix.github.io/react-native-navigation/docs/basic-navigation) and [Advance Navigation](https://wix.github.io/react-native-navigation/docs/advanced-navigation#replacing-the-root) articles in the docs will provide a clearer picture.

**Comment by webforuse** [comment]
thanks
