### ISSUE TITLE
Missing types in OptionsTopBar

### ISSUE THREAD

**Issue by jpgarcia** [wix/react-native-navigation#6383]
### Issue Description

`OptionsTopBar` interface does not include definitions for `leftButtonStyle` / `rightButtonStyle`

### Steps to Reproduce / Code Snippets / Screenshots

![Screen Shot 2020-07-10 at 10 41 08](https://user-images.githubusercontent.com/95109/87168932-95646b00-c2a5-11ea-9e01-50393ae72822.png)
![Screen Shot 2020-07-10 at 10 41 33](https://user-images.githubusercontent.com/95109/87168939-98f7f200-c2a5-11ea-8f91-6d3a85ad7b8c.png)

---
### Environment
* React Native Navigation version: 6.9.0
* React Native version: 0.63.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): N/A

**Comment by guyca** [comment]
Hey @jpgarcia 👋 
I believe these options are obsolete. They were introduced over a year ago as part of an attempt to provide means to declare a single style for all buttons in the TopBar. The reason we scraped this design was because it meant we now had duplicate places where button styles could be defined which can be confusing.

We're now working on a new api which will let developers hook into RNN's style (options) processing logic. This will allow for a more flexible styling logic and also allow you to share a single options object with all buttons, which was our intention with `leftButtonStyle` and `rightButtonStyle`.

Thanks for bringing this up, Love your work on https://github.com/underscopeio/react-native-navigation-hooks 🔥🔥🔥

**Comment by jpgarcia** [comment]
Ohhh good to know! I was about to submit a PR with those types 😅
I noticed what you mention about the duplication, now it's clear to me!

Glad to hear you like the hooks lib 🤩
