### ISSUE TITLE
How to migrate from v1 to latest version

### ISSUE THREAD

**Issue by aTrueSeeker** [wix/react-native-navigation#6783]
## 📚 Documentation

No documentaion from migrating from v1

**Comment by jinshin1013** [comment]
Hi @aTrueSeeker it has been quite some time the project has upgraded to `V7` and there were some fundamental changes since if I remember correctly 😅

I understand that the migration from V1 to V7 isn't going to be smooth and frankly could be painful 🙏 but I'd suggest you become familiar with the latest API, perhaps you could play around with `Playground` app. Once you are confident that you understand how it works, it'd be much easier to start your migration. 

Again, apologies that there isn't a fixed migration path we could provide however you are always welcome to shoot us questions on our Discord channel 🙌
