### ISSUE TITLE
Android Title is always to the left, and doesn't respect `layout.direction`.

### ISSUE THREAD

**Issue by a-eid** [wix/react-native-navigation#6974]
## 🐛 Bug Report

> I'm trying to setup i18n intro my app & android topbar is alway set to the left event when I have `layout.direction` set to `rtl` & `I18nManager.forceRTL(true)`, IOS just works. 

## To Reproduce

- `setDefaultOptions` `layout.direction` to `rtl`

## Expected behavior

- android backButton should change to the right & title should also change direction to the right.

## Actual Behavior

- android backButton doesn't show at all & title is always to the left.

![Screen Shot 2021-02-18 at 3 25 22 AM](https://user-images.githubusercontent.com/19273413/108316820-1681ca00-71c6-11eb-8109-685c3ae6c416.png)
![Screen Shot 2021-02-18 at 3 25 27 AM](https://user-images.githubusercontent.com/19273413/108316828-17b2f700-71c6-11eb-89fc-6cf2fadeba12.png)

weirdly enough android doesn't show a back button with `rtl` & `ltr`. 

## Your Environment
- React Native Navigation version: ^9.8.0 & ^7.9.0 & ^7.10.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): android
- Device info (Simulator/Device? OS version? Debug/Release?): debug ( I assume it behaves the same on release ).

## Reproducible Demo

https://github.com/a-eid/rnn/tree/android-rtl

this reproduces the topBar title issue, it doesn't reproduce the back button issue some how, I'll update when I'm able to reproduce it.

**Comment by swabbass** [comment]
@a-eid Thx for reporting, [the provided demo](https://github.com/a-eid/rnn/tree/android-rtl) is missing `android:supportsRtl="true"` in your demo android manifest, I added one and it just worked.

Updated the docs, for the next release.

- In android in general (Not RN apps only), in order to support RTL, you have to add this https://developer.android.com/training/basics/supporting-devices/languages#MirroringManifest
- You can always try in the playground and see if things are mis-configured.

**Comment by a-eid** [comment]
great, thank you 

حبيبي

**Comment by a-eid** [comment]
please feel free to close this issue, I'll be testing this in a couple of hours & reporting back.
