### ISSUE TITLE
navigationButtonPressed not emitted on backButton

### ISSUE THREAD

**Issue by ValentinOUI** [wix/react-native-navigation#7035]
## 🐛 Bug Report

Hello,
I need to emit a `navigationButtonPressed event` whenever I am pressing the Back button from the topbar. The event seems not to be listened at all.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Add an id to the default backButton (index.js)

```
Navigation.setDefaultOptions({
    topBar: {
      backButton: {
        id: 'BACK',
      }
    }
});    
```

2. Add a listener

```
useEffect(() => {
    const listener = {
      navigationButtonPressed: (_event: NavigationButtonPressedEvent) => {
        if (_event.buttonId === 'BACK') {
          console.log("Hello");
        }
      },
    };

    const event= Navigation.events().registerComponentListener(
      listener,
      componentId,
    );

    return () => {
      event.remove();
    };
  }, [componentId]);
```

3. Press the back button on corresponding screen

## Expected behavior

The console should display "Hello" 

## Actual Behavior

Nothing happened

## Your Environment

- React Native Navigation version: 7.11.3
- React Native version: 0.62.2
- Platform(s) (iOS, Android, or both?): Both
- Device info (Simulator/Device? OS version? Debug/Release?):  iOS 13.4 (device) and iOS 14.4 (Simulator), Android <10

**It is working correctly on an Android studio virtual device with Android 10.0**

Thanks a lot !

**Comment by jeseter45** [comment]
*Regular user of RNN library here.*

I would recommend you to use [react-native-navigation-hooks](https://underscopeio.github.io/react-native-navigation-hooks/docs/before-you-start) community library. Your code become much cleaner.

Once you set it up properly then you use only one hook:

```
import {useNavigationButtonPress} from 'react-native-navigation-hooks';

// ...

useNavigationButtonPress(e => {
  switch (e.buttonId) {
    case 'BACK':
      console.log("Hello");
      return;
    default:
      // do some logging here
  }
});
```

*Note: Make your back/left/right buttons ID of the top bar unique. I am defining my buttons ID inside component function and appending componentId to the button id. This is something what can not be done in `setDefaultOptions`, but for testing purposes it is just fine.*

**Comment by ValentinOUI** [comment]
Thanks for your help
However the code snippet I pasted is already a part of a more complex custom hook I made. 

I still tried to use the library with no additional logic but I kept having the same issue.

I also made sure that my back buttons ID are unique per component, thanks for noticing !

**Comment by yogevbd** [comment]
In order to receive back button event you first need to disable its default behavior.
```js
topBar: {
  backButton: {
    popStackOnPress: false,
  }
}
```
Read more about it [here](https://wix.github.io/react-native-navigation/docs/stack#handling-the-back-button).

**Comment by jeseter45** [comment]
@yogevbd What is the point of that? Why definition of the title is not enough?

**Comment by ValentinOUI** [comment]
> In order to receive back button event you first need to disable its default behavior.

Thanks, the event is now correctly emitted, but setting a custom ID for the back button doesn't work on iOS.
I can deal with the default back button id.

Thank you !

**Comment by guyca** [comment]
> @yogevbd What is the point of that? Why definition of the button ID is not enough?

@jeseter45 First, I'd like to apologize for the breaking change. We knew a few users will be broken by this and decided to give ourselves a pass and not do a proper gradual deprecation.

Second, the reason setting an id isn't enough is because it's not explicit enough and doesn't communicate the developer's intent clearly. Now, a click event is always emitted when the back button is pressed. If the developer wants to handle the back button press as well he explicitly requests RNN not to pop the stack / dismiss the modal. We believe this API is clear and allows more flexibility.

For example, if all you need is to emit a bi event when the back button is clicked, there's no reason to delay popping the screen. You can do that by specifying a back button id. If you wish to handle the back button in order to show a dialog of some sort, you can do that by instructing RNN not to handle the back press.

Sorry for the inconvenience.
