### ISSUE TITLE
Problem with button's custom component while testing app

### ISSUE THREAD

**Issue by leralera2201** [wix/react-native-navigation#7129]
I set custom component for right button and pass onPress function, also I add testID, and when I tap on this button through my tests, onPress function doesn't work. Click is made, because I see touchable effect. But function is not called at all. Also custom component does not trigger event in navigationButtonPressed. I use Detox for testing. This is my right button:

```js
{
  id: 'login-button',
  testID: 'publicEvents.nav-login-button',
  component: {
    name: 'LoginNavBarButton',
    passProps: {
      onPress: onEventLoginPress
    }
  }
}
```

How I tap on this button:
await element(by.id('publicEvents.nav-login-button')).tap();

**Comment by guyca** [comment]
Hey @leralera2201 👋 
When displaying react components as buttons, pressing them doesn't trigger `navigationButtonPressed` event. This is by design.

It seems like an issue in your component. Probably the onPress function isn't wired correctly. I suggest you try and reproduce this issue in the Playground app. If you're able to reproduce, please push the reproduction to your fork and someone will look into it.
