### ISSUE TITLE
Side Menu stil opens when visible and enabled set to false and cannot open with button 

### ISSUE THREAD

**Issue by njoshi94** [wix/react-native-navigation#7357]
I am currently trying to implement my side menu in my React Native application with Typescript and I only want it to open on some screens. By default, it should be not able to be opened. However, even on the screens where I have set Visible and Enabled to false, I am still able to swipe and open the Side Menu.

Additionally, I want the menu to be able to be opened by pressing a button, but whenever I press the button, nothing happens. 

Below is my code for my root as well as the button. Please let me know what additional information is needed. 

```
Navigation.setDefaultOptions({
  topBar: {
    visible: false,
  },
});

Navigation.events().registerAppLaunchedListener(async () => {
  Navigation.setRoot({
    root: {
      sideMenu: {
        center: {
          stack: {
            children: [
              {
                component: {
                  name: 'mp.Loading',
                },
              },
            ],
          },
        },
        left: {
          component: {
            name: 'mp.SideMenu',
            id: 'mp.SideMenu',
            options: {
              layout: {
                componentBackgroundColor: 'white',
              },
              sideMenu: {
                left: {
                  enabled: false,
                  visible: false,
                },
              },
            },
          },
        },
      },
    },
  });
});
```

Button:

``` 
onPress = () => {
    Navigation.mergeOptions(this.props.componentId, {
      sideMenu: {
        left: {
          visible: true,
          enabled: true,
        },
      },
    });
  };
```

React Native: 0.66.1
React Native Navigation: 7.23.1
On Android and PC

**Comment by swabbass** [comment]
Hey, I see missing info about RN version, RNN version, which platform,  can you, kindly, fill the issue template and not delete it?

**Comment by njoshi94** [comment]
> Hey, I see missing info about RN version, RNN version, which platform, can you, kindly, fill the issue template and not delete it?

I have updated the original post with the versions of RN, RNN, and the platform

**Comment by swabbass** [comment]
I tried to replicate the described behaviour, but could not reproduce it, see from our playground:

https://user-images.githubusercontent.com/7227793/142768695-6ea957b1-5ebb-47e6-a284-b77e017ba923.mov

What we can say is:

1. Button can open a drawer, via `mergeOptions` , the main issue might be that the component id you are passing is not right, try to use static one and call `mergeOptions` with it and see.
2. When you unset enabled, the menu cannot be opened, as you can see on the screenshot, and it could be related to `componentId`.

I suggest, kindly, that you create a minimal project which has the issue reproduced and share it here with us so we can debug it instead of guessing, or, fork our playground and make your changes and share them here so we can reproduce it.

**Comment by njoshi94** [comment]
By exploring the playground, I was able to figure out the issue.

**Comment by swabbass** [comment]
> By exploring the playground, I was able to figure out the issue.

Glad to hear that :]

**Comment by 08Thug** [comment]
@swabbass  I can't understand the side menu using React native navigation, could you share the source so that by analysing it.I can get to know better

**Comment by 08Thug** [comment]
> By exploring the playground, I was able to figure out the issue.

could you share the link for source code? @njoshi94
