### ISSUE TITLE
Trigger appear event after dismissModal (modalPresentationStyle -> overCurrentContext)

### ISSUE THREAD

**Issue by lindesvard** [wix/react-native-navigation#7359]
## 🚀 Feature

I want to be able to listen if a screen did appear even if the modalPresentationStyle is `overCurrentContext`. We have a quite large app with many independent teams and routes. 

We need to keep track what the current displayed screen is. We do this by listening on `componentDidAppear`. Something like below 

```
import { Navigation, ComponentDidAppearEvent } from 'react-native-navigation'

class NavigationStore {
  private currentComponentId = ''

  constructor(navigation: typeof Navigation) {
    navigation.events().registerComponentDidAppearListener(this.registerCurrentComponentId)
  }

  private registerCurrentComponentId({ componentId }: ComponentDidAppearEvent): void {
    this.currentComponentId = componentId
  }

  public get current(): string {
    return this.currentComponentId
  }
}
```

This works great until we show a modal with `overCurrentContext`. Below is a user journey where our problems occur.

```
push(A) // will trigger appear A
showModal(B) // will trigger appear B
dismissModal(B) // will trigger appear A
showModal(C, { modalPresentationStyle: 'overCurrentContext' }) // will trigger appear C
dismissModal(C) // will NOT trigger any appear event on A 
```

Not sure if this is a restriction on iOS but would love if we could get the appear event when a modal is closed with `overCurrentContext`.

- [x] <strong>Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?</strong>

## Motivation

So have already talked about the motivation a bit but I can see this be quite useful for developers to know if a screen below a modal with `overCurrentContext` would re-appear after the modal is close. React to that, refetch data, track current componentId. 

## Pitch

Not sure if this would be supported under the hood (on iOS) but otherwise it could be implemented like this.

```
// pseudo code somewhere in dismissModal
await internal.dismissModal(componentId)

// does closed modal have overCurrentContext
if(options.modalPresentationStyle == 'overCurrentContext') {
  // basic check to find out what screen should trigger appear event
  if (!overlay.isEmpty()) {
    emitDidAppearEvent(overlay.getLast())
  } else if (!modal.isEmpty()) {
    emitDidAppearEvent(modal.getLast())
  } else {
    emitDidAppearEvent(stack.getLast())
  }
}
```

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by swabbass** [comment]
Well, that is the essence of `overCurrentContext`, which means that the context on which the modal is being shown upon is still "visible" (appearing) to the user, hence, the context, here is the bottom modal, did not receive `didDisappear` event when modal on top is shown, which in turn no `didAppear` should be sent.

So the premise `overCurrentContext` relies upon, the fact that the shown modal (top) hosted over the context (partially or fully) without it being gone, which means the "context" (bottom) did not disappear.

Now, `didAppear` event is sent in 2 cases:
1. Initially when the view was not there and it becomes visible.
2. The view was "disappeared" for a reason like `pop` or `push` in the case of a stack for example (`showModal` with default `modalPresentationStyle` which behaves like a stack of modals).

In both cases, the disappear event was sent because the view is gone, hence, not visible to the user, and in the case of `overCurrentContext` the "context", which is a modal in your example is not gone.

So what you are suggesting is defying the logic behind `overCurrentContext`, but, I can suggest 2 solutions:

1. Use default presentation style and set layout background to be transparent somehow and see if that fits your needs.
2. Introduce a new event about a view becoming interactable, which covers your case, which means you might need to open a new feature for such an event.
