### ISSUE TITLE
All tabs will render when startTabBasedApp?

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#74]
It seems every tabs will render when app start? 
I have:
TabOne
TabTwo
TabThree

I don't tap on TabTwo and TabThree but every request called and view render before i tab them.

**Comment by beast** [comment]
Are you experiencing this on Android version? I am seeing the same problem on startSingleScreenApp as well. I think I narrow it down to the intent.addflags() not working as intended by this commit https://github.com/wix/react-native-navigation/commit/39548c57e6e94ad7227ef8131a138cec467f0830

@guyca 
I see that you are are setting the flags but in practice, if you use Reload JS in dev tools on simulator, the history stack in Android is still being read by the JS bundle. I am experimenting ways to fix. Any comments? Thanks.

**Comment by agumack** [comment]
@beast 
 I am testing on IOS

**Comment by guyca** [comment]
Hey @beast. I'm not sure how the Activity flags are related to the screen render issues @agumack mentioned. 
Is the odd behaviour you encountered reproducible in `example-redux` project?

**Comment by beast** [comment]
@guyca That is interesting. Yes, this behaviour is reproducible in example-redux. Just try reload js after you navigate a few tabs or pages. (Put a console.warn in each render method, you'll see this happening.)

@agumack No, I do not see this happening in iOS.

**Comment by guyca** [comment]
@DanielZlotin Seems like tab application behaviour on iOS and Android is inconsistent.

On iOS all tabs are rendered when `startTabBasedApp` is called - and all screens respond to state changes, even those not displayed on screen.

On Android, when navigating to a new tab, previous `ScreenStack` is [removed](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/activities/BottomTabActivity.java#L180) and the screens it contained are unmounted. So only the currently displayed screen responds to state changes.

Maybe we should implement something similar to [ViewPager.setOffscreenPageLimit()](https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setOffscreenPageLimit(int))

**Comment by guyca** [comment]
@agumack Why does it matter to you that `render` is called on offscreen views as well? The shadow DOM gets updated, but they don't actually get laid out on screen.

**Comment by DanielZlotin** [comment]
@agumack 
The actual issue here is that we don't have a correct and consistent way of listening to lifecycle events for the screens, for example something like `screenDidAppear`, `screenDidDisappear`.
These events do exists in native, but we don't forward them yet, and we plan to implement it ASAP since it is a requested and critical feature.
The `render` and `componentDidMount` functions should not be used as hooks for native lifecycle events.

side note: If your screen component subscribes for redux changes, for example, and is not currently displayed (for example, not currently at the top of the screen stack), it is important to keep its shadow view updated; so when you get back to it (for example you pop the stack) it will be updated with the correct redux state. This is a symptom and not a cause, the cause being the component (and it's native controller/view) is still there, just not on-screen.

**Comment by guyca** [comment]
3e8dca89f498cceb5b938bb414ea04447e9eff21 Some what consolidates Android and iOS behaviours in this regard. Screens are created when user first navigates to their tab. Once user navigates to a different tab, the screen will not be unmounted.

@artald Can you update iOS behaviour as well? Thanks.

**Comment by agumack** [comment]
@guyca thank you so much for support.
Because I don't kown how implement "badge for left/right button" so have change my layout apps using tabs. some tab screen call api and check some condition reponse. It redirect to a other screen if the condition is false (Ex: Profile tabs, ....)

ps: I few then using tabs layout, my app not smooth StartSingleScreenApp-Like.

**Comment by beast** [comment]
@guyca @DanielZlotin Hi, all. Thanks for your support. I now understand what could be my issue but this comes as really a surprise to me.

1. I am using StartSingleScreenApp in iOS for the last 3 months in my project and I don't see all my other screens being rendered at all. From what I am reading above, are you suggesting this only happens in startTabBasedApp in iOS?
2. I understand the part that there is no event forwarded from Android at the moment. But in a case that I would need to architecture my app only calls an API when I render a specific view, (Which is how my iOS working flawlessly) I shall change the architecture to call all my API at app start or refresh and only rely on redux store change?

Would greatly appreciate if someone could clarify these behaviours under different platform. Thanks a lot!

**Comment by beast** [comment]
I have figured out a solution. Thanks.

**Comment by MeKarina** [comment]
im still experiencing this issue with `rn-navigation@2.0.0-experimental.134` and `rn@0.31.0`..

i agree this is crucial issue especially when u share the same data on each tab... one change from one tab will affect other tabs causing all tabs will rerender.. its like data become global,, data flow become harder to predict and to trace... and become 2x harder when requiring data mutation...

also performance issue because all tabs will render at once especially when rendering complex big data...

thank Youu..

**Comment by guyca** [comment]
@MeKarina The expected behaviour is that all Screens associated with BottomTabs are mounted and rendered at startup. As you've noticed, mounted screens which are not visible also react to state changes.

This is actually one of the strong sides of RNN and means your BottomTab screens don't lose their internal state when you navigate to another tab.
Think about the basic use case of an e-commerce application that has a chat feature allowing seller and buyer to communicate with each other. The buyer asks the seller a question regarding an item. The seller navigates to the inventory tab and looks for the item etc. Then he navigates back to the Chat tab and the conversation is right were he left it - because the conversation screen was not unmounted.

Regarding performance, I can guarantee there's no performance hit. On Android, we detach inactive tabs from screen with out unmounting them while keeping a hard reference to them. This way your native views don't get garbage collected, but the system can still free up memory if needed since all images are detached from screen.

It seems to me your real issue is state management. I highly recommend you read an article written by one of my colleagues title [Avoiding Accidental Complexity When Structuring Your App State](https://hackernoon.com/avoiding-accidental-complexity-when-structuring-your-app-state-6e6d22ad5e2a#.jv85rcu54). it's a bit long but well worth it.

**Comment by MeKarina** [comment]
okay okay thats my stupidity after all,,my bad...

apologize...a bit confused because this is different with typical react app (single page app)... but this all make sense because this simply implement UITabBarController..

n even with startSingleScreen,,when new screen is pushed,,the root screen isnt unmounted after all,, which is great... for this i could transfer updated data from pushed screen to root screen via props...

but as for TabsScreen,, i guess api like `screenDidAppear` `screenDidDisappear` is great to eliminate the needs of something like redux to handle sideways loading..

is this `screenDidAppear` `screenDidDisappear` api still part of ur plan..??

or how wix handle sideways data loading between tabs..??

thank Youu..
karina

**Comment by alzalabany** [comment]
```
 i guess api like screenDidAppear screenDidDisappear is great to eliminate the needs of something like redux to handle sideways loading..

is this screenDidAppear screenDidDisappear api still part of ur plan..??
```
Is it?
