### ISSUE TITLE
Release build fails: Unsupported class file major version 59.

### ISSUE THREAD

**Issue by vliedel** [wix/react-native-navigation#7403]
## 🐛 Bug Report

When building a release version, I get:

```
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':react-native-navigation:reactNative63DebugUnitTestRuntimeClasspath'.
   > Failed to transform bcprov-jdk15on-1.68.jar (org.bouncycastle:bcprov-jdk15on:1.68) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /home/vliedel/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar.
         > Failed to transform '/home/vliedel/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).
```

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes.

## To Reproduce

Build release.

## Expected behavior

Build successful.

## Actual Behavior

Build failed.

## Your Environment

- React Native Navigation version: 7.24.0
- React Native version: 0.66.3
- Platform: Android
- Device info: Release build

## Suggestion

It seems very similar to: https://github.com/grpc/grpc-java/issues/8264

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by vliedel** [comment]
After adding `android.jetifier.blacklist = bcprov-jdk15on` to gradle.properties, it builds again.

**Comment by lyswhut** [comment]
Same problem,
it works:

> After adding `android.jetifier.blacklist = bcprov-jdk15on` to gradle.properties, it builds again.

**Comment by swabbass** [comment]
First, Thanks for reporting such a case. 

AFAIK, it is related to the android build tools, processing bountycastle transitive dependency, that required by libraries like [robolectric](https://github.com/robolectric/robolectric/issues/6521#issuecomment-902154567), [asm, an issue known by google](https://issuetracker.google.com/issues/159151549) and more, and it is, in nutshill, due to the jetifier that is requested to be true since RN started using AndroidX (0.63 I think), either you can disable it, or just blacklist the bountycastle to be processed or just upgrade to AGP 7, so since most of the projects are now [have to target android 30 ](https://developer.android.com/distribute/play-policies#APILevel30)  in order to be submitted to playstore, and RN uses jetifer, there are projects that did not migrate to AGP 7, and still use jetifier, which are most RN apps, either way, it is expected to take action and use one of the suggested flows: disabling jetifier, blacklisting problematic lib, upgrading to AGP 7.
