### ISSUE TITLE
Due to keyboard open, stuck UI

### ISSUE THREAD

**Issue by Mitesh-2009** [wix/react-native-navigation#7434]
https://user-images.githubusercontent.com/34374930/151766689-f78eb35f-21b1-41c0-8374-7ec38599c9da.mov

When we click any text input then the keyboard opens and when we close the keyboard the scroll view UI is stuck.
Some times keyboard is open then an immediate overlay opens then UI stuck issue occurs for more info check the Video attached.
And some react-native-navigation lib components option properties commit then some portion of keyboard issue works.

Android 10 and 11 working fine but in android - 8, 9 UI getting stuck
 
React-native version :- 0.66.4
react-native-navigation version:- 7.25.0

**Comment by swabbass** [comment]
Hey @Mitesh-2009, can you please follow the guidelines and provide minimal code in order to reproduce the issue? you might use our playground and mimick the behaviour you described.

**Comment by Mitesh-2009** [comment]
To reproduce the issue, create a new react native project with the latest version and install the latest version on RNN lib and try to test that app in android 9 and other android lower version emulators.

**Comment by swabbass** [comment]
@Mitesh-2009, You need to follow the guidelines and create a reproducible demo project and share it with us, we have a demo and its name is Playground and we did not manage to reproduce it in older versions of Android, so, in order to make this process efficient and since you face the issue and you know how your project is constructed and configured please create a minimal code in order to reproduce it.

If you do not want to create a new project and share it, please fork our playground and change it in a way that the problem reproduces.

**Comment by Mitesh-2009** [comment]
Working fine using https://github.com/wix/react-native-navigation/pull/7453/files solution
