### ISSUE TITLE
npx rnn-link not updating App Delegate correctly (RN 0.69.2 - RNN 7.28.1)

### ISSUE THREAD

**Issue by Huseyinnurbaki** [wix/react-native-navigation#7564]
## 🐛 Bug Report

npx rnn-link script must remove RCTAppSetupRootView. It's breaking RNN.

## To Reproduce

1. npx react-native init AwesomeProject // 0.69.2
2. npm install --save react-native-navigation
3. pod install --project-directory=ios
4. npx rnn-link

## Expected behavior

I expect script to remove lines correctly from app.delegate,mm file.
Following lines are not removed and it's breaking the navigation.

![Screen Shot 2022-07-21 at 22 15 01](https://user-images.githubusercontent.com/22790534/180348652-80c3efcd-f30a-4b4f-af82-b04225d5570c.png)

Since they are executed after rnn's registered, app throws following errors and if I dismiss it, it partially works.

```console
has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

Script requires an update. Those 2 lines must be removed. 

## Your Environment

"react-native": "0.69.2",
"react-native-navigation": "^7.28.1",
IOS

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by ApargMobile2** [comment]
Hi, after link script worked its deleted some part of my code, so what is exact fix?
can you provide me appdelegate.mm file example just with navigation ?
I'm using RN 0.69.6 version
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>

#import <React/RCTAppSetupUtils.h>

#import <Firebase.h>
#import <ReactNativeNavigation/ReactNativeNavigation.h>
#import "RNSplashScreen.h"
#import <UserNotifications/UserNotifications.h>
#import <RNCPushNotificationIOS.h>
#import <React/RCTLinkingManager.h>
#import "OpenedFromSettings.h"

#if __has_include(<VKSdkFramework/VKSdkFramework.h>)
#import <VKSdkFramework/VKSdkFramework.h>
#else
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import "VKSdk.h"
#endif


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTAppSetupPrepareApp(application);

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];




 openedFromSettings = [OpenedFromSettings allocWithZone:nil];

  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  // DatePicker Fix for IOS 14
  if (@available(iOS 14, *)) {
    UIDatePicker *picker = [UIDatePicker appearance];
    picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
  }
  [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions];

  // commentid due to bug in ios 13

  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;




  [RNSplashScreen show];

//  [[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options];
//  [VKSdk processOpenURL:url fromApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];

  return YES;
}

OpenedFromSettings *openedFromSettings;
// this function is firing when user opened application from device system notification settings: "AppName notification settings";
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
   openSettingsForNotification:(UNNotification *)notification
{
  NSLog(@"\n\n\n\nabcabc");
  [openedFromSettings sendEventWithName:@"appOpenedFromSettings" body:@{@"openedFromNotification": @"true"}];
}

-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
    completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
}

////iOS 9 workflow
//- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
//
//   [[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options];
//   [VKSdk processOpenURL:url fromApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
//    return YES;
//}

// Required to register for notifications
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
 [RNCPushNotificationIOS didRegisterUserNotificationSettings:notificationSettings];
}
// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
 [RNCPushNotificationIOS didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
// Required for the notification event. You must call the completion handler after handling the remote notification.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
// Required for the registrationError event.
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
 [RNCPushNotificationIOS didFailToRegisterForRemoteNotificationsWithError:error];
}
// IOS 10+ Required for localNotification event
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
  completionHandler();
}
// IOS 4-10 Required for the localNotification event.
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
 [RNCPushNotificationIOS didReceiveLocalNotification:notification];
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feture is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  // Switch this bool to turn on and off the concurrent root
  return true;
}

- (NSDictionary *)prepareInitialProps
{
  NSMutableDictionary *initProps = [NSMutableDictionary new];
  return initProps;
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge {
  return [ReactNativeNavigation extraModulesForBridge:bridge];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}


@end


here is mine, please tell what is wrong here?
