### ISSUE TITLE
[iOS] App gets in stuck plash screen with RN 0.71.1

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#7678]
### What happened?

Using the latest RNN 7.31.1 and RN 0.71.1, the app gets in stuck at Splash Sceen

### What was the expected behaviour?

Expect show navigation with registered screens

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version: 7.31.1
React Native version: 0.71.1
Has Fabric (React Native's new rendering system) enabled: yes
Node version: 16.13.0
Device model: Simulator
iOS version: 16.2

**Comment by pid0r-3blan** [comment]
I think the reason is the same as in #7676

**Comment by Apoorwa** [comment]
If you are using react-native-splash-screen module then try using using below file as AppDelegate.mm
`#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import "RNSplashScreen.h"
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"YOUR_APP_NAME";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};
  [super application:application didFinishLaunchingWithOptions:launchOptions];
  [RNSplashScreen show];
   return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}

@end
`

**Comment by moonjava2005** [comment]
> > If you are using react-native-splash-screen module then try using using below file as AppDelegate.mm
> 
> ```
> #import "AppDelegate.h"
> 
> #import <React/RCTBundleURLProvider.h>
> #import "RNSplashScreen.h"
> @implementation AppDelegate
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   self.moduleName = @"YOUR_APP_NAME";
>   // You can add your custom initial props in the dictionary below.
>   // They will be passed down to the ViewController used by React Native.
>   self.initialProps = @{};
>   [super application:application didFinishLaunchingWithOptions:launchOptions];
>   [RNSplashScreen show];
>    return YES;
> }
> 
> - (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
> {
> #if DEBUG
>   return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
> #else
>   return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
> #endif
> }
> 
> /// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
> ///
> /// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
> /// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
> /// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
> - (BOOL)concurrentRootEnabled
> {
>   return true;
> }
> 
> @end
> ```
> 
> After this you will just have to hide the splashscreen in your app component
> 
> ```
> useEffect(()=>{
>    SplashScreen.hide()
> })
> ```

@Apoorwa I don't use any SplashScreen or SplashBoot

**Comment by Pietro-Putelli** [comment]
Someone find a solution? My app still stuck on splash screen when doing the first indexing.

**Comment by 13thdeus** [comment]
In my case I have to init bridge manualy. 

```Json
  "react-native": "0.71.2",
  "react-native-navigation": "7.32.0",
```

In result `didFinishLaunchingWithOptions` looks like this:
```ObjC
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if (!self.bridge) {
    self.bridge = [self createBridgeWithDelegate:self launchOptions:launchOptions];
  }
  RCTBridge *bridge = super.bridge;
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.

  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

  #if RCT_DEV
    [bridge moduleForClass:[RCTDevLoadingView class]];
  #endif

  [ReactNativeNavigation bootstrapWithBridge:bridge];
  [[RCTI18nUtil sharedInstance] allowRTL:YES];
  [Splash showWithGreetings:bridge];
  [Orientation setOrientation:(UIInterfaceOrientationMask)UIInterfaceOrientationMaskPortrait];

  return YES;
}```

**Comment by moonjava2005** [comment]
@13thdeus My app get crash right after load index file, even I tried making the index file with empty content

**Comment by 13thdeus** [comment]
@moonjava2005 , in my case we have disabled Fabric in the app. You could try to add new arch specific code from this comment: https://github.com/wix/react-native-navigation/issues/7676#issuecomment-1408435169
I guess you need to add this part: 
```ObjC
  _contextContainer = std::make_shared<facebook::react::ContextContainer const>();
  _reactNativeConfig = std::make_shared<facebook::react::EmptyReactNativeConfig const>();
  _contextContainer->insert("ReactNativeConfig", _reactNativeConfig);
  self.bridgeAdapter = [[RCTSurfacePresenterBridgeAdapter alloc] initWithBridge:self.bridge
                                                               contextContainer:_contextContainer];
  self.bridge.surfacePresenter = self.bridgeAdapter.surfacePresenter;
  ```
  May be you need to exec `RCTAppSetupPrepareApp(application, YES);` method too

**Comment by Garamani** [comment]
@moonjava2005 
What errors do you get?

I could pass the splash screen by using react-native-splash-screen and the errors I get are:
**1.** 
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed.

**2.** 
Invariant Violation: "APPNAME" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

**Using:** 
```
- "react-native-navigation": "^7.32.1"
- "react-native": "0.71.4"
```

**Comment by imamabdulazis** [comment]
I was facing the same issue after upgrading from 0.69.2 to the react native 0.71.4

I commented out the Splash Screen Code, and re-run the splash screen still shows properly, I am not sure if this is only a temporary workaround.

```swift
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"YourModule";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};


  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }


  // [RNSplashScreen show];  //-->>> comment this code
  return [super application:application didFinishLaunchingWithOptions:launchOptions];;
}
```

**Comment by Garamani** [comment]
@imamabdulazis 
For the RNSplashScreen to work we need to change the last line:
`return [super application:application didFinishLaunchingWithOptions:launchOptions];
`

to this:
  ```
[super application:application didFinishLaunchingWithOptions:launchOptions];
  [RNSplashScreen show];
  return YES;
```

But either way, I get the same errors.

**Comment by kokosky93** [comment]
I have the same issue... Brand new application with "react-native": "0.70.6" stuck on default splashScreen. The issue is only with IOS.

**Comment by kevtran410** [comment]
Edit AppDelegate.mm as this comment worked for me
https://github.com/wix/react-native-navigation/issues/7676#issuecomment-1408435169

**Comment by Gabao-Farias** [comment]
> @imamabdulazis For the RNSplashScreen to work we need to change the last line: `return [super application:application didFinishLaunchingWithOptions:launchOptions]; `
> 
> to this:
> 
> ```
> [super application:application didFinishLaunchingWithOptions:launchOptions];
> [RNSplashScreen show];
> return YES;
> ```
> 
> But either way, I get the same errors.

Working here, using:

```
"react": "18.2.0",
"react-native": "0.72.1",
"react-native-splash-screen": "3.3.0"
```

**Comment by iamrohitagg** [comment]
I am getting white screen instead of Splash screen. I have done all the required changes. Please help!

**Comment by yogevbd** [comment]
hey @iamrohitagg, try to copy the [AppDelegate.mm](https://github.com/wix/react-native-navigation/blob/master/playground/ios/playground/AppDelegate.mm) and [AppDelegate.h](https://github.com/wix/react-native-navigation/blob/master/playground/ios/playground/AppDelegate.h) from the playground project.

**Comment by TechnerHarpreetSingh** [comment]
my problem is solved with this code.

# appDelegate.m

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  # ...other code
  
  # Instead of this
  [RNSplashScreen show];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
  
  # Use this.
  [super application:application didFinishLaunchingWithOptions:launchOptions];
  [RNSplashScreen show];
  return YES;
}

**Comment by TechnerHarpreetSingh** [comment]
my problem is solved with this code.

## appDelegate.m
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
   ...other code
  
  // Instead of this
  [RNSplashScreen show];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
  
  // Use this.
  [super application:application didFinishLaunchingWithOptions:launchOptions];
  [RNSplashScreen show];
  return YES;
}
```

**Comment by MRezaSafari** [comment]
> my problem is solved with this code.
> 
> ## appDelegate.m
> ```
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>    ...other code
>   
>   // Instead of this
>   [RNSplashScreen show];
>   return [super application:application didFinishLaunchingWithOptions:launchOptions];
>   
>   // Use this.
>   [super application:application didFinishLaunchingWithOptions:launchOptions];
>   [RNSplashScreen show];
>   return YES;
> }
> ```

"react-native-splash-screen": "^3.3.0",
"react-native": "0.73.1",

also fixes with this method

**Comment by eliabedossantos** [comment]
@imamabdulazis This solved my problem
