### ISSUE TITLE
SplashActivity doesn't seem to contain mainComponentName info

### ISSUE THREAD

**Issue by danieljvdm** [wix/react-native-navigation#773]
I had been dealing with the following issue: https://github.com/facebook/react-native/issues/12398 for the last week.  I eventually decided to try use `ReactActivity` and provide the`getMainComponentName` override with my main class name. Then everything started working!

So two questions: 

1) Why is `SplashActivity` not working? I looked inside the class and I'm not sure where it gets my mainComponentName from.

2) Is it safe to not use it? My app seems to be running fine without it.

Thanks

**Comment by guyca** [comment]
`mainComponentName` is an implementation detail of `ReactActivity`. Since `SplashActivity` doesn't inherit from it, theres no need to define it.
`mainComponentName` represents the entry point to your app. In RNN, you define your applications entry point and structure in the call to `startTabBasedApp` or `startSIngleScreenApp`

I'm surprised to hear it's working for you, but I'm guessing you'll soon run into issues.

You should switch back to `SplashActivity`, and read the [top level api](https://github.com/wix/react-native-navigation/wiki/Top-Level-API) section. Seems like your activity isn't started - I'm assuming your `index.android.js` isn't configured properly.
See the example project as well for more info:
[index.android.js](https://github.com/wix/react-native-navigation/blob/master/example/index.android.js)
[app.js](https://github.com/wix/react-native-navigation/blob/master/example/src/app.js)

**Comment by danieljvdm** [comment]
Thanks for the reply. I'm sure my index.android.js is fine since it's the same as my iOS version ( which works perfectly). Logcat was giving me lots of errors about not finding the project, so I'm guessing I'm not starting the activity somehow. I'm not sure what I'm doing wrong as I believe I've copied all the instructions to the letter.
