### ISSUE TITLE
UISplitViewController support

### ISSUE THREAD

**Issue by benkraus** [wix/react-native-navigation#790]
I wanted to create this to really start the discussion.

We are using this library for exactly the reasons mentioned in the README, to build a fairly sizable app in React Native. One shortcoming we found was that to build a truly universal application, (iPad & iPhone), we found it to be difficult, lacking `UISplitViewController` support.

This library seems like the perfect place to build in support for such a thing. In the deep linking docs, such an application is used an example of, so that sibling views can talk to each other.

Any thoughts on how this could be done? I'd love to contribute to this and possibly even build it out and submit a PR for it. Any directions I should or shouldn't head? Would there even be any interest in having such a thing here?

**Comment by guyca** [comment]
Hey there
This is a feature we also require for our apps, so it will definitely be supported. We're now working on the second major version of this library, practically rewriting it from from scratch. Once this is done,We'll be more comfortable accepting new features such as `UISplitViewController` from the community.

Regarding deeplinks, We've deprecated that mechanism in v2 since you'd be able to invoke screen related actions from anywhere in the app. No need to broadcast an event and handle it in a specific screen only because that screen has a navigator instance bound to it.

**Comment by chrise86** [comment]
Is this still a planned feature? Doesn't sound like it according to https://github.com/wix/react-native-navigation/issues/1148 😕

**Comment by adamski** [comment]
I think once v2 is released it will open the door for a PR to add this feature.

**Comment by bogobogo** [comment]
v2 Will support UISplitViewController

**Comment by benkraus** [comment]
Just thought I'd put this here: http://debugginghell.com/posts/native-navigation-in-react-native/

**Comment by adamski** [comment]
Thanks @benkraus, interesting read. 

> React Native Navigation made some bad assumptions in it’s codebase: that every view controller should be wrapped in a UINavigationController. Their v2 also made this incorrect assumption. This is incorrect because if you try to embed a UISplitViewController inside a UINavigationController, UIKit will throw an exception in your face.

@bogobogo @guyca how are you guys planning to get around this issue, or have you crossed the bridge already?

**Comment by bogobogo** [comment]
Hey @adamski  and @benkraus ,

After I'll be done with implementing basic custom transition animations on iOS, I will personally start working on `UISplitViewController`. I completely agree with @benkraus that it is a very important feature to have and kudos for making it happen in your own library - building your own navigation library to be able to support a feature is really impressive.

Regarding how we are going to make that happen:
Contrary to v1, v2 does not initiate it's stack with `startSingleScreenApp` or `startTabBasedApp`, but with `setRoot` precisely because we want to enable flexibility in how you structure your app.
Our aim is that v2 you will be able to have a splitViewController with tabs in one screen and a navigationController on the other - or any other thing that comes up to your mind(as long as it's supported by iOS).

Going slightly into technical details, when setRoot is called, we create a recursive data structure to represent the layout in the (take a look at [setRoot](https://github.com/wix/react-native-navigation/blob/v2/lib/src/commands/Commands.js#L11), [LayoutTreeParser](https://github.com/wix/react-native-navigation/blob/v2/lib/src/commands/LayoutTreeParser.js#L8) and [LayoutTreeCrawler](https://github.com/wix/react-native-navigation/blob/v2/lib/src/commands/LayoutTreeCrawler.js#L12). or even better, take a look at some of their [tests](https://github.com/wix/react-native-navigation/blob/v2/lib/src/commands/LayoutTreeParser.test.js)) . We pass it across the bridge to the CommandsHandler which passes it along to the [ RNNControllerFactory](https://github.com/wix/react-native-navigation/blob/v2/lib/ios/RNNControllerFactory.m) which goes over the recursive structure with the [fromTree](https://github.com/wix/react-native-navigation/blob/v2/lib/ios/RNNControllerFactory.m#L37)  function and creates the navigation stack. While it is currently true that there isn't a UISplitViewController option in there, it is certainly possible to add (and write in a way that avoids it being inside a navigationController).

Let me know if you want to hear more. We recently had a two hour video call with external contributors, going over the project structure and demonstrating how to add a feature. If there is a will, we wouldn't mind doing it again.

**Comment by benkraus** [comment]
Yeah, what I wrote was only from my experience trying it at the time, maybe March-ish?

I'd love to help out if there's any need for more help. Ours doesn't have Android support, and well, I wanna use this (which is more fleshed out, and with Android support) for my own personal project. :)

Lemme know if you need/want help at all! If you have another video call, I'd love to join!

**Comment by bogobogo** [comment]
@benkraus How can I contact you? I am bogo in the discord channel.
