### ISSUE TITLE
Side menu platform inconsistency

### ISSUE THREAD

**Issue by kevinnguy** [wix/react-native-navigation#808]
In order to show the side menu button on your navigation bar, you have to do this for both platforms.

```
  static navigatorButtons = {
    leftButtons: [
      {
        icon: require('menu.png'),
        id: Platform.OS === 'ios' ? 'menu' : 'sideMenu',
        showAsAction: 'always',
      },
    ],
  }
```

---
### Environment
* React Native Navigation version: 2.0.0-experimental.233
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
Hey
No need to specify `showAsAction: 'always'`, it only controls when buttons get pushed to the overflow menu.
The reason the Left button on Android is an enum is because the left button is either the back button or the menu button and their respective icons are provided by the system. On iOS, the menu is not a supported component, therefor you're required to provided an icon.
iirc you don't have to use `menu` id on iOS.

**Comment by kevinnguy** [comment]
@guyca thanks for the explanation!
