### ISSUE TITLE
Integrate RNN into a native IOS swift project

### ISSUE THREAD

**Issue by MartinMobilize** [wix/react-native-navigation#813]
Hi,
I have a native IOS (swift based) project.

I want to integrate some RN flows (for example login flow) into my native app.

I followed all your installation steps but i don't know how to configure the AppDelegate file, cause i don't have any AppDelegate.h or Appdelegate.m files.

Right now i'm getting an error "cannot read property 'setRootController' of undefined".

Probably is because i'm missing the last installation step.

How i'm supposed to configure the last installation step in a swift project?

**Comment by LeoNatan** [comment]
Do you already have React Native integrated and working in your project?

**Comment by MartinMobilize** [comment]
Yes.

I was able to show a RN screen (passing props from the native code).

But when i called the Navigation.startSIngleScreenApp method on my RN class i got this error

**Comment by LeoNatan** [comment]
If you integrated using CocoaPods, I am not sure it will work. CocoaPods integrates RN differently than how RNN expects RN to be integrated. RNN does not support CocoaPods.

Which integration guide did you follow for Navigation? The [one in the wiki](https://github.com/wix/react-native-navigation/wiki/Installation---iOS#installation---ios)? Unfortunately, that guide is quite outdated, and should not be followed for RN 0.40 projects (CC @DanielZlotin @gran33 @guyca).

**Comment by MartinMobilize** [comment]
I integrated using cocoapods(from RN docs) and RNN from your wiki docs :)

**Comment by MartinMobilize** [comment]
So how im supposed to install the RN into the swift project and then install RNN?

**Comment by LeoNatan** [comment]
I think it will not work. CocoaPods integrates RN as a dynamic framework, which will not work with how RNN needs include files. You need to manually integrate RN. To do that, use npm/yarn to bring react-native as a dependency of your project (using package.json).

Add React.xcodeproj, RCTActionSheet.xcodeproj, RCTGeolocation.xcodeproj, RCTImage.xcodeproj, RCTLinking.xcodeproj, RCTNetwork.xcodeproj, RCTSettings.xcodeproj, RCTText.xcodeproj, RCTVibration.xcodeproj, and RCTWebSocket.xcodeproj into your project (they are scattered somewhere in the node_modules/react-native dir hierarchy. Under your scheme’s build settings, disable parallel building, and add the React target as the first build target. Finally for your target, add each of the build artifacts (React.a, RCTActionSheet.a, etc.) to “Link with Libraries”.

Now add RNN version that supports 0.40 and above (@guyca assist here, what is the version?) into your package.json and install. Add ReactNativeNavigation.xcodeproj to your project, and add ReactNativeNavigation.a to your target’s Link with Libraries.

**Comment by guyca** [comment]
latest rnn support 0.40

**Comment by DanielZlotin** [comment]
CocoaPods is not (and won't be) supported.
Swift on the other hand, shouldn't be a problem.

I'm not sure this is related to swift - If you're trying to add react-native-navigation into an existing native project, we don't currently support that (although I guess you could hack it somehow). This would require to support 2 APIs - as more than 95% of our users don't need this use case and would rather use RNN as a framework (we do all the native stuff for you).

The logic behind this is that if you write native, you can control all the Activities/UIViewControllers yourself and have very minimal use for RNN.

I'm not against supporting this, but this would come at a maintenance cost.

If you would like that, please open an issue with this request and we'll try to implement it after v2.0.0 is out.

**Comment by joshyhargreaves** [comment]
@DanielZlotin is there any reason why `cocoapods` shouldn't be supported via a `podspec` in the repo? I can speak for myself in saying that cocoapod usage is not only for users with existing projects; with existing projects being a use case you wish to (sensibly) discourage. 

I personally don't really have anything against manually linking a library in manually, however it seems to be causing issues with a few users of `RNN`, including myself, who are managing their `react-native` dependency via `cocoapods`; again, I do not think this is that uncommon a use case. The issue is question is XCode not being able to find `react` native header files, this would seem to be because of the implicit dependency `RNN` has on `RN`, and of course the order in which the projects are built does seem to be an issue. 

I have tried the steps you mentioned about disable parallelising the build, but not such luck for myself. 

I did however simply create a `podspec` for `RNN` and was then able to `pod install` `RNN` as a dependency successfully. This is the Github issue in question: [link](https://github.com/wix/react-native-navigation/issues/1061). 

As for the podspec, here it is: [link](https://github.com/wix/react-native-navigation/compare/master...joshyhargreaves:add_podspec_to_rnn?expand=1)

`RNN` can then be added a `pod` dependency as follows: `pod 'react-native-navigation', :path => '../node_modules/react-native-navigation`

**Comment by DanielZlotin** [comment]
There are bunch of separate issues here.
1. supporting swift projects - should already work, nothing to do with rnn
2. supporting existing apps with existing view controllers - see #1234 
3. supporting projects with cocoapods: shouldn't be an issue, probably requires changing the build order in xcode though or something
4. supporting installation of RNN through cocoapods:
I don't really understand the benefit of this. From what I can tell, this only saves you the manual drag-drop into your `Libraries` step. You still have to do the other steps in the installation guide. Can you elaborate?

**Comment by joshyhargreaves** [comment]
I agree with 1 & 2. 

3 & 4. Most `brownfield` `iOS` projects install `react-native` via cocoapods in the way that is recommended in the [documentation](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#podfile). Using a `podfile` in this case lets you specify which `RN` modules to build in your project. If you were not to use `cocoapods` in this instance, you would need to follow the manual drag and drop steps for `RNN` for every single `RN` sub-project (so     'Core','RCTText', RCTNetwork', 'RCTWebSocket' ...) and this can be time-consuming and error-prone. `Cocoapods` also lets you define dependencies for each target without needing to do that manually within XCode too. 

As @LeoNatan said  in this thread:

> CocoaPods integrates RN as a dynamic framework, which will not work with how RNN needs include files. You need to manually integrate RN

It may not be possible to install `RNN` when you have `react-native` installed via `cocoapods` when `using frameworks` unless you install `react-native` by manually adding each `sub-project` as described. 

@LeoNatan I'm not sure if have anything to say about adding a `podspec` to `RNN`: [link to podspec](https://github.com/wix/react-native-navigation/compare/master...joshyhargreaves:add_podspec_to_rnn?expand=1). Are there any compelling reasons not to? This `podspec` works for myself when installing `RNN` via `cocoapods` and solves the build issues I was having.

**Comment by LeoNatan** [comment]
The most compelling reason is having to support and maintain something we do not use (or believe in) internally. Since we do do not wish to use CocoaPods internally, supporting it would require some learning curve and overhead.

So the question becomes "can RNN be used with a CocoaPods RN installation". I do not know the answer to that in a post-0.40 worlds. Facebook changed the way headers are discovered in 0.40, and it may or may not be possible to mix. We need to check this internally. Other open question we have is, how does CocoaPods play with node modules (the JS side)? The JS portions of RNN have dependencies which are resolved using npm/yarn. Simply bringing the Xcode sources of RNN is not enough. So please shed a few words here on this issue @joshyhargreaves.

A word on CocoaPods. In my own open source projects, I have categorically declined to support CocoaPods in favor of better options, such as Carthage. Some (but not all) of my reasons for disliking CocoaPods are eloquently written by Derek [here](http://drekka.ghost.io/cocoapods-vs-carthage/) and [here](http://drekka.ghost.io/cocoapods-vs-carthage-part-ii/). My projects are Xcode projects, and thus, really do not limit other uses of CocoaPods. In this case, it could be different. If indeed mixing CocoaPods RN with an external module is not possible, we should add support for CocoaPods. If it is possible, and the only benefit of CocoaPods support is saving the user having to drag the project into Xcode and adding to linked frameworks, I really do not see this happening. We need to investigate and see what is possible and what is not.

**Comment by joshyhargreaves** [comment]
I understand your question about maintenance now, sorry. To answer your question about `cocoapods` and JS portions of RNN, all `cocoapod` support would require is adding a [podspec](https://github.com/wix/react-native-navigation/compare/master...joshyhargreaves:add_podspec_to_rnn?expand=1) to the repo. RNN would be installed with yarn/npm as per usual, and `cocoapods` users would simply need to add a reference to RNN in their `node_modules` dir like so `pod 'react-native-navigation', :path => '../node_modules/react-native-navigation`. All dependencies would be managed via `npm` :). React native is also managed in this same way. 

As for podspec maintenance Airbnb's `react-navigation` `podspec` has only been touched twice since the project creation, for [example](https://github.com/airbnb/native-navigation/commits/master/native-navigation.podspec). 

Yes you're right, I do agree that "can RNN be used with a CocoaPods RN installation" is the better question to ask, and that would be a good question for us to answer and this can inform us going forward. I'm perfectly open to installing the manual way, if there's a straightforward way to do it with an `RN cocoapods installation`.

**Comment by LeoNatan** [comment]
Good. We intend to investigate this topic, and we expect to have an answer soon.

**Comment by LeoNatan** [comment]
@joshyhargreaves @MartinMobilize We’ve investigated, and have found that we need to add CocoaPods support. We’ll be including this support in v2 soon.

**Comment by DanielZlotin** [comment]
This wasn't an easy decision, we tried everything we could to make it work without the podspec, but alas cocoapods and node_modules don't go hand in hand.
This is another friction point for the project, and it will tend to break for unexpected reasons, but currently we realized we have no choice.
For example, in RN44 pods are [broken](https://github.com/facebook/react-native/issues/13198) as of today.

**Comment by DanielZlotin** [comment]
See https://github.com/wix/react-native-navigation/commit/08524de645cfa11848b745d2f9db23d3a4863b5c

**Comment by joshyhargreaves** [comment]
Thanks for taking the time to look into this and do your own investigations
to see if there was another. I agree, it is another friction point and
definitely might be worth seeing if we could add some tests to prevent
breakage.

Thanks again.

**Comment by Warpenguin** [comment]
Thanks for adding cocoapods support!

How would one configure the ViewController.swift file in a swift project to work with RNN v2? Is it possible or would I have to switch to an Obj-C project and refer to https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m ?

**Comment by LeoNatan** [comment]
If you are using CocoaPods, use the `use_frameworks!` directive. Then, there should be a ReactNativeNavigation framework you can import in Swift and use the API there.

**Comment by adamski** [comment]
Regarding Cocoapods, I created a very minimal tool to help with this: https://github.com/adamski/podspec-generator

Could do with some improvements but works for me to simple generate a Podspec for RN modules that don't provide one.

**Comment by jlyonsmith** [comment]
Just wanted to post a follow on for anyone else who's come here wondering how to integrate this component using Cocoapods.   I've created a [jlyonsmith/react-native-navigation](https://github.com/jlyonsmith/react-native-navigation) fork with the necessary changes.  It was simply a matter of adding a `ReactNativeNavigation.podspec` as mentioned per commit [08524de](https://github.com/wix/react-native-navigation/commit/08524de645cfa11848b745d2f9db23d3a4863b5c) with the `s.source` entry pointing to my fork and not the `wix` repo and adjusting the source file locations from `lib` as they seem to be in 2.0.   There's some issues building RN at the moment because of compiler errors in `yoga`, so here is the `Podfile` that is currently working for me:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'ReactNativeNavigation', :podspec => '../node_modules/react-native-navigation/ios/ReactNativeNavigation.podspec'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'yoga'
            target.build_configurations.each do |config|
                config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
                config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
            end
        end
    end
end
```

If you want to install directly from my fork use `npm install jlyonsmith/react-native-navigation`.  It would be _really_ nice if the team here would consider integrating this change into v1.0.  Even though v2.0 is the shiney, it's not a great idea to ship a product using an alpha release component. 

Great library guys.  Thank you very much for all the hard work!!!  🥇

**Comment by adamski** [comment]
I built a little utility for generating podspecs from React Native iOS modules: https://www.npmjs.com/package/podspec-generator

I use that for my project, RN 0.51. YMMV - I don't use Swift.
