### ISSUE TITLE
How to use remote image for titleImage property on titlebar

### ISSUE THREAD

**Issue by bluwave** [wix/react-native-navigation#852]
### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.startTabBasedApp({
      tabs: [
        {
          label: 'foo',
          screen: 'myScreen',
          title: 'foo',
          icon: require('./src/images/tab-bar/foo.png'),
          titleImage: 'http://pathTo/MyImage.png',
        },
      ],
    })
```

---
### Environment
* React Native Navigation version: 2.0.0-experimental.236
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS 10 Debug

**Comment by gran33** [comment]
Hi @bluwave,
`titleImage` can show image form your app only and NOT remote images.
So, in order to show the `titleImage` on the `navigationBar` u have 2 options:

1. Add the image to the code base (bundling with your app), and use it like this: `require('<YOUR_IMAGE_PATH>')`
2. In order to load the image remotely, u need to download it first (on runtime), save it, get the **local** path, and use as above `require(<YOUR_IMAGE_PATH>)`

If u have any other question, feel free to ask.

Good luck!
