### ISSUE TITLE
Handle different Screens

### ISSUE THREAD

**Issue by aayushcoder** [wix/react-native-navigation#881]
I'm trying to display login/signup screen first and then route to Tabs or Drawer. How can we implement this functionality ? 

### Environment
* React Native Navigation version: 2.0.0-experimental.252
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?):  both

**Comment by bogobogo** [comment]
Hey @aayushcoder, 

You can use `Navigation.startSingleScreenApp` and ` Navigation.startTabBasedApp`  whenever you want and more than once. A simple logic flow would be:
1) In your initialization function check if user is signed in. 
2) If he isn't use `Navigation.startSingleScreenApp` with your signup/login screen:
3) When he finishes the login process run `Navigation.startTabBasedApp` with your home screen.

If the user is logged in just skip stage 2 and go straight to `Navigation.startTabBasedApp`

You can find the top level API [here](https://github.com/wix/react-native-navigation/wiki/Top-Level-API)

**Comment by alexxsanchezm** [comment]
Hi, @bogobogo since your approach may work, In the documentation is not clear enough how you can build a multiscreen app without being tab based app. I mean, not every developer wants to build just a tab based app or a single screen app, that doesn't make sense, at least for me. I hope any other can understand.
