### ISSUE TITLE
Context?

### ISSUE THREAD

**Issue by natdm** [wix/react-native-navigation#885]
How is everyone passing Context to their application? I have a logger that I use that sends logs to an external API, and the old app just had context passed down from the root app that was rendered. That doesn't seem to be able to work with this library.

**Comment by DanielZlotin** [comment]
You can pass whatever you want down the props of your screen components. Passing a prop to all screen *roots* is kinda different from the way you are used to do it in web - because here we have multiple root components (each screen is a different root).

What you can do is create a higher order component which will encapsulate all your screens, something like so (untested code, YMMV):

```javascript

import React, { Component } from 'react';

function wrapWithContextProvider(Comp) {
  return (props) => {
    return (
      <Comp {...props} someOtherProp="this will be available in the screen root component" />
    );
  };
}

Navigation.registerContainer(`com.example.foo`, () => wrapWithContextProvider(MyScreen));
```

**Comment by natdm** [comment]
Thanks. I was hoping for context. Looks like this doesn't work. I get this error: http://imgur.com/a/g8oke

Code:

```js
function wrapWithContextProvider(Comp) {
  return (props) => {
    return (
		<LogCtx logger={new applogger(Platform.OS)}>
			<Comp {...props} />
		</LogCtx>
    );
  };
}

function registerComponents(components, store, provider) {
	components.forEach(c => {Navigation.registerComponent(c.screen, () => {wrapWithContextProvider(c.component), store, provider})})
}

const comps = [
	{screen: screens.login, component: LoginScreen},
	{screen: screens.searchModal, component: Search},
	{screen: screens.searchResults, component: SearchResults},
	{screen: screens.eventHome, component: EventDetails},
	{screen: screens.items, component: Items},
	{screen: screens.findEvent, component: FindEvent},
	{screen: screens.notifications, component: Notifications},
	{screen: screens.settings, component: Settings},
	{screen: screens.item, component: Item},
	{screen: undefined, component: UndefinedRoute},
]

// register all screens of the app (including internal ones)
export const registerScreens = (store, Provider) => registerComponents(comps, store, Provider);
```

where `LogCtx` is the following:

```js
import React, {Component} from 'react';

class LogCtx extends Component {
    getChildContext() {
        return {
            logger: this.props.logger
        }
    }
    render() {
        return this.props.children;
    }
}

LogCtx.childContextTypes = {
    logger: React.PropTypes.object
};

export default LogCtx;
```

**Comment by DanielZlotin** [comment]
looks like there's something not right with the syntax. maybe try:
```javascript
function registerComponents(components, store, provider) {
  components.forEach((c) => {
    Navigation.registerComponent(c.screen, () => wrapWithContextProvider(c.component), store, provider)
  });
}
```

**Comment by johngoren** [comment]
Wondering if this technique could be used with the cool new Context API to update dynamically as things change, or if it's better left to static variables.

**Comment by EdwardDrapkin** [comment]
We're using react-native-navigation and we wanted to skip a heavy state container (redux, rxjs, etc.) and use the new Context API instead.  We're using plain old EventEmitters to issue commands across the application; for example, to issue an API request for a new user status, you emit 'refresh_customer_status', which makes the request and eventually emits a 'new_customer_status' with the new customer status data object.

I was able to achieve this goal fairly simply by setting up a wrapping ContextProvider class that provided statically cached (outside of a react component) data and listened for the data events to call forceUpdate().  I'm not caching the actual data in ContextProvider.state because each screen the navigator mounts gets its own ContextProvider and that seemed like using more memory than necessary.

So here's an example, in code:

First, we need to declare the context and the function we'll use to wrap our components:
```
export const MyContext = React.createContext({});

function wrapWithContext<Props: {}, C: ComponentType<Props>>(Component: C): C {
    return hoistNonReactStatics((props: Props) => {
        return (
            <ContextProvider>
                <Component {...props}/>
            </ContextProvider>
        );
    }, Component);
}
```

Next, the static cache (can be encapsulated in an object if you want but just for simplicity, I'm leaving it as a file-level variable so it will live in the require cache:

```
let userStatus = null;

emitter.on('new_customer_status', (status: UserStatusDescriptor) => {
    userStatus = status;
});
```

Next, the ContextProvider component itself:

```

export class ContextProvider extends React.PureComponent<Props, State> {
    componentDidMount() {
        emitter.on('new_customer_status', this.listenForCustomerStatus);
    }

    componentWillUnmount() {
        emitter.removeListener('new_customer_status', this.listenForCustomerStatus);
    }

    listenForCustomerStatus = () => {
        this.forceUpdate();
    };

    render() {
        const Provider = MyContext.Provider;

        return (
            <Provider value={{ userStatus }}>
                {this.props.children}
            </Provider>
        );
    }
}

```

And finally, the registration that ties it all together:

```js

// registrations is a map of {key: Component}
Object.keys(registrations).forEach((key) => {
    Navigation.registerComponent(key, () => wrapWithContext(registrations[key]));
});

Navigation.startSingleScreenApp({
    screen: {
        screen: 'root',
        title: 'welcome',
        navigatorStyle: {
            navBarHidden: true,
        },
    },
});

```

So now any component that has an ancestor mounted by react-native-navigation can import `MyContext` and use the context; and the data is stored in exactly one place and shared between Contexts, so there's not a huge memory overhead in not sharing a single global root element.

**Comment by sturmenta** [comment]
I solved it in this way:
```javascript
const wrapWithToastProvider = Comp => props => (
	<ToastProvider>
		<Comp {...props} />
	</ToastProvider>
);

Navigation.registerComponent('myschool.login', () => wrapWithToastProvider(Login), store, ReduxProvider);
```

**Comment by atrimn** [comment]
@sturmenta  thanks this was a great solution

**Comment by atrimn** [comment]
@sturmenta hey this approach seems to create a new instance of state for all my screens.
do you know a way around it?

**Comment by sturmenta** [comment]
@atrimn
[This may be useful](https://github.com/wix/react-native-navigation/issues/3549#issuecomment-411800487)
