### ISSUE TITLE
Duplicate Class Declaration?

### ISSUE THREAD

**Issue by natdm** [wix/react-native-navigation#932]
### Issue Description

Getting Duplicate Declaration in the Navigation module:
![Imgur](http://i.imgur.com/jG0kkKe.jpg)

    - "react-native-navigation": "^2.0.0-experimental.253",
    - "react-native": "0.42.0",

how do I remedy this? I'm not an ObjC developer sadly.

**Comment by DanielZlotin** [comment]
It looks like React library is linked twice..
Make sure your project settings are correct as written [here](https://github.com/wix/react-native-navigation/wiki/Installation---iOS#installation---ios),

also, make sure you have only 1 instance of react in these places: 
![screen shot 2017-03-26 at 13 48 44](https://cloud.githubusercontent.com/assets/6660239/24330643/dd268852-122b-11e7-8012-6a2ba6466c43.png)

**Comment by urbancvek** [comment]
The problem you are having is because the wrong version of react-native-navigation get's installed. Even though you specify you want the latest somehow sometimes 2.0.0-legacy something version get's installed.

You can check this in node_modules/react-native-navigation/package.json. Look at the _resolved key and it should be set to what I said. This means that library that get's installed still uses the old import versions which look like this:
```
#import "RCTBridgeModule.h"
```

Instead they should look like this to work with react-native 0.40 and above.
```
#import <React/RCTBridgeModule.h>
```

Why this happens is beyond me... But the solution is to just manually install the version you want. For example:
```
npm i --save react-native-navigation@2.0.0-experimental.256
```

Just spent too much time on this and it works for me. Hope this helps you too.
