### ISSUE TITLE
Calling setTitle from open drawer does not work

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#984]
### Issue Description

When calling [setTitle](http://wix.github.io/react-native-navigation/#/screen-api?id=settitleparams-) from opened drawer the title won't change. But if drawer is closed and call `setTitle` it indeed changes the title of navigator :)

---
### Environment
* React Native Navigation version: v2.0.0-experimental.271
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): BOTH
* Device info (Simulator/Device? OS version? Debug/Release?): Real device

**Comment by guyca** [comment]
Hey @henrikra 
Each screen has it's own title, and navigator. Calling `navigator.setTitle` from a screen works since the screen has a title.

instead of calling `setTitle` from the SideMenu, [dispatch a deeplink](https://wix.github.io/react-native-navigation/#/deep-links?id=deep-links) and call setTitle from the relevant screen.
